## Evakuierung nach Rennersdorf und Befreiung in Görlitz

Der Begriff des Todesmarsches ist keine Wortschöpfung der Historiker,
sondern von den Häftlingen der Konzentrationslager geprägt worden.
Darunter verstehen sich erzwungene Märsche bewachter Gefangenenkolonnen
über längere Distanzen und unter schlechten Bedingungen, in deren
Verlauf viele der Häftlinge brutal gefoltert und ermordet wurden[^1].
Insbesondere in der Endphase des Krieges, als sich die alliierten Armeen
den Lagern bedrohlich näherten, stellten viele Konzentrationslager ihre
Funktion ein und evakuierten die Gefangenen in andere Lager. Nicht um
deren Leben willen, sondern um deren Arbeitskraft für die deutsche
Kriegswirtschaft weiter ausbeuten zu können. Der Begriff der
Evakuierung kann in diesem Zusammenhang auch als verleumderischer
Ausdruck dem SS-Jargon zugeschrieben werden, da die SS sich der Tatsache
bewusst gewesen sein muss, nicht nur Bewohner eines Gebietes an einen
anderen Ort zu schaffen, sondern damit das Leben der Gefangenen zu
riskieren. Einige Evakuierungen erfolgten auch mit der Eisenbahn, doch
im Fall Görlitz wird im Folgenden klar, dass die Situation im Februar
1945 dies nicht zugelassen hätte. Genau wie die Evakuierung der
Konzentrationslager, wurde auch die Evakuierung der deutschen
Bevölkerung durch die Operationen der sowjetischen Armee in Schlesien
diktiert[^2].Nun, nachdem schlagartig alle Einwohner Schlesiens, sofern
sie noch zu Hause waren (d.h. im Wesentlichen: Frauen, Kinder, Alte,
Kranke, Krüppel, Strafgefangene und KZ-Insassen), in Schnee und Kälte
(-20 Grad Celsius) über Görlitz nach Westen drängen, ergreift uns der
Strudel selbst., schrieb ein Görlitzer Pfarrer[^3] am 11. Februar in
sein Tagebuch. Der Historiker Alfred Konieczny gliedert die Evakuierung
der schlesischen KZ-Außenlager in drei Etappen[^4]. Jede dieser Etappen
wirkte sich auf eine andere Art verheerend auf die Situation der
Häftlinge im KZ-Außenlager Görlitz aus. In der ersten Etappe
funktioniert das KZ-Außenlager als Durchgangs- und Auffanglager anderer
evakuierter Lager. In der zweiten Etappe wird das Lager selbst evakuiert
-- in ein provisorisches Lager im 35 km entfernten Rennersodrf. Die
dritte Etappe ist jedoch einmalig im Vergleich zu anderen Groß-Rosener
Außenlagern. Die Häftlinge müssen zurück nach Görlitz und werden
gezwungen, die Stadt als Festung auszubauen.

### Das KZ-Außenlager Görlitz als Durchgangs- und Auffanglager anderer evakuierter Lager

Diese von Alfred Konieczny[]{#eva_2 label="eva_2"} beschriebene Etappe
war die Folge der Annäherung der Roten Armee an die Oderlinie während
der zweiten Januarhälfte 1945. Seit dem 27. Januar war das KZ Auschwitz
bereits befreit, die meisten Häftlinge jedoch vorher noch auf andere
Konzentrationslager, insbesondere Groß-Rosen, verteilt worden. Ende
Januar, so heißt es in einem Bericht eines ehemaligen Görlitzer
Insassen, quartierte man Häftlinge aus Auschwitz für eine Nacht im Lager
Görlitz ein[^5]. Ferner berichtet dieselbe Person auch von der Ankunft
eines Eisenbahnwaggons mit Dokumenten aus Auschwitz[^6].

Alle Groß-Rosener Außenlager rechtsseitig oder unmittelbar an der Oder
wurden evakuiert. Dies betraf insgesamt 11 Männer- und Frauenlager[^7].
Um den 10. Februar machte der Kommandant des Stammlagers Groß-Rosen,
Johannes Hassebroek, zusammen mit dem größten Teil seines Stabes für
eine Woche in Zittau Station, um sich dann in das Außenlager Reichenau
im Sudetengau abzusetzen.[^8] Von Zittau und später von Reichenaus aus
hält Hassebroek Kontakt zu den Evakuierungsmärschen und lässt sich deren
Standorte und Ausfälle durchgeben. Bereits am 15. Februar ist in einem
Heeresbericht vom Frontverlauf entlang der Städte Sommerfeld, Sorau,
Bunzlau und Goldberg die Rede. In diesem Zusammenhang ist es
wahrscheinlich, dass viele Todesmärsche die Stadt Görlitz passierten und
vielleicht auch im KZ-Außenlager stoppten. Hinweise darauf finden sich
in Erzählungen von Leuten, die damals in der Stadt oder in der näheren
Umgebung beheimatet waren[^9]. Nathan Klajman, ein Gefangener des
Außenlagers Kittlitztreben (Trzebień, Polen), bestätigt diese Vermutung
ebenso, wie der ehemalige Bunzlauer KZ-Häftling Simon Schweitzer. Nathan
Klajman, der bereits im Görlitzer Lager der Organisation Schmelt
inhaftiert war, bezeugt, dass während der Evakuierung des KZ-Außenlagers
Kittlitztreben eine große Zahl Kranker im Lager Görlitz zurückgelassen
wurde. In der Aussage von Nathan Klajmans heißt es:

::: leftbar
Am 9. Februar 1945 wurden wir informiert, dass unser Feind (die Russen)
heranzieht. Wir wurden gezwungen, das Lager zu verlassen. Es begann eine
Wanderung. Wer nicht imstande war weiter zu gehen, wurde sofort
totgeschlagen. Nachts lagen wir oft im Schnee. Wir hatten keine
Möglichkeit, um etwas zu essen. \[\...\] Wir liefen durch Görlitz
hindurch. 100 kranke Leute wurden im Görlitzer Lager zurückgelassen. Wir
kamen nach Zittau. Dort waren schon 300 Juden.[^10]
:::

Die Häftlinge aus Kittliztreben verließen nach ein bis zwei Tagen das
Lager und gingen über Dresden bis nach Buchenwald. Von den anfänglich
2000 Gefangenen sollen nur 360 überlebt haben[^11]. Simon Schweitzer
schreibt, dass er Mitte Februar 1945 mit einer Kolonne Bunzlauer
Häftlinge unter der Führung des Hauptsturmführers Michael[^12] im Lager
Görlitz eintraf. Das Groß-Rosener Außenlager Bunzlau wurde kurz nach
seiner Evakuierung von den sowjetischen Truppen erobert. Nach einem
mehrtägigen Marsch wollte man in Görlitz vor allem pausieren und
verwundete Häftlinge medizinisch versorgen. Der Görlitzer
Lagerkommandant Rechenberg hatte darum gebeten, seine Gefangenen und
Wachleute der Bunzlauer Kolonne anzuschließen. Angesichts des miserablen
gesundheitlichen Zustands der Görlitzer Häftlinge wäre es den hiesigen
Lagerinsassen jedoch unmöglich gewesen, mit den wesentlich kräftigeren
Häftlingen aus Bunzlau Schritt zu halten. Michael lehnte Rechenbergs
Anliegen ab und verurteilte den katastrophalen Umgang mit
kriegswichtigen Arbeitskräften im Lager Görlitz lautstark gegenüber dem
ihm unterstellten Lagerkommandanten[^13]. Neben den bisher erwähnten
männlichen Gefangenen, kam es im Februar 1945 auch zur Überstellung von
weiteren Jüdinnen. Obwohl vielfach von inhaftierten Polinnen berichtet
wird, gibt Anna Hynráková Grund zu der Annahme, dass selbige erst kurz
vor der Evakuierung des gesamten Görlitzer Lagers, also wenige Tage vor
dem 18. Februar 1945, eintrafen[^14]. Dies deckt sich mit der vielfach
bestätigten Überstellung von 120--180 polnischen Frauen aus dem
Frauenlager Ludwigsdorf (Bojanice, Polen)[^15]. Es deutet sich an, dass
die Evakuierung des Lagers Görlitz und damit die zweite Etappe[^16] kurz
bevor stand, bzw. zu dem Zeitpunkt an einigen Orten schon begonnen
hatte[^17].

### Evakuierung des Lagers

In einem Verwaltungsbericht der Stadt Görlitz vom 18. Ferbuar 1945 heißt
es: Die Lage ist so kritisch, dass mit Eindringen des Feindes jeden
Augenblick gerechnet werden muss[^18]. Zu diesem Zeitpunkt waren bereits
einige Besitzungen der Stadt, wie etwa die Heide und die Grube in
Kohlfurt, von der sowjetischen Armee besetzt. Bereits am Abend des 16.
Februar ereilte ein Räumungsbefehl die in der Stadt befindlichen
Zivilisten. Die Gefangenen im KZ-Außenlager standen dieser Tage schon
bereit zum Abmarsch[^19], bevor am Sonntag, dem 18. Februar, Kreisleiter
Malitz den endgültigen Befehl zum Abmarsch erteilte[^20]. Sinngemäß ließ
der Lagerführer gegenüber den Häftlingen verlauteten: Da ihr als Feinde
des Volkes in der Stadt Görlitz unerwünscht seid, müssen wir die Stadt
verlassen[^21]. Gerhard Anton Sedlak, der Fuhrparkleiter der WUMAG im
Biesnitzer Grund[^22], erinnert sich dessen:

::: leftbar
Während der Räumung des Lagers Biesnitzer Grund durch die Häftlinge im
Februar 1945 befand ich mich in dem Fuhrpark und hörte von dort aus
wiederholt Schüsse. Nachdem das Groß \[im Sinne von: der Großteil\]
abgezogen war, ging ich durch das Lager und stellte fest, dass mehrere
Häftlinge teils erschossen, teils aus anderen Ursachen -- anscheinend an
Schwäche -- verstorben auf dem Erdboden lagen. Ich persönlich kann mich
heute an 10--12 Leichen erinnern, die ich hier vorfand. \[\...\]
Außerdem fanden sich weitere schwache, noch lebende Häftlinge im Lager,
die sich gegenseitig um Hilfe anflehten. Ich selbst traute mich nicht,
ihnen Hilfe zu gewähren, weil ich damit rechnen musste, dass die zum
Nachkommando gehörenden SS-Leute mich im Falle der Hilfeleistung
erschießen würden.
:::

Bereits am 12. Februar wurden etwa 100 kranke Gefangene ins Nebenlager
Zittau überstellt[^23]. Weitere gehunfähigen Menschen blieben zunächst
im Lager zurück[^24], ebenso jene für den Lagerbetrieb unabdingbare
Häftlinge, wie z.B. dem Arzt Jakob Kinrus oder dem Elektriker Jechiel
Rappaport[^25]. Insofern kann davon ausgegangen werden, dass man mit der
Evakuierung nicht beabsichtigte, die Stadt judenrein zu machen, sondern
lediglich darauf bedacht war, die Arbeitskräfte an einem sicheren Ort zu
verwahren und bei Bedarf zurück zu holen. Die Tatsache, dass die
Gefangenen im nur vier Kilometer entfernten Kunnerwitz mehrere Tage
verweilten, spricht für diese Vermutung. Offenbar waren die
Entscheidungsträger fest davon überzeugt, die Stadt Görlitz auf lange
Sicht zu verteidigen und die Rote Armee weiter zurückzudrängen. Ohne
diesen Gedanken vom Endsieg und der wirklichkeitsfremden Vorstellung
sich als Festungsstadt behaupten zu können, hätte das Schicksal der
zurückgelassenen Kranken ebenso Erschießung durch die SS oder Befreiung
durch die Rote Armee heißen können.  

::: leftbar
Czech befahl \[\...\] den zum Bleiben bestimmten Personen, den anderen
ihre Holzschuhe zu geben. Er befahl den Kranken auch, ihre Mäntel und
Decken abzugeben.[^26]
:::

::: leftbar
Zuerst verließen lange Frauenreihen, und hinter ihnen Männerreihen, die
Lagertore. Es begann ein Ereignis von kurzer Dauer, das zu den
dramatischsten in meinem Lagerleben zählt. Auf den Landstraßen und auf
den wenig benutzten Wegen schleppten wir uns unter Aufsicht der
SS-Männer Richtung Osten. Der Winter war diesmal nicht streng, aber in
den dünnen Sträflingsanzügen froren und zitterten wir, da es Schneeregen
gab und wir mit Holzschuhen durch den kalten Matsch liefen. Ich ging
eingekuschelt in einer kaputten Pferdedecke, die von einer Pritsche
herunter genommen wurde. Jeder Gefangene versuchte sich etwas zu
besorgen, in diesem Moment wurden die Vorschriften nicht von der Eskorte
vorgeschrieben. Meine Füße waren mit Lappen umwickelt, welcher als
Fußlappen dienten. Mühelos lernte ich diese Art mir die Füße zu
umwickeln; sie war besser als Vorkriegsstrumpfhosen oder Socken. Ich
bemühte mich während des Gehens vorn mitzulaufen, weil hinten eine
größere Gefahr bestand. Hinten gingen die Schwächeren, Kranken und
Nichthinterherkommenden. Trotz ihrer Mühe wurden die Abstände immer
größer, sie versuchten verzweifelt nachzukommen, riefen Kumpels, um auf
sie zu warten, aber es ging nicht. Mit letzter Kraft versuchten sie
aufzuholen, dabei fielen sie in den Dreck. Eskortierende Soldaten
schossen ihnen mit Pfeilen in den Kopf. Unseren Weg konnte man durch die
da liegende Leichen verfolgen.[^27]
:::

Nach dem Abmarsch der Gefangenen kehrte Hermann Czech ins Lager zurück,
um einige Kranke nachzuholen[^28].

Während des gesamten Marsches zogen und schoben die Gefangenen gewaltige
Wagen mit sich, auf denen sich neben einigen Lebensmitteln und
persönlichen Dingen der SS und Funktionshäftlinge auch die Karthoteken
der Lagerinsassen befanden[^29]. Die Bewachung der Gefangenen übernahmen
neben den älteren SS-Leuten auch eine Reihe ukrainischer SS-Männer. In
den Verwaltungsberichten der Stadt Görlitz findet sich während der
letzten Kriegsjahre ein Hinweis auf ukrainische Schutzmannschaften der
Landesschützen-Polizei, die am 30. März 1944 von Sosnowitz mit ihren
Familien nach Görlitz überstellt wurden[^30], doch ist es nicht sicher,
ob dieselben den Evakuierungsmarsch begleiteten.

#### Der Weg des Todes

Die Evakuierung vollzog sich innerhalb von fünf Tagen über eine Strecke
von etwa 35 Kilometern (siehe Karte: ). Dabei machte die Marschkolonne
mehrmals Station. Die erste Etappe endete im sechs Kilometer entfernten
Kunnerwitz. Nach dreitägigem Aufenthalt im dortigen Stadtgut setzte sich
der Marsch über Pfaffendorf, Friedersdorf und die Schenkhäuser (bei
Gersdorf) nach Obersohland fort. Dort verbrachten die Häftlinge eine
Nacht auf dem Göbelschen Gut, bevor sie über die zu Kemnitz gehörenden
Lehdehäuser in Richtung Buschschenke (Herwigsdorf) weiter zogen. Bis
dorthin läßt sich die Route durch Zeugenaussagen und Leichenfunde
eindeutig nachvollziehen. Im Wald hinter der Buschschenke liefen die
Gefangenen zunächst Richtung Strahwalde und bogen dann links nach
Berthelsdorf ab. In Berthelsdorf berichten Augenzeugen, dass ein langer
Zug aus dem Wald kommend durch die Kränke (Niederdorf) kam[^31] und in
Richtung Rennersdorf ging.

Dennoch besteht diesbezüglich eine Ungewissheit, da mehrfach auch
Häftlinge in Oberberthelsdorf gesehen wurden. Dabei handelte es sich um
eine kleinere Gruppe von ca. 30 Häftlingen, die über den Oberhof
(Oberdorf Berthelsdorf) kam[^32]. Anwohner erkannten unter den
Wachleuten die gebürtige Berthelsdorferin Martha Jacob, die damals in
Görlitz wohnte. Dieselbe wurde in Görlitz zwangsverpflichtet, Gefangene
aus dem Polizeigefängnis zur Arbeit zu bringen und begleitete
gezwungenermaßen auch den Evakuierungsmarsch der in dem Gefängnis am
Postplatz (damals Hindenburgplatz 8) inhaftierten Menschen bis zum
Herrnhuter Bahnhof[^33]. Der Weg von Berthelsdorf nach Rennersdorf führt
jedoch in entgegengesetzte Richtung, weshalb Grund zu der Annahme
besteht, dass es sich dabei um einen anderen Gefangenentransport
gehandelt hat. Es ist nicht auszuschließen, dass es sich dabei um
KZ-Gefangene handelte, die in Rennersdorf verblieben, doch
wahrscheinlich war jener im Berthelsdorfer Oberdorf gesehene Todesmarsch
einer von vielen, dessen Ursprung und Ziel sich heute nicht mehr
bestimmen lässt. Gleiches gilt auch für den vom Altbernsdorfer
Ortschronist Siegfried Hüttig am 14.02.1945 in Altbernsdorf gesehenen
Marsch[^34], der entgegen vielfachen Behauptungen nicht nach Rennersdorf
führte.

#### Zeitzeugenaussagen

Zeitzeugenaussagen stellen subjektive Aussagen dar, die nicht unbedingt
von anderen Zeugen geteilt werden. In Bezug auf den Todesmarsch zwischen
Görlitz und Rennersdorf zeigt sich dies in zum Teil widersprüchlichen
und lückenhaften Berichten. Dennoch bilden die folgenden mündlichen oder
schriftlichen Überlieferungen aus erster Hand den wertvollsten Fundus
zur Rekonstruktion der Geschenisse. Der Autor möchte sich nicht anmaßen,
die Gräueltaten während des Marsches mit eigenen Worten zu beschreiben,
zumal sich selbst einige der befragten und unmittelbar betroffenen
Personen selbst nicht im Stande sahen, das Erlebte wiederzugeben.  
Samuel Mandelbaum:

::: leftbar
Die Leichen blieben auf der Straße liegen, die SS war aufgrund der
Feindannäherung sehr nervös. Für Übernachtung und Verpflegung war keine
Vorsorge getroffen worden.[^35]
:::

###### Kunnerwitz

  Wachmänner wurden damit beauftragt in Kunnerwitz ein Quartier
vorzubereiten[^36].

Der Wachmann Erich Kotter gestand nach dem Krieg ein:

::: leftbar
Beim Eintreffen am Ort ihrer Unterkunft wurden sie durch die Kapos wie
das Vieh in die Ställe und Scheunen hinein getrieben und in der gleichen
Art auch während ihres Aufenthaltes behandelt.[^37]
:::

Schlomo Graber:

::: leftbar
Nach einem Marsch von sechs Kilometern -- für uns eine schier endlose
Entfernung -- gelangten wir zu einem Bauernhof in Kunnerwitz. Wir wurden
im Pferdestall untergebracht. Auf dem Gelände fanden wir Zuckerrüben in
der gefrorenen Erde. Wir fertigten provisorische Grabstöcke, mit deren
Hilfe wir die Rüben ausgruben. Das war die einzige Nahrung, die uns nach
zwei Tagen über die Lippen kam. Die Rüben verursachten Sodbrennen im
Hals. Das aus dem Lager mitgebrachte Brot hatten sich die Blockältesten
und die Kapos genehmigt.[^38]
:::

Janusch Oborowicz berichtet ferner, dass ein entflohener polnischer
Häftling am Fuße der Görlitzer Landeskrone durch Zunker am Tage des
Weitermarsches erschossen wurde[^39].

Janusch Oborowicz:

::: leftbar
Vor dem Abmarsch aus Kunnerwitz erwies sich eine weitere Anzahl an
Häftlingen vor Erschöpfung und wegen Krankheit gehunfähig. Wie mir
später von denjenigen Häftlingen, die dem Aufräumkommando angehört
hatten, erzählt wurde, sind diese gehunfähigen Häftlinge auf dem Gut
Kunnerwitz erschossen und in der ehemaligen Latrinengrube verscharrt
worden.[^40]
:::

Nach dem Krieg fand man 13 Leichen in einer von Kompost überdeckten
Latrine. Vier weitere Tote wurden an der Gutsmauer geborgen (siehe S. ).
Der ehemalige Gefangene Israel Braun äußerte dazu:

::: leftbar
Jeden Morgen nach einer Rast musste ein Aufräumkommando, vielleicht 20
Mann, zurückbleiben und unter Leitung eines oder mehrerer SS-Männer das
Rastgelände sauber machen. Stets gab es kranke oder gestorbene
Häftlinge, die nicht weiter konnten. Einmal bat ein kranker Häftling,
als ich zu solch einem Kommando eingeteilt war, ich sollte die Wachen
veranlassen, ihn zu erschießen. Er könne nicht mehr. Er sprach nur noch
mit leiser Stimme und machte den Eindruck eines Sterbenden. Der Name von
ihm war Ehrenberg. Der SS-Mann, ich denke, es war ein Ukrainer,
antwortete mir: Dieses Schwein ist die Kugel nicht wert. Wir mussten ihn
begraben, und ich denke, er hat noch gelebt.[^41]
:::

###### Sohland am Rotstein

  Etwas abseits der eigentlichen Marschstrecke, in Obersohland, machte
die Kolonne ein zweites mal Station. Auf dem Gut der Familie Göbel
quartierte sich die SS im Wohnhaus des Bauern ein, die Häftlinge wurden
in die Stallungen (siehe Bild  ) gesperrt. Bauer Göbel war damit nicht
gerade einverstanden, doch konnte er sich auch nicht dagegen wehren. Er
wollte nichts mit der Sache zu tun haben und bestand deshalb unbedingt
darauf, dass sein Hof nachher wieder in einem ordentlichen und sauberen
Zustand gebracht wurde. Ausdrücklich verbot er der SS, Leichen auf
seinen Wiesen und Feldern zu verscharren. Aufgrund dieser
Auseinandersetzung holte die Gestapo Herrn Göbel zu Hause ab, um ihn
einem Verhör zu unterziehen.

Janusch Oborowicz:

::: leftbar
Nach Kunnerwitz wurde der zweite Aufenthalt in Sohland am Rotstein
genommen, wo uns an Verpflegung drei Pellkartoffeln verabreicht wurden.
Nach der Ausgabe eines Löffels Gemüsesalat am Tage unseres Abmarsches
erhielten wir bis zu unserem Eintreffen in Rennersdorf keine weitere
Verpflegung.[^42]
:::

Israel Braun:

::: leftbar
Auf dem Marsch gab es kaum Lebensmittel. Einmal wurde aus einem Fass
löffelweise eine Art Salat an die Häftlinge verteilt. Das Fass musste
man wohl gefunden haben. Nach dem Genuss dieses Zeugs erkrankten viele
Häftlinge an Magenschmerzen und starben.[^43]
:::

Schlomo Graber:

::: leftbar
Wir marschierten weiter über die Ortschaften Friedersdorf nach Sohland.
Auch in diesem Dorf wurden wir im Pferdestall eines Bauernhofes
untergebracht. Der Ort bot ein wenig Schutz vor der schlimmen Kälte. Wir
lagen auf dem Stroh, auf dem Heuboden über uns lagerten die Frauen. Auch
hier ernährten wir uns von Zuckerrüben, die wir mit Glasscherben aus der
Erde gruben, und von Suppe, die wir aus Wildkräutern kochten. \[\...\]
Etwa 15 Häftlinge blieben zurück, um den Hof zu säubern. Sie stießen ein
paar Stunden später wieder zu uns. Wir mussten zum Appell antreten.[^44]
:::

Jakob[]{#rosenbaum label="rosenbaum"} Rosenbaum:

::: leftbar
Vor dem Abmarsch in Obersohland fragte man beim Appell, wer von den
Häftlingen nicht mehr gehen konnte. Daraufhin traten neun Leute heraus.
Vor dem Abmarsch hatte man ein Kommando von 15 Männern gewählt, die den
Platz reinigen sollten, wo die Häftlinge sich aufgehalten haben.
\[\...\] Ich hatte damit gerechnet, dass, wenn wir die Arbeit beendigen
werden, wird der Bauer, der Eigentümer der Scheune, uns etwas geben. Als
wir die Arbeit beendet hatten, waren schon Fuhrwerke vorbereitet und die
ukrainischen Posten haben befohlen, die neun Gehunfähigen auf das
Fuhrwerk zu setzen. Wir haben sie aufgesetzt und außerdem zwei Tote, die
vor dem Abmarsch gestorben waren. Ein Ukrainer hat dem Fuhrmann
befohlen, abzufahren. Auf das zweite Fuhrwerk hat er befohlen, Schaufeln
und Kreuzhacken zu legen. Wir haben sofort verstanden, was das bedeutet.
Wir sind dem Fuhrwerk nachgegangen. Es war mir so finster vor Augen,
dass ich kaum wusste wo ich hingehe. Auf dem ersten Fuhrwerk waren
Menschen aus Łódź: mein Cousin Silberberg, an den Namen des zweiten
erinnere ich mich nicht, mir scheint Rosenberg. Sein Schwager, Friede
hieß er, war auch im Lager. Nach einer halben Stunde sind wir zu einem
Wald gekommen. Das erste Fuhrwerk mit den Menschen war schon da. Die
Ukrainer befahlen, ein Grab zu graben. Die neun Menschen, als sie das
gesehen haben, sind sie in Gewein ausgebrochen. Jeder hat gebeten, dass
er schon wird mit marschieren. Man soll ihm nur das Leben lassen. Mein
Cousin kam zu mir mit Tränen in den Augen. Friedes Schwager saß auf der
Erde und bewegte die Lippen, die Tränen flossen ihm aus den Augen.[^45]
:::

Janusch Oborowicz:

::: leftbar
Erschöpfte und kranke Häftlinge, die von Sohland aus den Marsch nicht
fortsetzen konnten, jedoch andererseits mit eigenen Augen gesehen
hatten, was ihren Leidensgenossen passierte, hatten sich vor dem
Abmarsch in der Scheune versteckt. Der Bauer Göbel, bei dem wir
untergebracht waren, hatte dies jedoch beobachtet und machte die
Wachmannschaft darauf aufmerksam, worauf eine Durchsuchung der Scheune
erfolgte. Die hierbei vorgefundenen Häftlinge wurden am nächsten
Waldrand von der SS-Wachmannschaft erschossen.[^46]
:::

Janek Schilid berichtet übereinstimmend:

::: leftbar
Mit einem vom Bauer Göbel zur Verfügung gestellten Fuhrwerk wurden die
Häftlinge an den nächsten Waldrand gefahren, dort vom Wagen herunter
geholt und von Angehörigen des Wachpersonals erschossen.[^47]
:::

###### Lehdehäuser

Ein Mann aus den Lehdehäusern, der nicht namentlich genannt werden
möchte, sah die Häftlingskolonne am elterlichen Haus vorbeiziehen:

::: leftbar
Zusammen mit meinem kleineren Bruder beobachteten wir vorbeiziehende
Häftlinge. Sie trugen längs gestreifte Kleider und eine kleine Mütze.
Viele liefen barfuß, die anderen hatten sich Lumpen um die Füße
gebunden. Durchweg allen konnte man ihre widrige Versorgungslage
ansehen, ihre Gesichter waren eingefallen und zeugten von
Unterernährung. Inmitten der Kolonne wurden mehrere großrädrige
Bauernwagen, die lediglich mit Brettern belegt waren, gezogen. Ein jeder
dieser zwei mal vier Meter großen Wagen wurde durch ca. 20 Häftlinge an
zwei Seilen gezogen und von allen Seiten geschoben. Die Wagen waren für
die Leichen sowie Grabwerkzeuge bestimmt. Der Zug wurde im Abstand von
30 Metern von SS-Wachleuten begleitet. Einige Häuser zuvor hatte Frau
Talke einen Viertelkorb Äpfel auf die Straße geschüttet, damit sie sich
die Gefangenen greifen konnten. Vor dem Haus meiner Eltern stand ein
Brunnen, an dem einige Häftlinge den Schwängel betätigten, um Wasser
hochzupumpen. Die SS-Wachleute ließen dies nicht zu und schlugen mit
ihren Gewehrkolben auf die Dürstenden ein. Ein Häftling brach, nachdem
er am Haus vorbei gelaufen war, auf der Straße zusammen. Sogleich stieß
ihm ein Wachmann sein Knie in den Rücken, so dass er ganz zu Boden sank
und durch einen Genickschuss getötet wurde. Ihn haben sie auf einen der
Wagen geladen. Ehe alle Häftlingen an den Lehdehäusern vorbeigezogen
waren, verging einige Zeit, doch viel länger dauerte es, bis das
Gewehrfeuer in der Ferne verstummte.[^48]
:::

Im Prozess gegen Zunker und Czech gab ein Zeuge zu Protokoll:

::: leftbar
Josef Bursztyn war während Evakuierung so schwach geworden, dass er
nicht mehr weiter gehen konnte und sich auf den Boden setzte. Zunker
ging auf ihn drauf zu und forderte ihn auf, aufzustehen, worauf er
Zunker bat, ihn doch zu erschießen, damit seine Qualen ein Ende haben.
Zunker befahl zwei anderen Häftlingen, ihm aufzuhelfen und erschoss ihn
dann.[^49]
:::

###### Buschschenke

  Gerda Bötig erinnert sich heute mit Schrecken an den Todesmarsch,
damals besaßen ihre Eltern die zwischen Herwigsdorf und Kemnitz gelegene
Gastwirtschaft in der gleichnamigen Buschschenke:

::: leftbar
Beim Eintreffen der Häftlingskolonne wollten die Gastleute den völlig
ausgehungerten Gefangenen Wurstbrühe geben. Die Wachmannschaften
verboten dies jedoch, und so gelang es ihnen nur, eine Wanne mit Wasser
in den Hof zu stellen. Auf demselben Wege wie die Häftlingskolonne kam
ich einige Zeit später aus Richtung Kemnitz zur Buschschenke, wo die
Häftlinge bereits beim Appell standen. Etwa 100 Meter vor der
Buschschenke sah ich einen Häftling auf der Straße liegen, der vor
Erschöpfung nicht mehr weiter konnte. Ich erzählte dies den SS Bewachern
in der Hoffnung, dass diese dem Häftling helfen und ihn nachholen. Diese
taten nicht dergleichen und entgegneten mir stattdessen: Wir machen ihn
fertig. Kurz darauf wurde der Häftling erschossen. Die Opfer zogen sie
in einem Karren hinterher. Der Todesmarsch setzte sich in Richtung
Strahwalde fort.[^50]
:::

Jakob Rosenbaum:

::: leftbar
Wir gehen weiter, wir treten auf Tote. Wir bemerken, wie im Wald ein
paar Menschen sitzen. Ich schreie steht auf! Ich habe gar nicht bemerkt,
dass zwei Soldaten sie bewachen und Menschen schon ein Grab graben. Als
wir uns etwas entfernt haben, hörten wir eine Schießerei. Wir gehen den
Weg weiter, der nach Reichenbach führt. Nach einem ganzen Tag
Marschieren, sind wir in Regersdorf \[gemeint ist Rennersdorf\] stehen
geblieben.[^51]
:::

Am selben Weg endeckten Waldarbeiter nach dem Krieg eine mit Reisig
verdeckte Grube. Unter den Zweigen lagen sieben Leichen (siehe
Ermittlungen gegen die NS-Verbrechen S. ).

::: leftbar
Auf dem Wege haben wir viele Tote gesehen. Ich habe unter anderem den
Juden Rosensaft aus Łódź gesehen. Das Blut ist ihm aus dem Mund gerinnt.
Ich habe mich ihm genähert und versucht ihn aufzustellen. Er hat mit der
Hand eine Bewegung gemacht und gemeint: Rosenbojm, lass mich sterben.
Ich wollte ihm erzählen, was im Wald passierte, in diesem Moment ist der
Rapportführer gekommen und hat ihn erschossen.[^52]
:::

###### Rennersdorf

  Am Nachmittag des 23. Februar 1945 erreichten die Häftlinge die
Ortschaft Rennersdorf.

Janusch Oborowicz:

::: leftbar
Nach Sohland galt als nächstes Ziel Rennersdorf, wo wir in den späten
Abendstunden eintrafen. Noch wenige 100 Meter vor dem Ziel fielen einige
Häftlinge vor Erschöpfung um, die dann sofort an der Straße von den
Angehörigen des Wachpersonals erschossen wurden.[^53]
:::

Frau Liesbeth Sägner beobachtete im Alter von 11 Jahren die
vorbeiziehenden Häftlinge:

::: leftbar
Sie waren gehüllt in Sträflingskleidung und Lumpen. Sie liefen in
Zweierreihen und bildeten eine lange Kette mit vielen Unterbrechungen.
Wachleute begleiteten den Zug mit ihren großen Hunden.[^54]
:::

Die Rennersdorferin Hildegard Fleischmann:

::: leftbar
Ich befand mich seinerzeit vor der Seliger-Schmiede und beobachtete, wie
einer der Häftlinge vor Erschöpfung zusammenbrach. Hierauf trat ein
Angehöriger des SS-Wachpersonals an den Zusammengebrochenen heran und
versuchte ihn mit den Füßen in den neben der Straße fließenden Bach zu
stoßen. Der Schmied Seliger beobachtete gleichfalls diesen Vorfall, trat
an den SS-Mann heran und sagte: Na, na, soweit ist es nicht, dass er in
den Bach gekippt wird. Er bot einen Handwagen zum Abtransport des
Häftlings an, womit dann der zusammengebrochene Häftling mit einem
zweiten Juden, der bereits einige Zeit vorher zusammengebrochen war,
weggefahren wurde.[^55]
:::

Die damalige Rennersdorferin Christa Schubert entsinnt sich der
Schrecken des 23. Februar 1945, dem Tag ihres 12. Geburtstags:

::: leftbar
Unsere Großmutter kam aus dem Oberdorf und hat sie \[die Häftlinge\]
gesehen. Wenn sie von Berthelsdorf kommen, bei der ersten Wirtschaft.
Dort hat unsere Großmutter gewohnt. Und wir haben unten bei Schulzes
Brücke \[Abzweig Herrnhut\] gewohnt und sie wollte zum Kaffee trinken zu
meinem 12. Geburtstag runter kommen, da hat sie das schon von dort oben
gesehen. Sie konnte sich noch erinnern, dass bei der Seliger-Schmiede,
wo jetzt Bachmanns wohnen, einige nicht mehr richtig fort konnten. Dort
musste der Schmied einen Leiterwagen geben. \[\...\] Die Großmutter sah
zu, dass sie weg kam. Der Zug ist dann hinterher gekommen. Das ist nach
dem Mittag gewesen, denn da war ja überall Landwirtschaft, und das Vieh
war zu füttern, deshalb musste in der dritten Stunde Kaffee getrunken
werden. Wir haben in der Küche auf der Bank gestanden und zum Fenster
raus geguckt. Ich kann mich noch genau entsinnen, weil da ein Zweiräder
\[Wagen\] war und die Köpfe auf der Straße hingen und schleiften. Das
war furchtbar. Die hatten solche großen Wagen und dort lagen Menschen
drauf. Den haben die Gefangenen vorn gezogen und darauf lagen die, die
nicht mehr fort konnten. Die waren furchtbar angezogen, die Sachen
hingen so runter und es war ja Winter. Mein Vater, meine Mutter auch,
jeder war entsetzt; auf so etwas war ja niemand gefasst.[^56]
:::

### Das Ausweichlager Rennersdorf

Die Überlebenden des Todesmarsches kamen am 23. Februar in das unweit
von Herrnhut gelegene Rennersdorf. Die SS quartierte die Häftling in
einem alten herrschaftlichen Gutshof am Fuße des Berges Eichler ein. Das
sogenannte Gut Oberrennersdorf (Bild  ) befand sich seit 1765 im Besitz
der Brüder-Unität Herrnhut. Unter dem Vorwand der Knappheit von
Siedlungsland und der strategischen Lage in Grenznähe zur
Tschechoslowakischen Republik erwirkte die Wehrmacht nach zähen
Verhandlungen den Verkauf des Gutes Oberrennersdorf als Bestandteil des
Remonteamtes (zusammen mit dem Berthelsdorfer und Großhennersdorfer Gut)
am 3. März des Jahres 1937[^57]. Dem damaligen Pächter Rosenberg wurde
im Juli des selben Jahres gekündigt[^58]. Das tote wie auch das
benötigte lebende Inventar ging in den Besitz der Wehrmacht über. Die
landwirtschaftlichen und forstwirtschaftlichen Unternehmungen setzte man
fort, wobei die Pferdeaufzucht eine wesentliche Rolle spielte. Laut dem
Rennerdorfer Ortschronisten war der damalige Wirtschaftsvogt und
Betriebsführer ein gewisser Reinhold Lehmann[^59]. Außer ihm wohnten
noch eine Reihe anderer Personen auf dem Gut: der Tierarzt Zwerschke mit
seinem Sohn, ein Schäfer namens Schlaffke sowie die Familien Bittrich,
Feder, Engel und Weber.

###### Welcher Art war das Lager in Rennersdorf?

Genau wie das hier bereits behandelte Görlitzer Lager im Biesnitzer
Grund, ist das Lager in Rennersdorf definitionsgemäß kein
Konzentrationslager[^60]. Ebenso wenig kann man es als Arbeitskommando
bezeichnen, da nur geringfügige Arbeitseinsätze erfolgten. Vielfach
wurde das Lager in der Literatur als KZ-Außenlager bezeichnet, wobei es
jedoch, entgegen Isabell Sprengers Annahme, kein reines Männerlager
war[^61]. Angesichts der Tatsache, dass die Gefangenen nur für knapp
zwei Wochen in Rennersdorf verweilten und anschließend wieder an ihren
Ausgangspunkt nach Görlitz zurückkehrten, scheint es im wörtlichen Sinne
ein Ausweichlager gewesen zu sein. Im Archiv des KZ Groß-Rosen sowie in
den Verwaltungsbüchern der Gemeinde Rennersdorf existiert kein einziges
Dokument, was den Zusammenhang mit dem Hauptlager erkennen lässt. Belegt
ist hingegen der enge Kontakt zwischen den Kommandoführern der
Evakuierungsmärsche und dem Meldekopf des Stammlagers, welcher sich ab
dem 17. Februar 1945 im Außenlager Reichenau im Sudetengau (Rychnov u
Jablonce nad Nisou, Tschechien) befand. Im Folgenden wird das Lager in
Rennersdorf dennoch als KZ-Außenlager bezeichnet, um damit einerseits
den Charakter eines KZ-Lagers auszudrücken und andererseits eine von der
Existenzdauer unabhängige Benennung beizubehalten[^62].

#### Die Haftbedingungen im Lager Rennersdorf

Das Außenlager Rennersdorf hatte einen stark provisorischen Charakter
und ist kurzfristig eingerichtet worden. Das Gelände war weder durch
einen Zaun gesichert, noch von der zivilen Außenwelt isoliert. Die
vorherige Nutzung als Remontegestüt[^63] war für die Gefangenen mehr als
offensichtlich. Die Unterbringung erfolgte im 70 m nördlich gelegenen
Pferdestall (Bild  ) zwischen einem kleinen Wäldchen und dem Weg nach
Neundorf. Der Pferdestall teilt sich in vier Abschnitte. Im hinteren,
vierten Abschnitt, welcher dem Gutshof am nächsten liegt, waren die
Frauen untergebracht. In den anderen drei Abschnitten waren die Männer
einquartiert.

Die Situation der Häftlinge war geprägt durch die gesundheitlichen
Folgen des langen Marsches und die Unzulänglichkeiten des provisorischen
Lagers. Beides zusammen zehrte an den physischen und mentalen Kräften
der Menschen im Lager. Aufgrund der Haftbedingungen kann man, im
Vergleich zum Außenlager Görlitz, nicht von einem geregelten, für fast
alle geltenden Tagesablauf sprechen.

Der ehemalige Gefangene Abram Rajchbart drückt mit wenigen Sätzen aus,
unter welchen Bedingungen die KZ-Gefangenen in Rennersdorf hausten:

::: leftbar
Hier herrscht Chaos. Wir schlafen auf dem Mist, der mit Stroh bedeckt
wird. Die Lebens- und Arbeitsbedingungen sind unmenschlich und
entsetzlich. Wir haben keine Möglichkeiten, uns zu waschen und die
Wäsche zu wechseln. Das Ungeziefer verbreitet sich, auch die Krankheiten
breiten sich aus.[^64]
:::

Es gab weder ein Krankenrevier noch einen Waschraum. Im Gegensatz zum
Görlitzer Lager, existierte keine Wäscherei, Schusterei oder
Schneiderei. Die Einrichtung des Lagers reduzierte sich auf eine Küche
und eine Latrine aus Birkenholz[^65]. Der Pferdestall diente als
Menschenstall, ohne Betten, bestenfalls mit etwas Stroh ausgelegt[^66].
Janusch Oborowicz führt dazu weiter aus:

::: leftbar
Infolge der in dem Pferdestall bestehenden ungünstigen hygienischen
Verhältnisse, hervorgerufen durch die schlechte Luft und die
Ausdünstungen des Mistes, haben sich auch die Läuse bei den Häftlingen
auffallend vermehrt.[^67]
:::

#### Die Versorgungslage der Häftlinge

Janusch Oborowicz:

::: leftbar
An Verpflegung erhielten wir seinerzeit für acht Häftlinge jeweils 1
Brot und 3/4 Liter halb rohe Gemüsesuppe. Neben den Erschießungen waren
infolge der schlechten Ernährung auch weitere Sterbefälle zu
verzeichnen.[^68]
:::

Die Unterernährung war den Gefangenen anzusehen und äußerte sich in der
verzweifelten Suche nach Nahrung. Einige der Notleidenden brachten es
fertig, so Ilse Gießler, eine Scheibe Brot von der Straße aufzuheben
ohne sich dabei auffällig bücken zu müssen[^69].

Die ehemalige Rennersdorferin Ilse Gießler erinnert sich:

::: leftbar
Fast täglich kamen Häftlinge an unserem Haus vorbei, um beim Bäcker
Alter mit einem hierfür gebauten Spezialfahrzeug Brot als Verpflegung
für die Häftlinge abzuholen. Eines Tages \[\...\] war ich Augenzeuge,
wie einer der Häftlinge während der Rückfahrt vom Bäcker zum Gute,
unmittelbar vor unserem Hause, von einem Posten der SS-Mannschaft mit
einem armstarken Knüppel schwer misshandelt wurde, indem er auf ihn
einschlug, wobei ihn der noch anwesende Kapo zu halten hatte. Da uns
einerseits verboten war, den Häftlingen irgendwelche Nahrungsmittel zu
verabreichen oder gar mit ihnen zu sprechen, wir andererseits tiefstes
Mitleid mit ihnen empfanden, hat mein Vater eines Tages Äpfel so in den
Straßengraben geworfen, dass die Häftlinge sie auf ihrem Rückweg vom
Bäcker sehen mussten, wodurch ihnen diese Zuwendung auch tatsächlich
gewährt werden konnte. Das Fuhrwerk wurde tatsächlich von ca. 1012 Juden
gezogen bzw. geschoben. Alle Häftlinge machten einen verwahrlosten und
verhungerten Eindruck [^70]
:::

Während seit Ankunft der Gefangenen ihre Unterernährung für die
Dorfbevölkerung nicht übersehbar war, machte die SS keinen Hehl daraus,
im Überfluss zu leben. In jener Zeit hatten selbst die Leute im Dorf
nicht übermäßig viel zu essen und empörten sich daher nicht ohne Grund
über die Verfütterung von großen Wurstringen an die Hunde der SS[^71].
Die überschwänglichen SS-Gelage in der Schmidt-Mühle wurden mit
Entsetzen durch die Bevölkerung aufgenommen.

Schlomo Graber erinnert sich der Situation in seinen Memoiren:

::: leftbar
Die Deutschen schlachteten sich Schafe, warnten uns jedoch, wer sich an
den Schafen vergreife, sei des Todes. Hier teilte man uns auch je eine
Scheibe Brot zu, die jeder in seinem Brotbeutel wie einen Schatz hütete,
um sie krümelweise zu essen. Als ich eines morgens aufwachte -- ich lag
zwischen Vater und einem anderen Juden -- spürte ich, dass dieser sich
nicht mehr regte, und suchte als erstes sein Brot. Als ich es gefunden
hatte, freute ich mich an dem Fund.

An jenem Morgen erschien der älteste Soldat, der die Küche der Deutschen
unter sich hatte, und rief mich: Farzer komm schnell. Er forderte mich
auf, den geschlachteten Schafen das Fell abzuziehen. Von ihm erfuhr ich,
dass kranke Schafe für die Häftlinge gekocht werden sollten. Ich fand
eine Methode die Schafe krank zu machen. Ich ging in den Pferch, trat
einem Schaf in den Bauch, dass es umkippte, und erklärte: Dies ist
krank. Auf diese Weise bekamen wir nach langem Hungern etwas in den
Magen.[^72]
:::

Die Landarbeiterin Auguste Hergarten:

::: leftbar
Die Häftlinge bekamen ein Essen, dass man nicht einmal als brauchbares
Schweinefutter bezeichnen kann. Es war furchtbar mit anzusehen, wie die
hilflosen armen Menschen immer wieder schwersten Mißhandlungen
ausgesetzt waren. Sobald sich eine Gelegenheit bot, steckten wir ihnen
zusätzlich etwas Essen zu, obgleich wir selbst nicht viel hatten.[^73]
:::

Der Rennersdorfer Helmut Sperling erinnert sich, wie sein Vater bei der
Lagerleitung um Hilfe beim Fällen einer Eiche bat. Seine Mutter
erwartete die Helfer mit einem Teller Schnitten, welcher jedoch von den
Bewachern auf dem Erdboden zertrampelt wurde.

#### Zwangsarbeit auf dem Gut Oberrennersdorf

Der Bericht des Zeitzeugen Helmut Sperrling legt die Vermutung nahe, die
Häftlinge seien auch in Rennersdorf von der Zwangsarbeit verschont
geblieben. Dies wird jedoch in nur in sehr wenigen Überlieferungen
ehemaliger Gefangener bezeugt. Ein Großteil der Menschen war nach dem
anstrengenden Marsch nach Rennersdorf physisch und psychisch kaum noch
in der Lage zu arbeiten. Angesichts dessen wird nur eine Minderheit, vor
allem aber Frauen, zur Arbeit herangezogen worden sein[^74]. Die Art der
Arbeit richtete sich nach den örtlichen Erfordernissen der im Hof
betriebenen Landwirtschaft. Damals arbeitete neben vielen anderen auch
Liesbeth Sägners Mutter im Gut Oberrennersdorf als Landarbeiterin. Sie
wusste zu berichten, dass die Häftlinge mit ihr und anderen Rüben
sortieren mussten. Obwohl sie sich in einem erbärmlichen Zustand
befanden, war es ihnen verboten von den Möhren zu essen, weshalb Frau
Sägners Mutter ihnen aus Mitleid mehrmals einen Kanten Brot bei der
Arbeit zuschob[^75]. Abram Rajchbart beschreibt die Arbeitsbedingungen
insgesamt als unmenschlich und entsetzlich[^76]. Die Annahme der
Historiker Gräfe / Töpfer und Zgłobicki, wonach in Rennersdorf
Schanzarbeiten verrichtet wurden, konnte in den zahlreichen
Überlebendenberichten nur gegenteilige Bestätigung finden, zumal es in
ganz Rennersdorf keine Überreste solcherlei Arbeit gibt. Aller
Wahrscheinlichkeit nach handelte es sich hierbei um eine Verwechslung
mit den bei der Rückkehr nach Görlitz befohlenen Schanzarbeiten.[^77].

#### Kontakt zur Dorfbevölkerung

Rennersdorf hatte während des Krieges nur wenige hundert Einwohner, die
fast alle miteinander bekannt waren. Die Neuigkeit von der Ankunft der
erbärmlich ausschauenden Häftlinge am 23. Februar 1945 verbreitete sich
also rasch, zumal die Kolonne zuvor auf gut zwei Kilometern die
Hauptstraße des Ortes passierte.

Jeder wusste es[^78]. Die Neuigkeit von der Ankunft der erbärmlich
ausschauenden Häftlinge verbreitete sich rasch. Den Pferdestall, in dem
die Häftlinge untergebracht waren, konnte man sehr gut von der am
Eichler vorbeiführenden Straße zwischen Herrnhut und Bernstadt /
Großhennersdorf einsehen. Ilse Gießler berichtete, wie sie während eines
Waldspazierganges auf dem Berg Eichler die abgemagerten Gefangenen
beobachten konnte. Insbesondere jene Rennersdorfer, die auf dem Gutshof
wohnten oder arbeiteten, konnten sich der Präsenz der Gefangenen
keinesfalls verschließen. Offensichtlich hielt die SS Appelle im Hof des
Gutes ab, bei denen es immer wieder zu Folterungen kam[^79]. Die SS -
seit dem Todesmarsch durch eine ukrainische Einheit verstärkt -
provozierte durch ihren Umgang mit den Gefangenen bei den Hofbewohnern
eine Angst, selbst in Mitleidenschaft gezogen zu werden. Die
Rennersdorfer sollten sehen, was ihnen blühte, wenn sie den Gefangenen
Mitleid entgegen brachten.

Bereits bei der Ankunft, als die Gefangenen das Hoftor passierten,
deutete sich alles an. Es kam zu einer ersten Erschießung vor den Augen
einiger Frauen und Kinder. Janek Schilid sagte 1948 dazu:

::: leftbar
Da vor dem Erreichen des Dorfes ein ziemlich steiler Berg zu überwinden
war, da einer der Häftlinge zu schwach war, den sich hieraus ergebenen
körperlichen Anforderungen gerecht zu werden und zusammen sank, wurde er
an der Straße durch angehörige des Wachpersonals erschossen. [^80]
:::

Die Unterernährung war den Gefangenen anzusehen und äußerte sich in der
verzweifelten Suche nach Nahrung. Dabei ersuchten sie auch Rennersdorfer
um Hilfe. Jedoch stets unter Gefahr, von der SS erwischt zu werden, wie
jene beim Bauer Schönfelder[^81].

Außerhalb des Gutshofes und bei der Abholung des Brotes beim Bäcker
kamen die Häftlinge jedoch kaum in Kontakt mit der Dorfbevölkerung.

Bemerkenswert ist die Begegnungen im Hause der Familie Löwe, welche
unweit vom SS-Quartier in der Schmidt-Mühle wohnte: Joachim Löwes Mutter
war an Fieber erkrankt und man befürchtete, eine Epidemie könntex sich
ausbreiten. Der Arzt im Nachbarort Herrnhut war verhindert, weshalb sich
der NSDAP-Ortsgruppenleiter nach einem Arzt unter den jüdischen
Häftlingen erkundigte und fündig wurde. Die Behandlung durch einen
jüdischen Arzt galt in jener Zeit als Rassenschande". Seit dem Erlass
der Nürnberger Gesetze (15.09.1933) war es jüdischen Ärzten untersagt,
Arier" zu behandeln. Trotzdem gestattete die Lagerleitung dem Arzt Frau
Löwe zu behandeln. Mit einer Medikamententasche erschien er im Haus der
Löwes. Einer der beiden ihn begleitenden Bewacher wollte zunächst der
Behandlung beiwohnen, erst als Frau Löwe mit einem Fingerzeig auf das
Bild ihres im Krieg gefallenen Gatten hindeutete, verließ der SS-Mann
die Stube. Der Arzt war mit Medikamenten sowie notwendigen Utensilien
ausgestattet und somit in der Lage der Erkrankten bei diesem und zwei
weiteren Hausbesuchen zu helfen. Die Löwes arrangierten sich, indem sie
ihm ein paar Stullen Brot gaben, die er nach anfänglichem Zögern in
seiner Hose versteckte.[^82]

#### Die SS in Rennersdorf

Die Kommandostruktur der SS war in Rennersdorf dieselbe wie zuvor in
Görlitz. Erich Rechenberg als Lagerkommandant verblieb in Görlitz und
kam nur gelegentlich nach Rennersdorf. Lagerführer Zunker, Rapportführer
sowie die älteren SS-Leute und die als grausam beschriebenen
ukrainischen SS-Männer bezogen in Rennersdorf Quartier. Ein Großteil der
Wachmannschaften wohnte auf dem Gut, ein Teil soll auch bei Wunderlichs
und andere bei Wenzels auf dem Gittelberg logiert haben[^83]. Zumindest
der Lagerführer bezog während dieser Zeit mit seinen Hunden und seinen
bediensteten Häftlingen (Stiefelputzer) die Schmidt-Mühle am
Fuchsberg[^84] (Bild  ).

#### SS-Terror in Rennersdorf

Wie bereits erwähnt, begann das Morden schon bei Ankunft der Gefangenen
im Gutshof. Eine weitere Erschießung erfolgte in der darauf folgenden
Nacht, als ein Häftling die Unterkunft zum Austreten verließ[^85].

Isaac Weintraub:

::: leftbar
Es gab keine Krankenbaracke. So wurde angeordnet, dass diese Häftlinge
von der begleitenden Wachmannschaft, die teilweise aus ukrainischer SS
bestand, erschossen wurden. Die Häftlinge wurden mit Karabinern, die aus
einer Entfernung von 50 m auf sie gerichtet wurden, erschossen und in
der Feldtoilette begraben.[^86]
:::

Auguste Hergarten:

::: leftbar
Ich war als Landarbeiterin auf dem Gut Oberrennersdorf beschäftigt und
wiederholt Zeuge, wie die Kapos die Häftlinge wegen den kleinsten
Geringfügigkeiten Schläge verpassten. Mir wurde auch von Häftlingen
erzählt, dass wiederholt Juden durch das SS-Wachpersonal erschossen
worden sind. Sie wurden hinter dem Remontestall vergraben \[\...\] Unter
ihnen befand sich auch ein 18-jähriger Häftling, der erschossen wurde,
weil er sich aus der Rübenmiete eine Runkelrübe beschafft hat, um sie zu
essen.[^87]
:::

Helmut Sperling verbrachte in Kindheitstagen viel Zeit bei einem Freund
auf dem Gutshof und erinnert sich an mehr als vier Exekutionen am Damm
eines Wiesenweges (Bild  ), an dessen Stelle sich heute ein Löschteich
befindet. Nachdem die zum Tode Bestimmten ihr eigenes Grab notdürftig
ausgehoben hatten, wurden sie an den Rand der Grube gegenüber dem
Pferdestall an einem Wiesenweg gesetzt und durch einen Genickschuss
getötet[^88]. Dem Gutsverwalter Lehmann sagt man nach, dass er den
Abraum, der beim Fegen des Hofes zusammen kam, auf die Gräber am
Wiesenweg kippen ließ, um somit die Vorkommnisse auf seinem Hof zu
vertuschen. Die sowjetische Militärkommandantur verhaftete ihn deshalb
nach Kriegsende.

Wenn auch als einziger, erinnert sich Samuel Kessler an eine Erschießung
eines Zivilarbeiters:

::: leftbar
Während des Evakuierungsmarsches war ich Augenzeuge der Erschießung
eines entflohenen polnischen Kriegsgefangenen, der von der örtlichen
Polizei in Rennersdorf dem KL \[Konzentrationslager\] überstellt wurde.
\[...\]

Es erschien dann Gendarmarie, die einen aus einem Kriegsgefangenenlager
geflüchteten Mann, vermutlich ein Pole, dem \[Lagerführer\] Zunker
vorführte. Es war der Zeitpunkt, als wir auf dem Zufahrtsweg zu dem
Gestüt in die Ställe eingeschleust werden sollten. Ich bemerkte, dass
Zunker wieder sehr aufgeregt war. Ich saß auf dem Bock des
Pferdefuhrwerks und befand mich in unmittelbarer Nähe des Geschehens.
Zunker wusste offensichtlich nichts mit dem herangeführten Häftling
anzufangen und wollte ihn auch nicht haben. Er stellte ihn dann einige
Meter entfernt von sich ab, drehte sich um, zog plötzlich die Pistole
und schoß mit 3--4 Schüssen dem Häftling in den Körper. Dieser fiel
sofort um und war tot. Auf dem danebenliegenden Feld ist dann dieser
Gefangene von Mithäftlingen verscharrt worden. Der Gefangene war damals
so um die 30--40 Jahre alt und trug Zivilkleidung.[^89]
:::

### Die Rückkehr nach Görlitz

Nach den Rückschlägen bei den Kämpfen um Lauban verlagerten sich die
militärischen Operationen der Roten Armee ab dem 8. März in Richtung
Berlin. Folglich stabilisierte sich die Frontlage bei Görlitz. Die
Rüstungsbetriebe holten ihre Arbeitslager, die sie evakuiert hatten, zum
größten Teil wieder zurück. Dasselbe trifft auch für das Arbeitslager
Biesnitzer Grund zu., heißt es in einer Aussage des Görlitzer
Kreisleiters Malitz[^90]. Malitz versuchte die Verantwortung für die
gesamte Evakuierung auf die WUMAG abzuwälzen, obwohl die von ihm mit
getragenen Ambitionen Görlitz zur Festung auszubauen, ausschlaggebend
für den Rückmarsch der Häftlinge waren. Auch der Lagerkommandant
Rechenberg und die nach Reichenau (Rychnov u Jablonce nad Nisou,
Tschechien) verlegte Kommandantur des Stammlagers musste informiert
gewesen sein.

Der Abzug der Gefangenen am 8. März 1945 bedeute gleichzeitig die
Auflösung des 13 Tage zuvor entstandenen Außenlagers Rennersdorf.

::: leftbar
Vor dem Abmarsch gab es einen Appell. Solche Appelle waren etwas
Alltägliches. Die Deutschen wollten wissen, wie viele Häftlinge noch
übrig waren. \[\...\] Sie fragten, wer marschunfähig sei. Es meldeten
sich rund 100 Leute, die per Lastwagen ins Lager Görlitz gefahren
wurden. Als wir dort ankamen, fanden wir sie lebend vor.[^91]
:::

Der Großteil der Gefangenen ging zu Fuß und verließ Rennersdorf Richtung
Niederdorf. Obwohl Schlomo Graber von gutem Wetter schreibt, welches das
Gehen erleichterte, herrschten immer noch winterliche Temperaturen.
Janusch Oborowicz dazu:

::: leftbar
Die Straßen waren während unseres Marsches sehr stark vereist und wir
konnten nicht verhindern, dass ein Fahrzeug ins Rutschen kam, als wir
eine steil abfallende Straße passierten. Bei der Gelegenheit hat sich
der Lagerführer dermaßen aufgeregt, dass er mit seiner Pistole anfing zu
schießen und zwei unserer Leute verletzte.[^92]
:::

Janek Schilid fügt hinzu:

::: leftbar
Der von uns bisher benützte Knüppel zum Bremsen auf abschüssigen Straßen
reichte nicht aus, dass Fuhrwerk zu einer angemessenen, gemäßigten
Geschwindigkeit zu halten, so dass es einem Häftling über die Beine und
über den Bauch gefahren ist, was seinen Tod zur Folge hatte.[^93]
:::

Überlebendenberichten zufolge sollen abgesehen von diesem Unfall während
des Rückmarsches keine oder nur vereinzelt Menschen ums Leben gekommen
sein[^94].

::::: fshaded
#### Nutznießer des Todesmarsches {#nutznießer-des-todesmarsches .unnumbered}

Als Frauen, Kinder, Alte und Schwache die Stadt Görlitz auf Befehl vom
NSDAP Kreisleiter verlassen mussten, bot der Lagerführer Winfried Zunker
der Görlitzerin Ursula Taube an, zusammen mit der Häftlingskolonne am
18.02.1945 die von der Roten Armee bedrohte Stadt zu verlassen. Sie war
zu dem Zeitpunkt schwanger und hatte keine Fahrtgenehmigung für die
Eisenbahn bekommen. Neben Frau Taube konnte ihre Verwandtschaft
mütterlicherseits, bestehend aus Mutter, Tante und Großeltern, den Weg
antreten. Ebenso eine Flüchtlingsfrau mit ihrem 1$\frac{1}{2}$jährigen
Kind.

::: leftbar
In den frühen Nachmittagsstunden begaben wir uns in das Lager Biesnitzer
Grund, wo die Häftlinge bereits zum Abmarsch angetreten standen. Hier
wurden uns von Zunker zwei weibliche Häftlinge zum Schieben des
Kinderwagens, den wir mit uns führten, zugeteilt und wir setzten uns an
die Spitze des Zuges mit den Häftlingen in Richtung Kunnerwitz über
Biesnitz in Bewegung. Der Abstand zwischen uns und den Häftlingen
schwankte zwischen 300 und 400 Metern.[^95]
:::

Ihnen war laut eigener Aussage bewusst, dass die Häftlinge aufgrund
ihrer Unterernährung nur so langsam voran kamen. Bei der Ankunft in
Kunnerwitz nahmen sie Quartier in einem Privathaus, während die
Häftlinge in die Scheune des Bauern Fünfstück eingepfercht wurden. Das
Betreten des Hofes war ihnen während der drei Tage und zwei Nächte
untersagt. Beim Abrücken erfuhren sie von dem Aufräumungskommando durch
Zunker, dessen Funktion er ihnen im wörtlichen Sinne erklärte. Einer der
Wachleute erläuterte der Familie einige Zeit später, was in Wirklichkeit
unter aufräumen zu verstehen war, nämlich die Beseitigung von Leichen.
Ursula Taube hatte ein offenbar sehr gutes Verhältnis zu Zunker, weshalb
sie ihn daraufhin zur Rede stellte. Entsetzt über den Verrat konnte er
die Gräuel nicht länger leugnen und gestand die Erschießung kranker,
gehunfähiger Häftlinge ein. Vom Abend desselben Tages berichtet sie:
Während die Häftlinge in der Scheune des Bauern Göbel untergebracht
waren, schliefen ich und meine Mutter in der Mansarde des
Wohnhauses.[^96] In Rennersdorf ergab sich eine ähnliche Situation,
wobei ihnen der Rennersdorfer Bürgermeister eine Aufenthaltsgenehmigung,
und die damit verbundene Zuteilung von Lebensmittelkarten versagte. Da
alle sieben Personen ebenso lang in Rennersdorf verblieben, wie die
Häftlinge, muss davon ausgegangen werden, dass sie sich nur auf Kosten
der KZ-Gefangen ernährt haben konnten. Zumindest Frau Taube fuhr im PKW
mit Zunker und einem nicht namentlich erwähnten Feldwebel nach Görlitz
zurück; nicht jedoch ohne die auf dem Fußmarsch befindliche Kolonne zu
überholen und deren erbärmliche Verfassung zu registrieren:

::: leftbar
Die Fuhrwerke wurden hierbei von den Frauen gezogen, während die Männer
teilweise derartig erschöpft waren, dass sie auf diesen von den Frauen
gezogenen Fuhrwerken saßen und lagen.[^97]
:::

In den darauf folgenden Tagen und Wochen bis kurz vor Kriegsende stand
Frau Taube in engem Kontakt mit dem Lagerführer Zunker[^98].
:::::

### Die letzten Wochen vor der Befreiung

Während der letzten 60 Tage vor der Befreiung starben durchschnittlich
mindestens zwei Menschen pro Tag. Der Grund für diese, im Vergleich zu
den vorherigen Monaten, extrem hohe Sterblichkeit waren die miserablen
Arbeitsbedingungen im Freien. Obwohl kurz nach der Rückkehr der
Häftlinge einige sofort für den erneuten Arbeitseinsatz bei der WUMAG
bestimmt wurden und fast bis Kriegsende in den Fabrikhallen
arbeiteten[^99], schuftete das Gros der Gefangenen bei Schanzarbeiten
sowie beim Bau von Barrikaden. Andere waren auf dem Görlitzer Flugplatz
(siehe Karte S. ) mit der Verladung von Munition beschäftigt[^100]. Die
Art der Arbeit bestimmte abermals die Überlebenschancen. Um jene, die
Panzergräben ausheben mussten, war es besonders schlecht bestellt. Bis
zu den Knien versanken sie mit ihren Holzschuhen im Schnee und
Matsch[^101]. Niederschlag und Kälte taten ihr Übriges. Hinzu kam noch
die lange Wegstrecke bis in die Oststadt. Folglich stieg der
Krankenstand und die Zahl derer, die vor Entkräftung aufgaben und durch
die ukrainischen Hilfskräfte bei der Arbeit erschossen wurden.   Die
ehemalige Gefangene Mila Weisberg erinnert sich, wie sie nach der
Evakuierung zu Schanzarbeiten gezwungen wurde:

::: leftbar
Um 5 Uhr treten wir zum Appell an. Um 6 Uhr gehen wir zu unserer Arbeit.
Wir arbeiten sehr schwer beim Schanzengraben. Wir stehen im Schmutz bis
an die Knöchel. Wir haben nur Holzschuhe, deshalb verfallen viele Leute
in Krankheit. Unsere tägliche Nahrungsration besteht aus einem Liter
Suppe und 20 dag Brot \[200 g\].[^102]
:::

Jechiel Rappaport:

::: leftbar
Ein Häftling namens Frenkel konnte vor Ermüdung nicht schritthalten als
sie vom Ausheben der Schützengräber zurück kamen, woraufhin ihn ein
ukrainischer SS-Mann erschoß. Jenseits der Neiße, nicht weit von der
Arbeitsstelle wurde er an Ort und Stelle begraben. Solche Vorfälle
wiederholten sich noch einige Male.[^103]
:::

  -- ------------------------------
     
     []{#nolabel label="nolabel"}
  -- ------------------------------

#### Kapitulation des KZ-Außenlagers Görlitz

Nach Einstellung der Produktion in der WUMAG in den letzten Kriegstagen
wurden auch kaum noch Arbeitskommandos für den Barrikadenbau entsandt.
Die Unruhe unter den Wachleuten und der andauernde Fliegeralarm deuteten
darüber hinaus an, dass irgend etwas nicht stimmte[^104]. Kurz vor der
Befreiung ergriffen die Wachleute die Flucht.   In einem Interview
beschreibt Anna Hyndráková die Ereignisse wie folgt:

::: leftbar
Wir arbeiteten auf einem Flughafen. Auf einmal haben wir einen Befehl
bekommen, wir sollen zurück marschieren. Wir sind zurückgekommen und
haben gesehen, dass nirgends die Wachen sind. Am 6. Mai war das. Die
Männer waren im Frauenlager und umgekehrt. Zunker hat zum Appell
gepfiffen. Alle sollten aus den Blöcken heraus. Ich hatte meinen Mantel
drinnen und wollte ihn holen, da hat er mir eine Ohrfeige gegeben\...
Ich konnte drei Tage nicht hören, ich dachte, ich habe mein Gehör
verloren. Und er hat geschrien: Ihr glaubt wohl, ich würde euch alle
einzeln herausholen. Und dann beim Appell hat er gesagt: Ihr wisst, wir
haben euch nie geschlagen. Er sagte, die SS wird uns zu den Amerikanern
bringen und wenn wir hier bleiben, kommen die Russen -- die werden uns
vergewaltigen und die Nasen abschneiden und so weiter und so fort. Wir
wollten nicht mit ihnen gehen, aber wir haben auch Angst gehabt dort zu
bleiben. Man hat gesagt die Deutschen brennen die Lager ab, damit die
Spuren vernichtet werden. Wir waren 12, also wir drei \[tschechischen
Mädchen\], Stella Beck \[Lagerälteste im Frauenlager\] und ein paar
Leute aus dem Männerlager. Einer von denen war ein Kutscher \[Samuel
Kessler\]. \[\...\] Wir haben uns verabredet, mit Zunker und den
SS-Leuten mit zu gehen und dann wegzulaufen. Der Kutscher hatte so einen
Heuwagen und ein Pferd. Dort auf dem Wagen war Brot, Margarine und
Marmelade für die Deutschen. Eine große Menge. Damit sind wir gegangen.
In der ersten Nacht hat uns Kessler alle aufgeweckt und mit dem Wagen
und dem Brot sind wir weggegangen. In einer Stadt, durch die wir fuhren,
waren die SS-Männer von Görlitz und die haben unsere Männer erkannt. Wir
waren sehr gespannt. Sie wollten die Zivilkleider mit ihren Uniformen
tauschen. Da haben wir gesagt: Ja bitte, aber wir sind verlaust und es
besteht die Gefahr, dass wir mit Typhus infiziert sind. Sie ließen uns
durch. Auf einer Wiese haben wir noch ein Pferd gesehen. Dann haben wir
noch einen Wagen gesehen. Das Pferd war so schwach -- am Ende hatten wir
zwei Wagen und zwei Pferde. So sind wir nach Prag gekommen. Dort haben
wir uns verloren. Ich bin nach Prag gekommen mit Stella Beck, Samuel
Kessler und einem Mann aus Frankfurt.[^105]
:::

Wohin die Wachmannschaften geflohen sind, ist nicht ganz sicher.
Lagerkommandant Erich Rechenberg wurde jedenfalls am 11. Mai 1945
zusammen mit dem Wachmann Werner Weiss in Deutsch-Gabel (heute: Jablonné
v Podještědí, Tschechien) durch die Rote Armee gefasst.

Das Lager überließ man dem Chaos. Der ehemalige Häftling Leon Hostig
beschreibt wie sich Gefangene sich nun an ihren Folteren aus den eigenen
Reihen rechten:

::: leftbar
In dieser Zeit konntest du jeden umbringen und musstest dir deshalb
keine Sorgen machen. Ich sah den ein \[Kapo\] aus dem Lager kommen; er
sah uns auch. Er war von Baracke 7 und er kannte mich, weil ich eine
Zeit lang in der Küche arbeitete. Er wirkte so gnädig und lächelte, ich
sah ihn an, wie brutal er vorher war und wie er niemals lächelte. Ich
nahm den \[an einem Schleifstein geschärften\] Löffel, stieß ihn ihm in
die Seite und ging weiter. Ich weiß nicht, ob ich ihn getötet habe, aber
ich ließ den Löffel in ihm stecken. Ich ließ ihn am Straßenrand liegen.
[^106]
:::

Die Befreiung des Lagers und der Stadt Görlitz geschah zeitgleich am 8.
Mai 1945. Leider lässt sich nicht mehr genau feststellen, welche Einheit
der Roten Armee an jenem Morgen im Lager eintraf. Somit konnten auch
keine Informationen über die Anzahl und die körperliche Verfassung der
Gefangenen in Erfahrung gebracht werden.

Jakob Kinrus' Erlebnisse am Tag der Befreiung:

::: leftbar
Am 8. Mai 1945 früh um 6 Uhr sind wir aufgestanden, aber haben gesehen,
dass Lagerführer und Lagerältester und alle, die uns bisher bewacht
hatten, verschwunden waren. Von Weitem hörten wir Schüsse und sahen,
dass russische Truppen sich näherten. Deshalb hängten wir eine weiße
Fahne heraus und gingen ihnen entgegen. \[\...\] einer, der russisch
konnte, sagte ihnen: Hört mal zu, das ist ein Arbeitslager und wir sind
Juden \.... Ich war immer negativ zu Russland eingestellt. Aber Tatsache
ist, dass sie mir das Leben gerettet haben. Ich bin der Roten Armee
dankbar, die mich befreit hat.[^107]
:::

#### Die Zeit danach

Viele der ehemaligen Häftlinge schlossen sich unmittelbar nach der
Befreiung zusammen und gingen in die Stadt, um dort zunächst ihre
Grundbedürfnisse nach sauberer Kleidung, Essen und einer Unterkunft zu
befriedigen. Die Stadt war menschenleer und somit standen in vielen
Wohnungen und Häusern Tür und Tor geöffnet. Manche sahen es als ihr
gutes Recht an, für das durch die Deutschen entstandene Leid einen
materiellen Ausgleich zu suchen[^108]. Dr. Jakob Kinrus und andere
kümmerte sich zunächst um die noch immer zahlreichen schwer kranken
Menschen im Lager. Der Zahnarzt Kinrus trat deshalb in Verhandlung mit
sowjetischen Ärzten. Für besonders schwere Fälle erwirkten die
Lagerärzte bereits vor der Befreiung Einweisungen in ein örtliches
Krankenhaus (siehe Abschnitt über das Krankenrevier, S. ). Weitere
Einlieferungen hat es mit Sicherheit gegeben.

Keiner der Gefangenen stammte aus der unmittelbaren Umgebung von
Görlitz, die meisten waren hunderte, ja sogar über tausend Kilometer von
daheim entfernt. Die Ungewissheit über das Schicksal ihrer
Familienangehörigen mag viele dazu bewogen haben, schnellstmöglich nach
ihren Verwandten zu suchen und in ihre Heimat zurück zu kehren. Um die
Heimkehr zu erleichtern, gründete man in Zusammenarbeit mit der Roten
Armee ein Ortskomitee[^109]. Für viele der ehemaligen Gefangenen verlief
die Heimreise über eine Reihe von Auffanglagern. Andere ließen sich
jedoch für einige Jahre in Görlitz und Umgebung nieder[^110].

###### Unter Tulpen und Narzissen

Im Jahre 1946 begann man einige der Holzbaracken im Biesnitzer Grund zu
demontieren und anderenorts wieder aufzubauen[^111]. Im selben Jahr
bemühten sich die ersten Kleingärtner, Steine und Zementblöcke weg zu
schleppen und ein Stück Land zu gewinnen, auf dem sie sich in jener
Notzeit der Nachkriegsjahre zunächst Kartoffeln und Gemüse anbauen
konnten. In der unmittelbaren Nachbarschaft gab es bereits einige
Gärten, weshalb es offenbar naheliegend erschien, für weitere
Gartengrundstücke auf diesem mit Schweiß und Blut gedünkten Boden[^112]
Platz zu machen.

Spricht man heute mit Hobbygärtnern der Kleingartenanlage Biesnitzer
Grund (siehe Bild  ), so sind sich fast alle der Tatsache bewusst, ihr
Gemüse und ihre Blumen dort zu säen, wo einst hunderte hungrige
Häftlinge ihrem Verderben entgegen sahen. So verwundert es manche gar
nicht mehr, ein paar Patronenhülsen beim Umgraben zu finden oder beim
Bau einer Wasserleitung ein Gewehr zu entdecken. Schließlich hat man
auch einige Lauben mit den Zementbrocken der alten Baracken errichtet.

[^1]: Israel Gutman: Enzyclopädie des Holocaust, Band 3, S. 1412.

[^2]: Alfred Konieczny: Groß-Rosen, S. 18.

[^3]: Gemeint ist niemand geringeres als Franz Scholz, der katholische
    Geistliche im Görlitzer Ostteil, der über diese Zeit hinweg
    umfangreiche Eintragungen in sein Tagebuch machte. Später erklärte
    man ihn zum Ehrenbürger der Stadt Görlitz. Vgl. Franz Scholz:
    Görlitzer Tagebuch, 2. Auflage, S. 16.

[^4]: Vgl. Alfred Konieczny: Groß-Rosen, S. 18.

[^5]: Samuel Reifer. ZIH 301/2311.

[^6]: Ebendieser. Um was für Dokumenten es sich dabei handelte und wohin
    sie gebracht wurden, ist ungewiss. Zeitlich spricht er vom Februar
    1945. Am 12. Februar wurde Samuel Reifer, nach eigenen Angeben, ins
    Außenlager Zittau überstellt. ZIH 301/2311.

[^7]: Vgl. Alfred Konieczny: Groß-Rosen, S. 18.

[^8]: Dorota Sula und Andrea Rudorff: Zittau, in: Wolfgang Benz /
    Barbara Diestel (Hgs.): Orte des Terrors. Geschichte der
    nationalsozialistischen Konzentrationslager Band 6. Natzweiler.
    Groß-Rosen. Stutthof. S. 470-473. Verlag C. H. Beck, München 2008.

[^9]: Herbert Elger sah zwischen dem 8. und 12. Februar eine
    Häftlingskolonne, die Görlitz in Richtung Westen verließ. Er selbst
    war mit einem schwer bepackten Fahrrad unterwegs und kam mehrmals
    mit Wächtern und Häftlingen ins Gespräch. Herbert Elger wohnte
    später in Stockholm. LArchB B Rep 058 Bd. 1. Franz Scholz bezeugt
    auch KZ-Gefangene, die Richtung Westen zogen. Vgl. Franz Scholz:
    Görlitzer Tagebuch, S. 16. Vgl. Siegfried Hüttig: Ortschronik
    Altbernsdorf.

[^10]: Nathan Klajman, ZIH 301/2765. Die hier gemachten Zahlenangaben
    konnten jedoch nicht weiter überprüft werden.

[^11]: Telefonisches Interview mit Monik Mlynarski vom 18.11.2004.

[^12]: Der ehemalige Häftling Simon Schweizer berichtet, der
    Hauptsturmführer Michael hätte unter seinen Gefangenen ein hohes
    Ansehen genossen. Michales Wohnort war in Görlitz. Vor seiner Zeit
    als Lagerkommandand war Rittmeister in der Wehrmacht.

[^13]: Simon Schweitzer: Simons langer Weg, S. 152ff.

[^14]: Der Hinweis von Abram Rajchbart, nach dem auch Frauen aus dem
    Ghetto Litzmannstadt (Łódź, Polen) zusammen mit den von dort
    kommenden Männern viel früher in Görlitz eintrafen, konnte nicht
    weiter bestätigt werden.

[^15]: Das Außenlager Ludwigsdorf ging aus einem Lager der Organisation
    Schmelt hervor. Die durchweg weiblichen Gefangenen arbeiteten für
    Nobel-Dynamit. Der Zeitpunkt der Überstellung ins Görlitzer
    Außenlager variiert in den Aussagen von Chaja Zaks, Miriam Ben
    Shlomo und Toska Markowicz zwischen Ende März und Anfang April 1945.
    LArchB: B Rep 058 2231/4, sowie Mila Weisberg und Cesia Finkel; ZIH
    301/923 bzw. 301/924.

[^16]: Vgl. Alfred Konieczny: Groß-Rosen, S. 18.

[^17]: Ebenda. Die Evakuierung des Stammlagers Groß-Rosen setzte bereits
    in der zweiten Februarhälfte ein.

[^18]: RAG Verwaltungsbericht 1944/45, S. 47.

[^19]: Aussage von Anna Hynráková in einem Interview am 29.03.2005 in
    Prag.

[^20]: Kreisleiter Malitz stand in der Hierarchie über dem
    Lagerkommandanten Rechenberg. Ungewiss ist, inwieweit die
    Kommandantur des KZ Groß-Rosen und die WUMAG einen Einfluss auf die
    Evakuierung ausgeübt haben.

[^21]: Janusch Oborowicz. BStU MfS ASt 13/48 Bd. 2 / 392.

[^22]: Im Jahre 1945 übernahm ich in dem Arbeitslager Biesnitzer Grund
    den Fuhrpark der WUMAG, der sich im Lager Biesnitzer Grund befand.
    Mir unterstanden 11 Pferde und drei paar Ochsen und ca. 10
    Fuhrwerke. Außerdem war ich verantwortlich für die Verwaltung der
    Futtermittel, Geschirre und das gesamte Inventar. Arbeitskräfte aus
    dem Arbeitslager Biesnitzer Grund wurden mir für meine Arbeit nicht
    zugeteilt \.... Aussage von Gerhard Anton Sedlak, 1913 in Nieder
    Gurig, Kreis Bautzen geboren. BStU MfS ASt 13/48 Bd. 2 / 389.

[^23]: Samuel Reifer wurde dann im Zittauer Krankenhaus von der Roten
    Armee befreit. ZIH 301/2311.

[^24]: Im Lager Görlitz wurden etwa 200 Kranke zurückgelassen. Vgl.
    Jakob Rosenbaum: Von Görlitz nach Tirol, S. 39-45.

[^25]: Aussage von Jechiel Rappaport. LArchB B Rep 058 Bd. 2.

[^26]: Schlomo Graber: Schlajme.

[^27]: Schlomo Graber: Schlajme.

[^28]: Ich habe am Evakuierungsmarsch von Görlitz nach Rennersdorf
    teilgenommen. Ich bin aber nicht mit den gesunden Lagerinsassen
    gegangen, sondern mit einer kleineren Gruppe, die erst nachträglich
    vor dem Revier formiert wurde -- und die Kolonne einholte., heißt es
    in einer Aussage von Dov Bernard Levi. LArchB B Rep 058 Bd. 5.

[^29]: Aussage von Emmrich Schiffer. LArchB B Rep 058 Bd. 5.

[^30]: RAG Verwaltungsbericht 1943/44, S. 186 II.

[^31]: Laut Liesbeth Sägner.

[^32]: Laut Aussage von Horst Rohland, Elfriede und Bärbel Lorenz,
    Berthelsdorf Hauptstraße.

[^33]: Interview vom 25.01.2005 mit der Görlitzer Jüdin Ruth Pilz,
    welche zusammen mit Martha Jacob diesen Weg beschritt. Frau Jacob
    war weder Mitglied der SS noch gewalttätig. Ruth Pilz beschreibt sie
    als hilfsbereite und humane Person, die sich ebenso ihrem Schicksal
    ergeben musste. Vgl. auch: Roland Otto: Die Verfolgung der Juden in
    Görlitz während der faschistischen Diktatur, S. 102ff. Weiter
    Informationen über diesen Todesmarsch in: Heinz Israel: Im Wandel
    der Zeit -- 1285--1985, Beiträge zur 700-Jahrfeier der Gemeinde
    Deutsch-Paulsdorf, S. 33. Deutsch-Paulsdorf 1985.

[^34]: Vgl. Siegfried Hüttig: 750 Jahre Altbernsdorf auf dem Eigen, S.
    54.

[^35]: Aussage von Samuel Mandelbaum. LArchB B Rep 058 Bd. 2.

[^36]: Erich Kotter erhielt von Feldfebel Homelius den Auftrag dazu.
    BStU MfS ASt 13/48 Bd. 2 / 409.

[^37]: Erich Kotter. BStU MfS ASt 13/48 Bd. 2 / 409.

[^38]: Schlomo Graber: Schlajme, S. 85

[^39]: Janusch Oborowicz. BStU MfS ASt 13/48 Bd. 2 / 392.

[^40]: Janusch Oborowicz. BStU MfS ASt 13/48 Bd. 2 / 393.

[^41]: Aussage von Israel Braun. LArchB B Rep 058 Bd. 6.

[^42]: Janusch Oborowicz. BStU MfS ASt 13/48 Bd. 2 / 393.

[^43]: Aussage von Israel Braun. LArchB B Rep 058 Bd. 6.

[^44]: Schlomo Graber: Schlajme, S. 86.

[^45]: Jakob Rosenbaum: Von Görlitz nach Tirol, S. 39-45.

[^46]: Janusch Oborowicz. BStU MfS ASt 13/48 Bd. 2 / 393.

[^47]: Janek Schilid, am 04.08.1914 in Jaloschin/Welonyen geboren. BStU
    MfS ASt 13/48 Bd. 2 / 397.

[^48]: Interview vom 16.10.2004 in den Lehdehäusern / Kemnitz.

[^49]: Prozessakten von Czech. LArchB B Rep 058 Bd. 2.

[^50]: Interview mit Gerda Bötig durch Kurt Wolf vom Sommer 2004.

[^51]: Jakob Rosenbaum: Von Görlitz nach Tirol, S. 39-45.

[^52]: Jakob Rosenbaum: Von Görlitz nach Tirol, S. 39-45.

[^53]: Janusch Oborowicz, am 25.05.1923 in Breslau geboren. BStU MfS ASt
    13/48 Bd. 2 / 393.

[^54]: Liesbeth Sägner während eines Interviews in Rennersdorf, 2005.

[^55]: Hildegard Fleischmann, am 02.09.1915 in Schlegel geboren. BStU
    MfS ASt 13/48 Bd. 2 / 460. Bestätigt wurde dies auch durch Liesbeth
    Sägner während eines Interviews in Rennersdorf. Auch Christa
    Schuberts Großmutter hat dies gesehen.

[^56]: Interview mit Christa Schubert, Berthelsdorf, den 01.04.2005.

[^57]: UArch 7275.

[^58]: Ebenda

[^59]: Vgl. Robert Heinze: Ortschronik Rennersdorf. Reinhold Lehmann
    (\*26.03.1889) war eines von insgesamt 60 NSDAP Mitgliedern im Ort,
    die im Zuge der Entnazifizierung durch die sowjetische
    Militärkommandantur ermittelt wurden. KArchLZ Rennersdorf / 142.

[^60]: Im Sinne der Inspektion der Konzentrationslager von Oswald Pohl.

[^61]: Vgl. Isabell Sprenger: Groß-Rosen, S. 232.

[^62]: Gleiches gilt für das KZ-Außenlager Kunnerwitz, wo bereits vor
    dem Durchmarsch der Görlitzer KZ-Häftlinge ein Groß-Rosener
    Arbeitskommando bestand. Sohland am Rotstein, als zweite Station
    während des Todesmarsches von Görlitz nach Rennersdorf, soll jedoch
    nicht als KZ-Außenlager angesehen werden, da die Gefangenen dort nur
    einen Tag verweilten und kein geordneter Lagerbetrieb errichtet
    bestand.

[^63]: Ein Remontegestüt sorgt für die Aufzucht von jungen Pferden als
    Ersatz für solche, die durch Krieg oder andersartig sterben.

[^64]: Aussage von Abram Rajchbart. Jüdisch Historisches Institut
    Warschau, 301/715.

[^65]: Laut einem Interview mit Ilse Gießler, Dresden 2005.

[^66]: Aussage von Max Wachsmann. LArchB B Rep 058 Bd. 6.

[^67]: Aussage von Janusch Oborowicz. BStU MfS ASt 13/48 Bd. 2 / 392.

[^68]: Aussage von Janusch Oborowicz, BStU MfS ASt 13/48 Bd. 2 / 392.

[^69]: Interview mit Ilse Gießler, Dresden, März 2004.

[^70]: Ilse Gießler, am 24.12.1920 in Niederrennersdorf geboren. Die
    damals 26jährige bewohnte mit ihren Eltern ein heute nicht mehr
    stehendes Haus an der Hauptstraße (zwischen dem Abzweig Herrnhut und
    dem Wehr). Ihr Vater war vor 1933 KPD Mitglied, sie selbst ist weder
    dem Bund Deutscher Mädel, noch einer anderen NS-Organisation
    beigetreten und wurde deshalb vom damaligen Ortsgruppenleiter für
    vogelfrei erklärt. Im Jahre 1948 wurde sie als Zeugin im
    Malitz-Meinshausen-Prozess vorgeladen, jedoch aufgrund der
    ausreichenden Beweislast gegen die Angeklagten nicht mehr angehört.
    BStU MfS ASt 13/48 Bd. 2 / 462. Interview mit Ilse Gießler, Dresden,
    März 2004.

[^71]: Laut Aussage mehrerer Zeitzeugen, darunter Ilse Gießler, Helmut
    Sperling sowie Siegfried und Wolfgang Bittrich.

[^72]: Schlomo Graber: Schlajme, S. 87.

[^73]: Auguste Hergarten, am 22.06.1893 in Berthelsdorf geboren. BStU
    MfS ASt 13/48 Bd. 2 / 464.

[^74]: Vor und nach der Evakuierung gibt es übereinstimmende
    Zeugenaussagen, wonach die Frauen in einer eindeutig besseren
    körperlichen Verfassung waren als die Männer.

[^75]: Laut Liesbeth Sägner.

[^76]: Aussage von Abram Rajchbart. ZIH 301/715.

[^77]: Vgl. Gräfe / Töpfer: Die Konzentrationslager auf dem Territorium
    des heutigen Sachsens. Vgl. auch: Roman Zgłobicki: Obozy i cmentarze
    Wojenne w Zgorzelcu.

[^78]: Laut Ilse Gießler und vielen anderen teils ehemaligen
    Rennersdorfern.

[^79]: Interview mit den Brüdern Bittrich, die einst als kleine Jungen
    im Alter von 4 und 8 Jahren Zeuge der Gewalt wurden. Rennersdorf,
    29.03.2004.

[^80]: Janek Schilid. BStU MfS ASt 13/48 Bd. 2 / 397.

[^81]: Vgl. Katja Junge: Der Todesmarsch vom KZ-Außenlager Biesnitzer
    Grund nach Rennersdorf 1945, unveröffentlichtes Manuskript, S. 6.

[^82]: Interview mit Joachim Löwe, Rennersdorf 2004 und 2005.

[^83]: Interview mit Christa Schubert, Berthelsdorf, den 01.04.2005. Die
    Familien Wunderlich und Wenzel konnten nicht mehr eindeutig
    ausfindig gemacht werden.

[^84]: Interview mit Helmut Sperling, der in unmittelbare Nähe wohnte.
    Rennersdorf 23.12.2003.

[^85]: Janek Schilid. BStU MfS ASt 13/48 Bd. 2 / 397.

[^86]: Aussage von Isaac Weintraub. LArchB B Rep 058 Bd. 3/4

[^87]: Auguste Hergarten BStU MfS ASt 13/48 Bd. 2 / 464.

[^88]: Helmut Sperling. Interview vom Dezember 2003 in Rennersdorf.

[^89]: Aussage von Samuel Kessler, LArchB B Rep 058 Bd. 1 und 6.

[^90]: BStU MfS ASt 13/48 Bd. 2 / 172.

[^91]: Schlomo Graber: Schlajme, S. 87. Siehe auch: Aussage von Dov
    Bernard Levi, welcher selbst mit dem Lastwagen nach Görlitz zurück
    kam. LArchB B Rep 058 Bd. 5.

[^92]: Janusch Oborowicz. BStU MfS ASt 13/48 Bd. 2 / 393.

[^93]: Janek Schilid. BStU MfS ASt 13/48 Bd. 2 / 397.

[^94]: Unter anderem die Aussage von Maximilian Brandt, LArchB B Rep 058
    Bd. 3. Vgl. auch: Schlomo Graber: Schlajme, S. 88.

[^95]: Aussage von ursula Taube. BStU MfS ASt 13/4.

[^96]: Aussage von Ursula Taube. BStU MfS ASt 13/4.

[^97]: Aussage von Ursula Taube. BStU MfS ASt 13/4.

[^98]: Aussage von Ursula Taube. BStU MfS ASt 13/4.

[^99]: Janek Schilid. BStU MfS ASt 13/48 Bd. 2 / 397.

[^100]: Harry (Hirsch) Silbering. LArchB B Rep 058 Bd. 6. Interview mit
    Anna Hynráková vom 29.03.2005 in Prag.

[^101]: Abram Rajchbart. ZIH 301/715. Siehe auch: Schloime Monczink (Sol
    Munn) in einem Interview mit seinem Neffen Samson Munn im Juni 1984
    in den USA.

[^102]: Mila Weisberg, ZIH 301/923.

[^103]: Jechiel Rappaport. LArchB B Rep 058 Bd. 2.

[^104]: Jakob Kinrus. RAG Sammelgut KZ Biesnitzer Grund.

[^105]: Interview mit Anna Hyndráková vom 29.03.2005 in Prag

[^106]: Leon Hostig, in: David van Biema: Poisoned Lives.

[^107]: Aussage von Jakob Kinrus, in Gräfe / Töpfer: Ausgesondert und
    fast vergessen.

[^108]: Vgl. Schlomo Graber: Schlajme, S. 88ff. Vgl. auch Interview mit
    Sol Munn, Juni 1984.

[^109]: Aussage von Jakob Kinrus. Vgl. Gräfe / Töpfer: Ausgesondert und
    fast vergessen.

[^110]: Janek Oborowicz zum Beispiel.

[^111]: Zumindest eine solche Baracke stand, laut Hildegard Ecke und
    Kurt Wolf, später in Ebersbach bei Neugersdorf.

[^112]: Zitiert aus einem Artikel der Sächsischen Zeitung vom 8. Juli
    1955: Mit Schweiß und Blut gedünkter Boden im Biesnitzer Grund.
