## Ermittlungen gegen NS-Verbrechen

Das Blatt hatte sich längst gewendet -- die einstigen Angreifer,
Befehlshaber und Sklavenhalter wurden zu Angeklagten, Gejagten oder
Begründern des deutschen Wirtschaftswunders. Letzterer Vergleichspunkt
scheint abwegig, doch ist er für das Beispiel der Görlitzer WUMAG leider
zutreffend. Während der letzten Kriegswochen sollte die Stadt Görlitz
emporsteigen und sich als Festungsinsel der aus Osten kommenden Flut der
Rotarmisten behaupten. Durch den Angriff der Roten Armee auf Berlin
blieb der Stadt Görlitz etwas Zeit, ein klägliches Bollwerk gegen
sowjetische Panzer zu errichten und alle Neißebrücken zu sprengen. Die
buchstäbliche Drecksarbeit beim Bau der Barrikaden verrichteten die eben
aus Rennersdorf zurück beraumten KZ-Häftlinge und gingen daran zahlreich
zugrunde. Drei Jahre nach Kriegsende hatte man vermutlich alle Leichen
der Häftlinge geborgen. Die Verantwortung für die im KZ-Außenlager
Görlitz und Rennersdorf begangenen Verbrechen an der Menschlichkeit
wurden weder in der DDR noch in der BRD hinreichend beleuchtet,
geschweige denn umfassend juristisch geahndet. Die deutsche Teilung und
nicht zuletzt die unterschiedlichen ideologischen Absichten hinderten
und beeinflussten eine freie historische Aufarbeitung sowie eine
angemessene Erinnerungsarbeit.

### Opferzahlen

Die Frage nach der Anzahl derer, die zwischen dem 10. August 1944 und
dem 8. Mai 1945 in den KZ-Außenlagern Görlitz und Rennersdorf ums Leben
kamen, ist zunächst grundlegend und von besonderer Bedeutung, obwohl
unbedingt alle im Lager Inhaftierten als Opfer anzusehen sind. Dennoch
dürfen diese Zahlen nicht losgelöst als alleiniger Maßstab für das
Ausmaß nationalsozialistischer Gewaltherrschaft im KZ-Außenlager Görlitz
gesehen werden. Der Versuch, die nazistischen Gräuel an den Todesopfern
zu messen, scheitert an der Vernachlässigung der zum Tod führenden
Umstände und dem Leid derer, die dem Terrorsystem widerstehen konnten.
Im Umkehrschluss gilt dies auch für die Überlebenden, denn allein deren
Anzahl gibt keinen Aufschluss über das Ausmaß der durch die KZ-Haft
resultierenden physischen und psychischen Folgen für die Gesundheit und
die Lebenserwartung der Betroffenen. Gut 60 Jahren nach der Befreiung
ist es kaum noch möglich gewesen, eine größere Zahl Überlebender
ausfindig zu machen, um die körperlichen und seelischen Folgen der
Inhaftierung zahlenmäßig oder zusammenfassend darzustellen. Die anfangs
gestellte Frage der Opferzahlen im Sinne von Todesopfern kann jedoch
ebenfalls nur ungenügend beantwortet werden (siehe Tabelle
 [\[opferzahlentab\]](#opferzahlentab){reference-type="ref"
reference="opferzahlentab"}). Die Quellenlage lässt es unabhängig von
Überlebendenberichten weder zu, die genaue Zahl der Todesfälle zu
bestimmen, noch die Namen aller bekannten Toten zu ermitteln. Während
der Existenz des Lagers können indes 368 Todesfälle nachgewiesen werden,
mindestens 11 weitere geben angesichts vieler Berichte von ehemaligen
Gefangenen Anlass zur Spekulation.

[]{#opferzahlentab label="opferzahlentab"}

::: tabularx
.8Lrr

------------------------------------------------------------------------

**Ort** & **Zeitraum** & **Todesopfer**\

------------------------------------------------------------------------

Görlitz & 10.08.1944 -- 02.02.1945 & 140--141\
Todesmarsch & 18.02.1945 -- 23.02.1945 & 33--39\
Rennersdorf & 23.02.1945 -- 08.03.1945 & 12--16\
Görlitz & 03.02.1945 -- 08.05.1945 & 173\

------------------------------------------------------------------------

**Gesamt** & 10.08.1944 -- 08.05.1945 & **367--378**\

------------------------------------------------------------------------
:::

##### Todesopfer vor dem Todesmarsch

In den Einäscherungsbüchern der Görlitzer Friedhofsverwaltung
verzeichnete man 141 toteSchutzhäftlinge. Mit der Bemerkung Auf der
Flucht erschossen geht die erste Eintragung auf den 16. Mai 1944
zurück[^1]. Dabei geht nicht hervor, aus welcher Art von Lager der
Häftling entstammte. Noch bevor das KZ-Außenlager Görlitz formal und
offiziell existierte, ist eine weitere Einäscherung eines Warschauer
Juden vom 3. August 1944 verzeichnet, wobei ausdrücklich das Außenlager
Görlitz erwähnt wird. Dies könnte darauf hindeuten, dass ein
Vorauskommando aus Groß-Rosen damit beauftragt wurde, das Lager für die
Ankunft des ersten Gefangenentransportes vorzubereiten (siehe S. ). Das
erste Opfer, das im KZ-Außenlager Görlitz zu Tode kam, starb spätestens
13 Tage nach der Ankunft der ersten Häftlinge, zumindest vor dem 23.
August 1944. Die Urnen der Toten schaffte man nach Groß-Rosen. Die erste
Überstellung der Urnen erfolgte am 6. September, zehn weitere mit
insgesamt 28 Urnen bis zum 1. Dezember 1944. In der Folgezeit verblieben
alle weiteren 112 Urnen der Toten auf dem Görlitzer Friedhof im
Urnenhain XIII[^2]. Am 2. Februar 1945 kam es zur letzten Einäscherung
im Krematorium Görlitz. Von den 1449 bei der WUMAG beschäftigten
Häftlingen starben bis zum 1. Februar 1945 139 Menschen. Bewiesen ist,
dass zu diesem Zeitpunkt 1278 Juden in den Fabriken der WUMAG arbeiteten
und, laut dem Lagerschreiber Emrich Schiffer, 30 Kranke nach Zittau
überstellt wurden. Insofern ist die angegebene Zahl der Opfer
realistisch und sogar annähernd genau, bedenkt man, dass es auch
Überstellungen einzelner Gefangener nach Groß-Rosen gegeben hat[^3]. Bis
zu diesem Zeitpunkt erfolgten deshalb auch keine Einäscherungen im
Krematorium Zittau oder anderswo.   Auffallend ist insgesamt, dass es
sich bei den Toten ausschließlich um Männer handelt. Allem Anschein nach
kam den Frauen im KZ-Außenlager Görlitz bis Februar 1945 eine bessere
Behandlung zu.   Zum Abtransport der Leichen aus dem Lager ins
Krematorium wurde ein örtliches Beerdigungsinstitut namens Schubert &
Co[^4] beauftragt. Ein bis zweimal wöchentlich holte die Firma Schubert
die im Keller unter dem Waschraum liegenden Leichen mit einem
Pferdefuhrwerk ab[^5]. Laut Aussage des Inhabers, Ernst Schubert,
begleiteten ihn sechs Häftlinge und ein Arzt. Dieses
Leichenkommando verlud die Toten auf den Wagen und schaffte sie ins
Krematorium.

::: leftbar
Bei der Verladung war der seinerzeitige Lagerführer häufig zugegen, der
wiederholt mit einer Reitpeitsche auf die Häftlinge einschlug und sie
schwerstens misshandelte, wenn ihm die Verladung der Leichen nicht
schnell genug erschien. Infolge der Mißhandlungen brachen die Häftlinge
häufig zusammen.[^6]
:::

Zur Verbrennung der Leichen mussten selbige vorschriftsgemäß in einem
Sarg liegen. Von den insgesamt 303 bei der Sargtischlerei Ulrich
gekauften Särgen wurden bis zu 139 allein für die Einäscherung der
KZ-Häftlinge aus dem Biesnitzer Grund verwendet. Es ist jedoch nicht
auszuschließen, dass mehrere Leichen in einen Gefangenensarg gezwängt
wurden[^7].

##### Todesopfer während des Todesmarsches

Bei der Frage nach den Todesopfern ist es sehr schwer, eine verlässliche
Aussage zu treffen. Angaben über die Zahl der Opfer in Berichten von
Überlebenden sind, teilweise sogar in sich, widersprüchlich und
schwanken zwischen 50 und 1.000[^8]. Als glaubwürdiger gelten jedoch die
Angaben des ehemaligen Lagerschreibers, der damals sämtliche Sterbefälle
in der Häftlingskartothek registrierte[^9]. Er beruft sich auf 75 Tote,
die er mit eigenen Augen in Rennersdorf sah. Doch auch dafür gibt es
keine eindeutigen Beweise. Die bisher einzigen nachgewiesenen Todesfälle
wurden im Zusammenhang mit den Ermittlungen gegen den Görlitzer
Kreisleiter Malitz und Oberbürgermeister Meinshausen von der
Kriminalpolizei Görlitz, teils aufgrund von Hinweisen aus der
Bevölkerung, aufgedeckt. Nach Kriegsende exhumierte man einige Leichen
in Zusammenarbeit mit der sowjetischen Militärkommandantur, die unter
den Toten sowjetische Soldaten vermutete[^10]. Angesichts der eisigen
Witterungsbedingungen und der körperlich schlechten Verfassung der
Gefangenen in jenen Februartagen 1945 konnten unmöglich alle Toten nach
Rennersdorf transportiert werden. Gleichfalls war es aufgrund des
gefrorenen Erdreichs auch schwierig, die Leichen irgendwo zu begraben.
Lediglich in Sandgruben oder bereits vorhandenen Vertiefungen war es dem
sogenannten Leichenkommando möglich, die auf einem Wagen mitgeführten
Toten zu verscharren.   Lagerschreiber Emmrich Schiffer:

::: leftbar
Nach unserer Marschkolonne ging ein Leichenkommando -- von Lagerinsassen
formiert. Das Leichenkommando musste ein Pferdefuhrwerk schieben. Auf
diesen Wagen wurden die Leichen geworfen und uns nachgebracht. Ich
gedenke keine Namen der Angehörigen des Leichenkommandos, das etwa 6--8
Mann stark gewesen war.[^11]
:::

Schon allein dieser Umstände wegen wäre es unmöglich gewesen, hunderte,
geschweige denn 1.000 Tote auf den reichlich 35 km Wegstrecke zu
verscharren. Es spricht jedoch vieles dafür, dass zwischen Görlitz und
Rennersdorf noch mindestens ein Massengrab unentdeckt ist[^12].

In den Ermittlungsakten der Kriminalpolizei finden sich genaue Angaben
zu den Leichenfunden zwischen Görlitz und Rennersdorf. In den folgenden
Absätzen wird auf die Ermittlungsergebnisse je Ortshcaft genauer
eingegangen.

###### Kunnerwitz[]{#kunnerwitz label="kunnerwitz"}

In Kunnerwitz verbrachten die Gefangenen drei Tage und zwei Nächte auf
dem Stadtgut. Aufgrund eines Hinweises eines ehemaligen Gefangenen
entdeckte man im April 1946 insgesamt 13 Leichen in einer mit Kompost
überhäuften Jauchegrube auf dem Gut. Sämtliche Ermittlungen wurden in
Zusammenarbeit mit der Zentralstelle H der Kriminalpolizei Görlitz und
der Operativgruppe der NKWD getätigt, heißt es in einem Bericht von
Kommissar Reimann vom 19.04.1946[^13]. Die Leichen brachte man auf den
Jüdischen Friedhof nach Görlitz[^14]. An der Mauer des Stadtgutes
exhumierte die Kriminalpolizei vier weitere Tote. Kriminalkommissar Kurt
Wolf exhumierte 1948 einen weiteren Leichnam am Ortseingang von
Kunnerwitz[^15]. Die Leiche war nur teilweise mit Abraum bedeckt.

Im gleichen Zeitraum wurden drei Leichen in einer Sandgrube (nahe dem
Sandweg) geborgen. Im Unterschied zu den anderen Leichenfunden fanden
die Ermittler keinerlei Reste von Kleidung oder anderen Utensilien, wie
Holzschuhe oder Geschirr. Kurt Wolf mutmaßt deshalb, dass es sich
hierbei im Opfer des KZ Außenlager Kunnerwitz handele. Ein
bemerkenswertes Indiz dafür sind die unzusammenhängenden Finger- und
Fußknochen, die in der Kürze der Zeit (1945-1947) nicht hätten verwesen
können, trotzdem der sauerstoffreiche Sandboden die Verwesung
beschleunigt haben kann. Alle vier Leichen setzte man auf dem Jüdischen
Friedhof zu Görlitzer bei.

Otto Pfeffer, der einstige Friedhofsgärtner des Jüdischen Friedhofs,
bestätigt unabhängig von den bisher erwähnten Leichenfunden die
Überführung von fünf Leichen noch während des Krieges:

::: leftbar
Etwa im März 1945 brachte wiederum eine Speditionsfirma fünf Särge, die
in einem Gemeinschaftsgrab von 4 m Länge beigesetzt wurden. Es handelte
sich hierbei um Leichen, die auf der Strecke Kunnerwitz--Sohland auf den
Feldern verscharrt gewesen waren und ausgegraben wurden. Die Überbringer
dieser Leichen sagten: Das sind Sammelleichen, die seinerzeit auf dem
Wege der Häftlinge schlapp gemacht haben und auf den Feldern verscharrt
wurden.[^16]
:::

  -- --
     
     
     
     
  -- --

  -- --
     
     
     
     
  -- --

###### Deutsch-Paulsdorf

In Deutsch-Paulsdorf wurden laut Hinweisen der Bevölkerung insgesamt
vier getötete Häftlinge gefunden, deren Verbleib ungewiss ist. Nach
Recherchen des damals in der Sache ermittelnden Kriminalkommissars Kurt
Wolf lag ein Toter an der Waage (Waage für landwirtschaftliche Güter),
zwei weitere in der Nähe des Hofes von Familie Schmidt und ein Leichnam
in der Sandgrube, nahe dem ehemaligen Abzweig nach Altbernsdorf[^17].

###### Obersohland am Rotstein[]{#sohland label="sohland"}

Während des Aufenthalts der Gefangenen im Göbelschen Gut in Obersohland
starben des nachts fünf Menschen; angeblich weil sie versuchten, auf den
Dachbalken der Scheune zu schlafen und herunter fielen. Jene fünf
Leichen wurden an einem unbekannten Ort hinter dem Obersohländer
Friedhof beigesetzt und mit keinem Wort in den Kirchenbüchern vermerkt.
In einem nahe gelegenen Waldstück kam es angeblich zu einer Erschießung
von sieben Menschen. Der genaue Ort ist bis heute unbekannt[^18].

###### Lehdehäuser

Wie bereits erwähnt, waren einige Bewohner der Lehdehäuser Zeuge, wie
vor ihren Augen ein entkräfteter Häftling niedergeschlagen und
erschossen wurde. Wahrscheinlich sammelte das Leichenkommando den Toten
später ein, denn laut Aussage eines Anwohners hinterließ die
Gefangenenkolonne keine Spuren.

###### Buschschenke[]{#buschschenke label="buschschenke"}

Gerda Bötig bezeugt einen Toten, den sie unweit vom elterlichen Haus auf
der Straße liegend fand.   Am 03. November 1947 heißt es in einem
Polizeibericht, dass man auf der Verbindungsstraße Kemmnitz--Strahwalde
sieben Leichen im Wald gefunden hatte (Bild  ), welche am 26.02.1945
durch den Totenbettmeister von Kemnitz, August Hänsch, auf Anordnung des
damaligen Bürgermeisters von Kemnitz, Richard Milsch, an der Fundstelle
beerdigt wurden.[^19]. Die Exhumierung im Jahre 1947 geschah im Beisein
der Großschweidnitzer Ärzte Dr. Ehrlich und Fräulein Dr. Elfriede
Ochsenfahrt[^20]. Von den gefundenen sieben stark verwesten Leichen
waren drei Schädel total zertrümmert, ein weiterer wies an beiden
Schläfen handtellergroße Sprünge auf[^21]. Bei den drei anderen
Skeletten konnten die Ärzte keine sichtbaren Spuren von Gewalteinwirkung
feststellen. Die Umbettung geschah am 4. November 1947; wohin, wurde
nicht erwähnt. Ferner gibt der Polizeibericht Aufschluss über die
persönlichen Dinge, welche die Opfer während des Marsches mit sich
führten. Neben sieben paar Holzschuhen fanden die Ermittler: Tabakdose
mit Inhalt eine Zigarettenspitze, 1 Ausschnitt einer Zeitung in
slawischer Sprache, 5 blecherne Essschüsseln, 3 Löffel, 1 Taschenmesser
und 2 feststehende Messer.

Zu den Fundstücken zählte die Polizei noch etwas wesentlich
Wertvolleres, dessen sich die damaligen Machthaber in gleicher Weise
bedienten, wie zuvor die SS in den Konzentrationslagern:

::: leftbar
Ferner wurden auf Anordnung der SMA \[Sowjetische
Militäradministration\] die Gold- und Silberzähne aus den Gebissen der
Toten entfernt und werden sofort nach Eintreffen in der hiesigen
Dienststelle der SMA-Dienststelle Löbau/Sa. zugestellt.[^22]
:::

Der materielle Wert des Edelmetalls wiegt bei diesem Befehl
offensichtlich schwerer als die Pietät.

###### Berthelsdorf

Es gibt Gerüchte über Leichenfunde zwischen der Neuberthelsdorfer
Sandgrube und dem Oberhof (Berthelsdorf), jedoch keine bestätigten
Funde[^23]. Alle innerhalb der Ortschaft verstorbenen Menschen schaffte
man wahrscheinlich mittels Wagen nach Rennersdorf[^24].

##### Opfer in Rennersdorf

Die Zahl der in Rennersdorf zu Tode gekommenen KZ-Gefangenen ist ebenso
unbestimmt wie die Opferzahl während des Todesmarsches.

Laut dem damaligen Ortschronisten Robert Heinze wurden bereits im
Oktober 1945 insgesamt acht Leichen durch ehemalige Rennersdorfer
NSDAP-Mitglieder freigelegt und auf den örtlichen Friedhof
umgebettet[^25]. Bei der Exhumierung verpflichtete die SMA eine
Schulklasse aus Rennersdorf zur Anwesenheit[^26].

Eine andere Rennersdorfer Schulklasse machte bei einem Ausflug eine
grausige Entdeckung, als beim Laufen abseits des Weges mehrere Knochen
hervortraten[^27]. Die daraufhin verständigte Polizei leitete weitere
Ermittlungen ein. Am Donnerstag dem 29.01.1948 kam es dann in
Rennersdorf zur Ausgrabung von vier Leichen. Anwesend waren der
Polizeiarzt Dr. Gottschalk aus Görlitz und die Kriminalkommissare
Reimann, Wolf, Hulek, der stellvertretende Bürgermeister Richter[^28],
ferner einige Arbeiter, zumeist ehemalige Mitglieder der
Hitlerjugend[^29].

::: leftbar
An einem etwa 2 Meter hohen Abhang befand sich die Fundstelle. Der
Abhang war mit Grasbüschen bewachsen. Die Fundstelle war bei unserem
Eintreffen leicht mit Erde und Stroh zugedeckt. Die Kriminalpolizei
hatte bereits einige Tage zuvor mit dem Suchen begonnen. Als sie dabei
auf die Knochenreste stießen, wurde die Arbeit nicht fortgesetzt, da die
Kriminaldienststelle Görlitz K5 verständigt werden musste[^30]. Nachdem
von uns die Erde entfernt wurde, waren 4 Skelette von Leichen zu sehen,
die in schwarze Lumpen gehüllt waren. Die Skelette lagen geschichtet
nebeneinander, zwei Kopfschädel neben den Beinen und Fußknochen der
beiden anderen Skelette, die in umgekehrter Richtung lagen. Beim
Herausnehmen der Knochenstücke zerfielen diese sofort in einzelne
Stücke, so dass der Zusammenhang verloren ging. Bei der oberflächlichen
Untersuchung durch Dr. Gott-schalk konnten keine Schuss- oder
Schlagverletzungen festgestellt werden. Die Knochenstücke wurden in
Papiersäcke geborgen und im Kraftwagen nach Görlitz gebracht.[^31]
:::

Merkwürdig erschien den Ärzten, dass sämtliche Schädel Frakturen mit
glatten geradlinigen Bruchlinien aufwiesen, die eine Einwirkung eines
stumpfen Gegenstandes ausschließen[^32]. Bei zwei der Leichen fehlten
die Halswirbel (Atlas), was auf einen Einschuss im Genick als
Todesursache schließen läßt. Der Verbleib dieser insgesamt zwölf
Leichname in Rennersdorf ist indes nur teilweise geklärt. Laut der
Grabsteininschrift sind auf dem Rennersdorfer Friedhof 10 jüdische
Menschen begraben. Demnach bestattete man neben den acht, im Jahre 1945
gefundenen, Leichen, noch zwei weitere, deren Fundstelle unbekannt ist
oder mit der im Februar 1948 aufgedeckten Grabstätte übereinstimmt
(siehe auch S. ).

Die Differenz zwischen den von Emmrich Schiffer dokumentierten 75 in
Rennersdorf angekommenen Toten und den tatsächlich gefundenen 12
Leichnamen, konnte nicht aufgeklärt werden. Auch die im Jahre 2010 im
Auftrag des Sächsischen Landesamtes für Archäologie durchgeführten
archäologischen Untersuchungen des Waldstücks neben dem Pferdestall
blieben ergebnislos.

##### Todesopfer zwischen März und Mai 1945

Bei Rückkehr der Gefangenen nach Görlitz befand sich die Stadt immer
noch im Ausnahmezustand. Die Flüchtlingsströme aus Osten und die nahe
liegende Front bedingten während dieser Zeit viele Todesfälle, welche
die örtlichen Bestatter kaum noch bewältigen konnten. Im Tagebucheintrag
des Görlitzer Predigers Franz Scholz[^33] heißt es bereits am 12.
Februar:

::: leftbar
Die Leichenhalle auf dem städtischen Zentralfriedhof platzt aus allen
Nähten. Die Toten sind dort längst nicht mehr alle unterzubringen.
\[\...\] Für die Leichen der Erwachsenen wird die riesige Halle der
Nikolaikirche bestimmt.
:::

Es scheint klar, dass die Einäscherung weiterer KZ-Häftlinge unter
diesen Umständen unmöglich erschien[^34] und die Lagerleitung eine
andere Möglichkeit finden musste, sich der fortlaufenden Todesopfer im
Lager zu entledigen. Berichte, wonach es auch im Krematorium Zittau zur
Einäscherung Görlitzer Häftlinge kam, ließen sich weder widerlegen noch
eindeutig bestätigen. Im Krematorium Zittau sind zwischen dem 19.
Februar und 7. Mai 1945 insgesamt 106 jüdische Häftlinge in den
Einäscherungsbüchern verzeichnet. Mindestens 29 der dort aufgeführten
Häftlingsnummern weichen nur geringfügig von den Nummern Görlitzer
Häftlinge ab. Die Angaben sind aber jeweils nicht eindeutig einer Person
zuzuordnen, da entweder die Häftlingsnummer oder der Name gelistet ist.
Der nur wenige hundert Meter vom Lager entfernte Jüdischen Friedhof
wurde in der folgenden Zeit als notdürftiger Bestattungsort der toten
Häftlinge sowie der im Lager hingerichteten Personen genutzt. Die
Gefangenen mussten dafür mehrere Massengräber errichten. Zur Öffnung
zweier Massengräber auf dem jüdischen Friedhof kam es zwischen dem 19.
und 22. Februar 1948 im Zuge der Ermittlungen gegen den Görlitzer
Kreisleiter Malitz und Oberbürgermeisters Meinshausen[^35]. Bei der
gleichzeitigen Exhumierung der sterblichen Überreste fanden die
Ermittler insgesamt 173 Leichen
(Bild. [\[leichenzeitung\]](#leichenzeitung){reference-type="ref"
reference="leichenzeitung"}), darunter sechs Särge mit jeweils 1--3
Leichen darin. Alle übrigen Leichen fanden die Ermittler in bis zu vier
Schichten übereinander gestapelt und unbekleidet in den Gräbern.
Mindestens[]{#weiss label="weiss"} drei von ihnen hatten längere Haare,
was zunächst die Vermutung nahe legt, dass es sich bei ihnen nicht um
Lagerinsassen handelt, sondern vielmehr um die Kriegsgefangenen, die
während der letzten beiden Kriegsmonate im Lager umgebracht wurden.
Dieser Schluss gilt nicht unbedingt, da insbesondere jene Frauen im
Lager lange Haar trugen, die ab Januar 1945 in Görlitz eintrafen[^36].

Als bemerkenswert gilt der Fund von einer in weißes Tuch gehüllten Frau.
Der Überlebende Janek Oborowicz bekundet, dass es sich dabei um eine
Ungarin handelt, deren Leichnam er selbst gesehen hat[^37]. Darüber
hinaus konnten die Ermittler unter den Opfern noch zwei weitere Frauen
ausmachen. Einige Leichen trugen Zivilkleidung und bei zwei weiteren
konnte eindeutig festgestellt werden, dass sie zum Zeitpunkt des Todes
nicht älter als 19 bzw. 20 Jahre waren. Die Polizeistellte schließlich
fest, dass einige (nicht unbedingt alle) der im Lager von der SS und
Gestapo hingerichteten Kriegsgefangenen und Fremdarbeiter an keinem
anderen Ort als dem Jüdischen Friedhof beigesetzt wurden[^38].   Der
damals in die Ermittlungen involvierte Polizeikommissar Kurt Wolf
schreibt dazu:

::: leftbar
Oberarzt Dr. Scheit vom Friedrichstädter Krankenhaus in Dresden konnte
anhand von Ein- und Ausschusslöchern oder Schlagverletzungen am Kopf
nachweisen, dass ein großer Teil der Häftlinge nicht nur eines
Hungertodes starb, sondern durch äußere und brutale
Gewalteinwirkung.[^39]
:::

  -- -- --
        
        
  -- -- --

### Ermittlungen gegen NS-Verbrecher[]{#ns-verbrechen label="ns-verbrechen"}

Bereits im Februar 1942 beschlossen die Alliierten auf der Konferenz von
Jalta, alles Mögliche zu tun, um den deutschen Militarismus und Nazismus
zu vernichten und endgültig die Garantie dafür zu schaffen, dass
Deutschland nie wieder dazu in der Lage sein wird, den Weltfrieden zu
brechen[^40]. Konkretisiert wurde dieses Vorhaben durch die Direktive
Nr. 24 des Alliierten Kontrollrates im Januar 1946. Um dieses Ziel zu
erreichen, sollten alle nazistischen und militärischen Einflüsse aus
öffentlichen Einrichtungen, dem Kultur- und Wirtschaftsleben entfernt,
und sämtliche Kriegsverbrecher angeklagt und verurteilt werden. Die
Notwendigkeit, die Straftäter des KZ-Außenlagers Görlitz vor Gericht zu
stellen, wurde aber auch maßgeblich durch die ehemaligen Gefangenen
forciert. Des Weiteren bestand ein erhebliches öffentliches Interesse,
die zahlreichen Leichenfunde aufzuklären und die dafür verantwortlichen
Personen zur Rechenschaft zu ziehen. In der sowjetischen Besatzungszone
begannen die Ermittlungen im Zusammenhang mit dem Görlitzer KZ-Lager
zwar relativ zeitig, doch ermittelte man erst im Jahre 1948 intensiver,
als es darum ging, die Görlitzer Hauptkriegsverbrecher dingfest zu
machen. Sämtliche Ermittlungsverfahren, die in den westlichen
Besatzungszonen bzw. der BRD eingeleitet wurden, basierten entweder auf
Strafanzeigen ehemaliger Gefangener oder auf Hinweise polnischer
Behörden, welche ihrerseits sehr konsequent gegen NS-Verbrecher
vorgingen.   Eine vergleichende Bewertung des Umgangs mit NS-Verbrechern
in der DDR und der BRD lässt sich anhand der wenigen hier betrachteten
Fälle jedoch nicht vornehmen und ist auch nicht das Anliegen dieses
Buches. Die hier betrachteten Fälle machen dennoch deutlich, dass die
Verantwortung für die Geschehnisse im KZ-Außenlager Görlitz nicht auf
eine homogene Personengruppe reduziert werden kann, obwohl weder
Staatsanwaltschaften noch Gerichte gewillt waren die Verstrickung
zwischen Funktionshäftlingen, Lagerpersonal, Staatsorganen und
Wirtschaft gebührend zu berücksichtigen. Dem entgegen steht die
wahrscheinlich größere Zahl derer, die von den sowjetischen Besatzern
wegen bestimmter Beziehung zum Görlitzer KZ-System ohne richterliches
Urteil in sowjetischen Speziallagern wie Bautzen festgehalten
wurden[^41].

Eine genauere Betrachtung der Ermittlungen im Zusammenhang mit dem
KZ-Außenlager Görlitz erfolgt anhand der einzelnen Fälle.

###### Der Lagerkommandant Erich Rechenberg[]{#rechenberg_ahndung label="rechenberg_ahndung"}

Die Flucht Rechenbergs misslang am 11. Mai 1945 in Deutsch-Gabel
(Jablonné v Podještědí, Tschechien), wo er und einige Wachleute in die
Arme der Roten Armee fielen. Rechenberg verbrachte die folgenden
achteinhalb Jahre in den sowjetischen Kriegsgefangenenlagern
Hoyerswerda, Frankfurt/Oder, Rybinsk (ab Juli 1945), Nowo Tscherkask,
Tanganrok, Rostow, Schachty, Tanganrok und zuletzt in Krasnopolje (bis
September 1953)[^42]. Nach seiner Rückkehr erhielt er durch die
Bundesrepublik Deutschland, offenbar ganz selbstverständlich, 4140 DM
Entschädigung für die Zeit seiner Gefangenschaft[^43]. Nachdem polnische
Behörden erhebliches Beweismaterial zur Verfügung stellten, begann die
Staatsanwaltschaft Berlin im Jahre 1970 gegen Erich Rechenberg zu
ermitteln. Gemäß § 170 Abs. 2 wurde das Verfahren gegen ihn am 6.
Dezember 1971 aufgrund widersprüchlicher Zeugenaussagen und fehlender
Identifizierung der Person Rechenberg durch Zeugen eingestellt. Der Name
Rechenberg war den über 100 Befragten zumeist unbekannt, nicht jedoch
sein Aussehen. Bei den Rechthilfeersuchen verzichteten die Behörden auf
die Beilegung von Fotos des Beschuldigten und fragten statt dessen nur
nach seinem Namen. Letztlich fand sich lediglich ein belastender Zeuge,
dessen alleinige Aussage allerdings nicht als ausreichend erachtet wurde
und zudem teilweise im Widerspruch zu Aussagen anderer Häftlinge stand.
Während des gesamten Verfahrens wurde Rechenberg nicht ein einziges Mal
zu den Vorwürfen befragt. Die Polizei tat sich sogar schwer, Herrn
Rechenberg daheim ausfindig zu machen, obwohl er seinen Wohnsitz seit
den 1950er Jahren nicht änderte und zeitweilig sogar eine Anstellung im
Landgericht Berlin hatte. Die ermittelnde Staatsanwaltschaft versäumte
es völlig, in Betracht zu ziehen, dass sich Rechenbergs
Verantwortungsbereich auf fünf weitere KZ-Außenlagern erstreckte, deren
Überlebende nicht zu Aussagen herangezogen wurden.   Aber was zählt
schon ein Überlebender. Der Berliner Oberstaatsanwalt Wolke brachte es
letztmalig am 20. August 1996 in einer Verfügung auf den Punkt:

::: leftbar
Was der Zeuge Schlomo Graber in Bezug auf den Beschuldigten sagen kann,
ist nicht bekannt. Es dürfte kaum damit zu rechnen sein, dass er
Umstände zu bekunden in der Lage ist, die zu einer Wiederaufnahme des
Verfahrens führen. Dessen ungeachtet wird man wohl den Versuch machen
müssen, ihn zu hören. Da die Anhörung nach Lage der Dinge sich aber
nicht auf konkrete, in das Wissen des Zeugen gestellte Tatsachen stützt,
sondern nur darauf beruht, dass er Überlebender des KL ist, dürfte eine
förmliche Wiederaufnahme der Ermittlungen damit nicht verbunden
sein.[^44]
:::

Um bei Herrn Wolke Gehör zu finden, bedarf es offenbar etwas mehr als
das Bezeugen von Straftaten. Schlomo Graber wurde nie von deutschen
Behörden zu den Verbrechen im KZ-Außenlager Görlitz befragt. Erich
Rechenberg erfreute sich eines hohen Alters und verstarb im Jahre 2000
in Ratzeburg bei Berlin.

###### Lagerführer Zunker[]{#zunker_ahndung label="zunker_ahndung"}

Über das Schicksal des Oberscharführers Zunker ist nur soviel sicher,
dass er nach einer Kriegsgefangenschaft in Dachau 1947 an Polen
ausgeliefert und am 25. Januar 1949, zusammen mit dem Lagerältesten
Czech, in Łódź hingerichtet wurde[^45]. Gerüchten nach war Zunker mit
einer ungarischen Jüdin liiert und hat sich gemeinsam mit ihr auf die
Flucht begeben[^46].

###### Der Lagerälteste Hermann Czech[]{#czech_ahndung label="czech_ahndung"}

Ein ehemaliger Häftling des KZ-Außenlagers Bunzlau (heute: Bolesławiec,
Polen) namens Monik Mlynarski verbrachte während der Evakuierung seines
Lagers zwar nur wenige Tage im Görlitzer Lager, doch gelang es ihm den
Görlitzer Lagerälteste ausfindig zu machen:

::: leftbar
Ich wollte ein Schloss in einem Erfurter Eisenwarengeschäft kaufen. Dies
war nicht zu haben, deshalb wollte ich den Chef sprechen. Dieser war
Czech. Ich fragte, ob er Lagerältester in Görlitz gewesen sei. Er
erwiderte: Alter Kollege und bot mir eine Zigarette an. Im Hotel
erzählte ich meinen Freunden davon. Diese wiederum klärten mich auf,
dass Czech der schlimmste Verbrecher sei und Frauen vergewaltigt hatte.
Daraufhin habe ich Czech bei der Polizei angezeigt.[^47]
:::

Ein von ehemaligen Häftlingen aufgesetztes Schreiben führte 1947 zur
Verhaftung Hermann Czechs:

::: leftbar
Berlin-Schlachtensee, 22. Februar 1947:\
Die unterzeichneten ehemaligen KZ-Häftlinge des KZ-Lagers Görlitz bitten
die Behörden hiermit, die Verhaftung des Hermann C Z E C H\
geb. 27.10.1892\
in Breslau\
jetzt Wohnhaft in Erfurt, Zeitlitzerstr. 12, b/Herrn Zenser vorzunehmen.
Dieser Hermann Czech war im KZ-Lager Görlitz bis März 1945 als
Berufsverbrecher Lagerältester. In dieser Eigenschaft hat er alles
getan, um die Häftlinge für jede Kleinigkeit zu quälen und zu ermorden.
Er hat beim Lagerkommandanten die Erschießung von unzähligen Häftlingen
veranlasst. Er selbst hat täglich die Häftlinge für jede Kleinigkeit
durchgepeitscht und gequält, hat das Essen, was für Lagerinsassen
bestimmt war, für eigene Zwecke und für seine Leute genommen. Sein
Vermögen hat er durch Diebstahl von Kleidern, Lebensmitteln, sowie
Zigaretten, die für die Häftlinge bestimmt waren, erworben. Er war der
grausamste Sadist, der seine Freude an der Quälerei und Ermordung der
Häftlinge hatte. Kranke Häftlinge hat er aus dem Revier genommen und sie
zur Arbeit gejagt, von der sie nicht mehr zurück kamen. Dagegen hat er
seine Kapos und Mithelfer geschützt und sie damit zu weiteren
Schandtaten angespornt. Die Zuteilung von Lebensmitteln und Zigaretten,
welche die Häftlinge für ihre Arbeit von der Firma WUMAG bekommen
sollten, hat er verschoben und die Häftlinge verhungern lassen.[^48]
:::

Izaak Weintraub, Bernard Rus und Leon Hecht veranlassten durch ihre
Aussagen bei der Polish War Crimes Mission in Bad Salzuflen einen
Auslieferungsantrag nach Polen. Am 20.7.1947 wurde er schließlich
dorthin ausgeliefert und 1948 zusammen mit dem ehemaligen SS-Lagerfüher
Zunker vor dem Kriegsgericht in Łódź zum Tode verurteilt[^49]. Die
Vollstreckung des Urteils erfolgte am 27. Januar 1949.

###### Die Lagerkapos[]{#kapos_ahndung label="kapos_ahndung"}

Einen Tag vor der Befreiung des Lagers hatte sich der Lagerkapo Jacob
Tannenbaum nach Italien abgesetzt, wo er mit importierten
Schwarzmarktgütern Geschäfte machte. In Florenz lernte er seine zweite,
20 Jahre jüngere Frau kennen, mit der er später drei Kinder hatte. Der
*Displaced Persons Act* ermöglichte Tannenbaum im Dezember 1949 die
Einreise in die USA. Sechs Jahre später, im März 1955, erkannte man ihm
die amerikanische Staatsbürgerschaft zu[^50]. In New York arbeitete er
in der Folgezeit bei einem Lebensmittelgroßhändler. Seine aktive
Mitgliedschaft in der orthodoxen Jüdischen Gemeinde *Temple Beth El* in
Manhattan Beach verlieh ihm Anonymität, da ihre Mitglieder von den
übrigen orthodoxen Gemeinden relativ isoliert waren.

Nachdem die USA über 35 Jahre lang Kriegsverbrecher in der Mitte der
Gesellschaft ignoriert hat, gründete das Justizministerium 1979 das
*Office of Special Investigations* (OSI). Dieses befasste sich mit
Tannenbaum, welcher 1978 duch einen ehemaligen Görlitzer Häftling
angezeigt wurde. Der Fall verzögerten sich jedoch bis in die späten
1980er Jahre aufgrund der außergewöhnlichen ethischen Komplexität, den
Schwierigkeiten an dutzende Zeugenaussagen aus aller Welt zu gelangen
und den Vorgesetzten, die sich schwer damit taten, einen Juden eines
Kriegsverbrechens anzuklagen. Ihm wurde vorgeworfen, als Aufseher in
einem NS-Konzentrationslager an der Verfolgung und Inhaftierung von
Menschen, aufgrund ihrer Rasse oder Religion, beteiligt gewesen zu sein.
In der Pressemeldung des OSI werden Tannenbaum brutale körperliche
Misshandlungen an Häftlingen vorgeworfen. Es handelte sich um einen
Zivil-, nicht jedoch um ein Strafprozess, bei dem es darum ging,
Tannenbaum auszubürgern und abzuschieben. Während der Verhöre durch die
beteiligten Anwälte verlor Tannenbaum mehrmals das Bewusstsein. Ärzte
attestierten ihm Herz- und Kreislaufbeschwerden. Angesichts seiner
gesundheitlichen Verfassung ersuchte man, um seines Lebens Willen, keine
Abschiebung. Die US-Regierung beließ es dabei, da Tannenbaum seine
staatsbürgerlichen Rechte, d.h. seine US-amerikanische
Staatsbürgerschaft freiwillig abgab. In ähnlichen Fällen hatten die USA
bereits John Demjanjuk nach Israel und Karl Linnas an die UDSSR
ausgewiesen. Tannenbaum hätte ein ähnliches Schicksal ereilt, wenn man
ihn unmittelbar nach der Anzeige des Falls -- als er sich noch bester
Gesundheit wägte -- verurteilt hätte Der ambivalente Fall Tannenbaum
erregte internationales Aufsehen in den Medien und bei jüdischen
Organisationen[^51]. Tannenbaum spendete Zeit seines Lebens an das
*Simon Wiesenthal Center* in Los Angeles.[^52]   Der zweite Lagerkapo,
Schneebaum, soll unter anderen Namen in den USA untergetaucht sein.

###### Der Blockälteste des Block 8: Adolf Eichner[]{#eichner_ahndung label="eichner_ahndung"}

Sechs Jahre Haft wegen Körperverletzung mit Todesfolge und 6 Jahre
Entzug bürgerlicher Ehrenrechte unter Anrechnung der Untersuchungshaft,
lautete das Urteil eines Hamburger Gerichts gegen den Angeklagten Adolf
Eichner[^53]. Auf der Hamburger Reeperbahn erkannten ihn Zeugen, die er
zunächst mit Geld bestechen wollte. Der zuvor mehrmals wegen Hehlerei
straffällig gewordene Eichner war der Polizei bereits bekannt.

###### Kreisleiter und Oberbürgermeister der Stadt Görlitz

 \
Durch den Befehl Nr. 201 der Sowjetischen Militäradministratur (SMAD)
wurde im August 1947 die Umsetzung der Entnazifizierung im Sinne der
Direktive Nr. 24 und Nr. 38 dem Dezernat K5 der Kriminalpolizei
übertragen. Die K5-Kommissariate bildeten ab 1949 den Kern der
Hauptverwaltung zum Schutz der Volkswirtschaft und legten zudem den
dokumentarischen Grundstock für das NS-Sonderarchiv des Ministeriums für
Staatssicherheit (MfS). Demzufolge sind die K5-Kommissariate ein
Vorläufer des MfS[^54]. Diese vermeintliche Randnotiz ist nicht
unerheblich für die Betrachtung des Verfahrens gegen die zwei
hauptschuldigen NS-Verbrecher in Görlitz. Gemeint ist der im Volksmund
bekannte Malitz-Meinshausen-Prozess gegen Dr. Bruno Erwin Fritz Malitz,
so der vollständige Name des ehemaligen NSDAP-Kreisleiters in Görlitz,
und gegen den ehemaligen Görlitzer Oberbürgermeister Dr. Hans Friedrich
August Meinshausen. Malitz und Meinshausen waren zwei von insgesamt
2.405 so genannten hauptschuldigen NS-Verbrechern, gegen die in der
Sowjetischen Besatzungszone zwischen September 1947 und Jahresende 1950
ermittelt wurde. Beide Beschuldigte waren jedoch zu Beginn der
Ermittlungen noch nicht in polizeilichem Gewahrsam[^55].

Malitz hatte Görlitz am späten Abend des 7. Mai 1945 verlassen und
flüchtete über Friedland (heute: Frydland, Tschechien), Teplitz-Schönau
(heute: Teplice, Tschechien) und Chemnitz nach Goslar im Harz[^56].
Unter Leugnung seiner Parteizugehörigkeit bekam er bereits am 26. Juli
desselben Jahres eine Stelle als Abteilungsleiter im Bremer
Ernährungsamt, die er bis zu seiner Ergreifung am 24.02.1947
behielt[^57]. Eine ehemalige Görlitzerin hatte ihn dort jedoch
wiedererkanntund bei der Polizei angezeigt, woraufhin Malitz in die
Sowjetische Besatzungszone ausgeliefert wurde.   Meinshausen saß indes
in einem Darmstädter Internierungslager ein und wurde auf Drängen der
Stadt Görlitz ausgeliefert. Laut dem damaligen Generalstaatsanwalt Rolf
Helm ist das der einzige Fall, in dem geflüchtete NS-Verbrecher aus der
westlichen Besatzungszone in die sowjetische Besatzungszone zur
Verurteilung überführt wurden[^58]. Die Hauptverhandlung der Großen
Strafkammer Görlitz (Bild  ) in der Sache Malitz-Meinshausen begann am
6. April 1948. Auf der Anklagebank saßen der Görlitzer Oberbürgermeister
Meinshausen und der NSDAP-Kreisleiter Malitz (Bild  ).

Sie wurden beschuldigt, die Sprengung von Neißebrücken, Wasserwerken und
Backöfen einen Tag vor Kriegsende veranlasst zu haben. Ferner
befehligten sie die Erschießung von Deserteuren, Zwangsarbeitern und
Kriegsgefangenen durch den Görlitzer Volkssturm (Werksvolkssturm WUMAG)
bis in die letzten Kriegstage hinein. Hinzu kommt die Anordnung zur
Erschießung des Leiters des Wirtschaftsamtes Breslau auf Weisung des
Gauleiters Hanke und vieles andere mehr. Maßgeblich schrieb man beiden
jedoch die Schuld für die Zwangsevakuierung der Görlitzer Bevölkerung
sowie des sogenannten Konzentrationslagers im Biesnitzer Grund zu.
trieben 70 000 Menschen ohne Verpflegung und Transport zwangsweise auf
die Landstraße. Viele Hunderte kamen um, Kinder wurden auf der Straße
geboren, Alte und Kranke wurden dem sicheren Tod übergeben[^59], heißt
es da in einem Zeitungsbericht[^60]. Malitz berief sich in seiner
Verteidigung hierbei auf eine Anordnung des stellvertretenden Gauleiters
Müller, welcher unter anderem die Evakuierung befohlen haben soll[^61].
Die Räumung des KZ-Außenlagers, führte Malitz an, sei auf Veranlassung
der WUMAG geschehen[^62]. Aufmerksamkeit erregte der Prozess nicht nur
in Görlitz, sondern dank einer weitreichenden Medienkampagne auch in der
gesamten sowjetischen Besatzungszone (Bild )[^63]. Der 2.000 Menschen
fassende Saal der Görlitzer Stadthalle diente als Verhandlungsort,
genügte jedoch kaum dem Andrang der interessierten Bevölkerung. Mittels
Lautsprecher konnte die Verhandlung auch auf Görlitzer Hauptstraßen
verfolgt werden[^64]. Strittig bleibt, in wie fern es sich hierbei um
ein faires Verfahren[^65] oder um einen Schauprozess handelte, dessen
Urteil, um einer öffentlichen und vor allem deutschlandweiten Blamage zu
entgehen, schon von vorn herein feststand.

Die beiden Angeklagten wurden zum Tode verurteilt. Das Strafmaß für
Meinshausen sei im Verhältnis zu Urteilen des Nürnberger Militärgerichts
nicht gerechtfertigt, hieß es im Revisionsantrag der Verteidigung. Die
Ankläger, unter der Leitung von Generalstaatsanwalt Dr. Rolf Helm,
definierten daraufhin ihre Auslegung der Verbrechen gegen die
Menschlichkeit, wonach ebendiese sich nicht allein auf körperliche
Mißhandlung beschränken, sondern die gesamte Tätigkeit des
Nationalsozialismus auf allen Lebensgebieten einbeziehen[^66]. Eben
diese Tätigkeit stand in Bezug auf das KZ-Außenlager jedoch in
Abhängigkeit mehrerer Instanzen, welche man zur Klärung der
Verantwortung für den Todesmarsch hätte heranziehen müssen. Die
Staatsanwaltschaft bemühte sich nicht, eine Auslieferung des
Lagerkommandanten oder des Generaldirektors der WUMAG zu erwirken.
Malitz und Meinshausen wurde die gesamte Verantwortung zugeschrieben, so
dass sich weitere Ermittlungen in der hier betreffenden Sache
erübrigten[^67].   Nachdem der Antrag auf Revision abgelehnt und das
Gericht am 24.04.1948 das Todesurteil fällte wurden Malitz und
Meinshausen nach Ablehnung der Gnadengesuche durch die sächsische
Staatsregierung am 19. Oktober 1948 in Dresden hingerichtet.   Alles mit
dem Prozess in Verbindung stehende Aktenmaterial[^68] nahm das MfS 1955
in Beschlag und stand fortan nur bedingt für gerichtliche und
historische Ermittlungen zur Verfügung. Das MfS sicherte sich diesen
Fundus zum Zwecke ihres operativen Geschäfts in der BRD und begegnete
Rechtshilfeersuchen seitens der westdeutschen Staatsanwaltschaften, wie
etwa in der Sache Rechenberg, nur äußerst selektiv und ausweichend.

  -- --
     
  -- --

  -- --
     
  -- --

[^1]: Mojzerz Boms aus Konstantwinov. Seine Urne kam bereits am
    24.05.1944 nach Groß-Rosen. FVG Einäscherungsregister 1944/45.

[^2]: Zwischen 1948 und 1950 wurden jene Urnen auf dem Jüdischen
    Friedhof beigesetzt.

[^3]: Dies wurde vielfach von Überlebenden bestätigt, so auch von Samuel
    Reifer, den dieses Schicksal fast ereilt hätte.

[^4]: Am 11. Februar 1945 stellte das Unternehmen aufgrund von
    Personalmangel den Betrieb ein und übergab das Geschäft dem
    Görlitzer Bestattungsunternehmen Ulrich.

[^5]: Janek Oborowicz. BStU MfS ASt 13/48 Bd. 2 / 472.

[^6]: Ernst Schubert, BStU MfS ASt 13/48 Bd. 2 / 546.

[^7]: Die Daten über die Sargauslieferungen zwischen dem 18.08.1944 und
    dem 02.02.1945 stellte mir freundlicherweise das
    Bestattungsunternehmen Ulrich, Obermarkt in Görlitz, zur Verfügung.

[^8]: Abram Rajchbart spricht von 57 Toten. ZIH 301/715. Ber Leib
    Toronczyk beruft sich auf 60 Tote. Diese Zahl soll bei einem Appell
    in Rennersdorf kurz nach der Ankunft durch Czech verkündet worden
    sein. LArchB B Rep 058 Bd. 4. Schlomo Graber sprach in Interviews im
    Jahre 2005 von 1.000 Todesopfern.

[^9]: Emmrich Schiffer war in der Lage detaillierte Angaben über
    Tötungen von Häftlingen zu machen, welche in anderen Quellen anhand
    von Namen und Häftlingsnummern Bestätigung fanden. PMGR 4702/14/DP.

[^10]: Laut Kurt Wolf, dem damals in der Sache ermittelnden
    Polizeikommissar der Kriminalpolizei Görlitz

[^11]: Aussage von Emmrich Schiffer. LArchB B Rep 058 Bd. 5.

[^12]: Vgl. Jakob Rosenbaum: Von Görlitz nach Tirol, S. .

[^13]: BStU MfS ASt 13/48 Bd. 2 / 417.

[^14]: Die genaue Grabstätte ist nicht bekannt.

[^15]: Laut Kurt Wolf lag der Tote direkt neben dem heute nicht mehr
    stehenden ersten Haus in Kunnerwitz. Interviews mit Kurt Wolf, Löbau
    2004-2010.

[^16]: Aussage von Otto Pfeffer. BStU MfS ASt 13/48 Bd. 2 / 476.

[^17]: Interview mit Kurt Wolf, Löbau 2005-10

[^18]: Vgl. Schlomo Graber: Schlajme. Vgl. auch Jakob Rosenbaum: Von
    Görlitz nach Tirol.

[^19]: BStU MfS ASt 13/48 Bd. 2 / 479.

[^20]: xxx Zusammenhang mit Euthanansieverbechen in Großschweidnitz
    klären.

[^21]: BStU MfS ASt 13/48 Bd. 2 / 481.

[^22]: BStU MfS ASt 13/48 Bd. 2 / 481.

[^23]: Laut Hinweisen von Ilse Gießler und Wolfgang Bittrich sowie
    einiger anderer Berthelsdorfer Bürger.

[^24]: Hildegard Fleischmann. BStU MfS ASt 13/48 Bd. 2 / 460.

[^25]: Robert Heinze: Ortschronik Rennersdorf. Dies stimmt mit der
    Aussage von Christa Schubert überein, deren Vater der
    Ausgrabungsaktion beiwohnen musste.

[^26]: Aussage von Christa Schubert, deren Bruder im Kindesalter bei den
    Ausgrabungen anwesend war.

[^27]: Edeltraud Bittrich. Interview vom 29.03.2004.

[^28]: BStU MfS ASt 13/48 Bd. 2 / 465.

[^29]: Laut Günter Scholze, der damals selbst mit Hand anlegen musste.
    Telefonisches Interview vom 29.03.2004.

[^30]: Das erklärt, warum die Fundstelle mit Stroh und Erde abgedeckt
    war.

[^31]: BStU MfS ASt 13/48 Bd. 2 / 465.

[^32]: BStU MfS ASt 13/48 Bd. 2 / 467.

[^33]: Franz Scholz wurde später wegen seines couragierten Eintretens
    für Kriegsgefangene zum Ehrenbürger der Stadt Görlitz ernannt.

[^34]: Einige Quellen berichten zudem vom Ausfall der Gasversorgung im
    Krematorium, dies konnte jedoch nicht weiter bestätigt werden.

[^35]: Laut Aussage von Kurt Wolf, welcher damals zusammen mit Kommissar
    Mellmann die Ausgrabungen auf dem Jüdischen Friedhof leitete.
    Interviews mit Kurt Wolf, Löbau 2005-10.

[^36]: Interview mit Anna Hyndráková, Prag 2005.

[^37]: Der Rapportführer sagte, dass vor einigen Tagen eine Ungarin
    beigesetzt wurde. Janek Oborowicz. BStU MfS ASt 13/48 Bd. 2 / 472.

[^38]: Juda Widawski. LArchB B Rep 058 Bd. 2. Siehe auch BStU MfS ASt
    13/48 Bd. 2 / 549.

[^39]: Kurt Wolf: Das KZ-Außenlager Görlitz Biesnitzer Grund, S. 23.

[^40]: Vgl. Peter Reichel: Vergangenheitsbewältigung in Deutschland, S.
    30. Siehe auch: Alexander Fischer (Hg.): Teheran -- Jalta --
    Potsdam. Die sowjetischen Protokolle von den Kriegskonferenzen der
    Großen Drei, S. 184f.

[^41]: Hinweis darauf geben Berichte über den Rennersdorfer
    Gutsverwalter Lehmann, den Fuhrparkleiter Anton Sedlak (Akten sind
    verschollen) sowie Männer des Wachpersonals. Vgl. BStU MfS ASt
    13/48.

[^42]: LArchB B Rep 058 Bd. 2.

[^43]: Ebenda.

[^44]: LArchB B Rep 058 Bd. 11.

[^45]: Prozess gegen Winfried Zunker, Az.: VII K 1613/48, VII 1614/48.
    Kriegsgericht Łódź.

[^46]: Laut Anna Hyndráková, die mit ihm flüchtete.

[^47]: Telefonisches Interview mit Monik Mlynarski vom 18.11.2004.

[^48]: PMGR 70/4593/MF.

[^49]: Prozess gegen Hermann Czech, Az.: VII K 1613/48, VII 1614/48.
    Kriegsgericht Łódź.

[^50]: Bekanntgabe des United States Department of Justice vom 12. Mai
    1987.

[^51]: Ebenda. Vgl. auch: Schlomo Graber: Schlajme, S. 82. Der Konflikt
    wurde 2003 von Jeffrey Sweet im Theaterstück The Action Against Sol
    Schumann thematisiert und am *Victory Gardens Theatre* Chicago
    uraufgeführt.

[^52]: ﻿David van Biema: Poisoned Lives.

[^53]: Landgericht oder Schwurgericht Hamburg 511106 (06.11.1951) Az.:
    (50) 13/51.

[^54]: Vgl. Henry Leide: NS-Verbrecher und Staatssicherheit.

[^55]: Ebenda

[^56]: BStU MfS ASt 13/48 Bd. 2 / 114 und 90.

[^57]: BStU MfS ASt 13/48 Bd. 2 / 114.

[^58]: Vgl. Rolf Helm: Anwalt des Volkes -- Erinnerungen. S. 170f.

[^59]: RAG, Sammlungsgut KZ Biesnitzer Grund

[^60]: Anklageschrift vom 29.02.1948 gegen den ehemaligen Kreisleiter
    der NSDAP Dr. Bruno Malitz und den ehemaligen Oberbürgermeister Dr.
    Hans Meinshausen. Aktenzeichen: 5-5-61/333/47/201. Privatbesitz des
    Autors.

[^61]: BStU MfS ASt 13/48 Bd. 2 / 170.

[^62]: BStU MfS ASt 13/48 Bd. 2 / 172.

[^63]: Das Prozessgeschehen dokumentierten unter anderem die Lausitzer
    Rundschau, die Märkische Union (Potsdam), Die Union (Dresden) und
    der Tagesspiegel (Berlin).

[^64]: Vgl. Rolf Helm: Anwalt des Volkes -- Erinnerungen. S. 170.

[^65]: Ein faires Verfahren gründet auf Waffengleichheit zwischen
    Staatsanwaltschaft und Beschuldigten, vgl. Creifelds
    Rechtswörterbuch, München 2007 (19. Auflage), S. 403, zitiert in
    Schmeitzner: Der Fall Mutschmann, S129f. Anforderungen an einen
    fairen Prozess: a) menschenwürdige Voruntersuchung (d.h. ohne
    Folter), b) Zulassung von Strafverteidigern (Wahl- bzw.
    Pflichtverteidigern), c) Zulassung von Zeugen der Verteidigung, d)
    Zulassung der Öffentlichkeit, e) Anwenden von Rechtsgrundlagen, die
    den tatvorwürfen entsprechen, f) Unabhängigkeit der Richter (vor
    allem von politisch-ideologischen Vorgaben), g) Individueller
    Schuldnachweis, h) zeitlich angemessener Verfahrensablauf, i)
    Anwendung eines Strafmaßes, was der Tat angemessen erscheint, j)
    Berufungsungs- und Begnadigungsrecht.

[^66]: Entsprechend der Bestimmungen des Kontrollratsgesetzes Nr. 10.

[^67]: Ausgenommen hiervon: Gerhardt Anton Sedlak, der Fuhrparkleiter
    der WUMAG, den man aufgrund der Mißhandlungen, die er an Häftlingen
    verübte, zu acht Jahren Gefängnis verurteilte. Sedlak schwärzte
    Häftlinge an, die sich Schweinefutter aus den Kübeln der WUMAG
    holten. LG/BG Bautzen 480626 Az.: 9a/ StKs16/48, OLG Dresden Az.:
    21ERKs221/48 (Akten sind verschollen).\
    Rudolf Müller verurteilte man zu drei Jahren Haft wegen
    Misshandlungen von Häftlingen in seiner Funktion als Meister in der
    WUMAG. LG/NG Bautzen 480117 Az.: 9a/StKs6/7.\
    Diese Akten sind ebenfalls nicht mehr auffindbar.

[^68]: Laut Aussage von Kurt Wolf (Löbau, 06.02.2009) umfasste das
    Material 12 Akten mit je zwei Leitzordnern.
