## Namen von Todesopfern

::: tiny
  ----------------------- ------------- -------- ------------------ --------------- ------------ -------------- -------------- ----------- ------------
                                                                                                                                           
  Name                    Vorname         Nummer       Nation         Geburtsort         geboren      gestorben   Einäscherung  Urnenhain    Groß Rosen
                                                                                                                                           
  Zielinski               Withold              ?       Polen           Warschau        5.05.1923              ?      3.08.1944     --        06.09.1944
  Wjzecz                  Boms                 ?         ?           Konstantwinow    14.04.1913              ?     16.05.1944     --        24.05.1944
  Romanowski              Waclav            4969         ?                 ?           8.12.1923           1944     26.08.1944     --        06.09.1944
  Schweiger               Jew              14176         ?                 ?                   ?           1944     26.08.1944     --        06.09.1944
  Stodolski               ?                 5868         ?                 ?          21.08.1921     20.08.1944     24.08.1944     --        07.09.1944
  Wasiak                  Edward            5810         ?                 ?          18.08.1907     21.08.1944     24.08.1944     --        06.09.1944
  Sobolenski              Wlagslav          5040         ?                 ?          20.03.1911     21.08.1944     24.08.1944     --        07.09.1944
  Usci                    Josef             5074         ?                 ?           3.09.1910     21.08.1944     24.08.1944     --        07.09.1944
  Bobek                   Antonie           6215       Polen               ?          10.10.1911     26.08.1944     29.08.1944     --        06.09.1944
  Stefan                  Jamucz           27802       Polen               ?           2.09.1911      3.09.1944      4.09.1944     --        12.09.1944
  Kochan                  Aron             24236       Polen               ?          28.06.1924      3.09.1944      6.09.1944     --        15.09.1944
  Drenger                 Meier            24841       Polen               ?          21.08.1901      4.09.1944     16.09.1944     --        15.09.1944
  Goldwasser              David            24533       Polen               ?           2.08.1914      7.09.1944      9.09.1944     --        20.09.1944
  Strum                   Moses            25711       Polen               ?           3.01.1904      7.09.1944      9.09.1944     --        20.09.1944
  Groß                    Abraham          42657       Ungarn              ?          10.09.1918      7.09.1944     12.09.1944     --        20.09.1944
  Meitelis                Jakob            25282       Polen           Sosnowitz      20.01.1909     17.09.1944     21.09.1944     --        29.09.1944
  Karp                    David            24770       Polen            Krenau        13.02.1909     19.09.1944     21.09.1944     --        29.09.1944
  Malinowitzer            Alter            25056       Polen           Sosnowitz      26.05.1911     19.09.1944     21.09.1944     --        29.09.1944
  Günbaum                 Jakob            24589       Polen           Sosnowitz      29.05.1892     20.09.1944     23.09.1944     --        02.10.1944
  Granek                  Samuel           24553       Polen           Sosnowitz      19.12.1923     22.09.1944     23.09.1944     --        02.10.1944
  Braun                   Moritz           42546       Ungarn              ?          21.10.1896     25.09.1944     30.09.1944     --        05.10.1944
  Kopel                   Moczek           56853         ?                 ?           9.05.1908     28.09.1944     30.09.1944     --        05.10.1944
  Rejder                  Wolf             56966         ?                 ?          24.02.1923     29.09.1944     30.09.1944     --        05.10.1944
  Parlowski               Ignac            56963         ?                 ?          30.10.1910      2.10.1944      6.10.1944     --        11.10.1944
  Grynberg                Szymal           57082         ?                 ?          14.06.1895      3.10.1944      6.10.1944     --        11.10.1944
  Linker                  Hersch           25016       Polen            Krenau        14.01.1909      7.10.1944     10.10.1944     --        11.10.1944
  Klimek                  Boleslav          4779         ?              Gulbari       25.02.1913     10.10.1944     31.10.1944     --                 ?
  Fried                   Samuel           42616       Ungarn              ?           5.10.1886     11.10.1944     27.10.1944  XIII b/1              ?
  Werder                  Mordka           56892         ?                 ?          22.12.1896     12.10.1944     27.10.1944  XIII b/1              ?
  Rusinek                 Josef            25395       Polen               ?          25.10.1920     12.10.1944     27.10.1944  XIII b/2              ?
  Hostrig (oder Hostig)   Abram            57100         ?                 ?              2.12.0     13.10.1944      1.11.1944  XIII b/4              ?
  Schlesinger             Adolf            14162         ?                 ?          22.09.1895     14.10.1944     27.10.1944  XIII b/2              ?
  Geldhammer              Chana                ?         ?                 ?          19.10.1923     16.10.1944      1.11.1944  XIII b/3              ?
  Karz                    Jonas            57113         ?                 ?          20.01.1906     17.10.1944     27.10.1944  XIII b/3              ?
  Tannenberg              Wolf             25730       Polen          Kozinglowy       2.04.1918     19.10.1944      1.11.1944  XIII b/4              ?
  Weber                   Pesach           25891       Polen         Witzmannstadt     7.09.1901     22.10.1944      1.11.1944  XIII b/5              ?
  Glückner                Josef            57074         ?                 ?          31.03.1901     22.10.1944      1.11.1944  XIII b/6              ?
  Levkowicz               David            56949         ?                 ?           1.07.1912     24.10.1944      1.11.1944  XIII b/5              ?
  Sokowicz                Valerian          2356         ?                 ?           6.01.1906     25.10.1944     31.10.1944     --                 ?
                                                                                                                                           
  Name                    Vorname         Nummer       Nation         Geburtsort      geboren am   gestorben am   Einäscherung  Urnenhain    Groß Rosen
                                                                                                                                           
  Friedmann               Chil             57063         ?                 ?           3.08.1904     27.10.1944      7.11.1944  XIII b/6              ?
  Honig                   Israel           42707       Ungarn              ?          15.01.1892     27.10.1944      7.11.1944  XIII b/7              ?
  Dormitz                 Moses            24231    Niederlande        Amsterdam       7.06.1908      2.11.1944     13.11.1944  XIII b/9              ?
  Wonermann               Isak             25846       Polen           Warthenau      24.04.1914      2.11.1944     13.11.1944  XIII b/9              ?
  Novowico                Rudolf           42710       Ungarn              ?          17.10.1926      3.11.1944     13.11.1944  XIII b/7              ?
  Glodny                  Meier            24479       Polen            Modrow                 ?      3.11.1944     13.11.1944  XIII b/8              ?
  Adler                   Jakob            12971         ?              Houszt        15.08.1895      4.11.1944     13.11.1944  XIII b/8              ?
  Genad                   Arnold           13206         ?            Vesarosnemy      7.05.1928      6.11.1944     22.11.1944  XIII b/10             ?
  Faktor                  Schaja           24282       Polen           Warthenau      10.05.1906      9.11.1944     22.11.1944  XIII b/11             ?
  Tarner                  Jonas            57236         ?                 ?          20.07.1899     14.11.1944     22.11.1944  XIII b/10             ?
  Teßler                  Israel           42967       Ungarn              ?          17.07.1897     15.11.1944      1.12.1944  XIII b/11             ?
  Kollar                  Karl             65008  Tschechoslowakei      Budweis        2.12.1887     15.11.1944     21.11.1944     --        01.12.1944
  Schenitzki              Hersch           25642       Polen           Sosnowitz      20.01.1925     18.11.1944      1.12.1944  XIII b/12             ?
  Willner                 Benjamin         57251         ?                 ?          22.09.1899     18.11.1944      1.12.1944  XIII b/12             ?
  Rottenberg              Emil             14057         ?           Nagybuttervek    25.10.1884     19.11.1944     21.11.2019  XIII b/13             ?
  Scheiner                Isidor           14130         ?            Nagy Basko       2.04.1895     21.11.1944      5.12.1944  XIII b/13             ?
  Friedrich               Simon            24400       Polen           Dombrowa       29.08.1905     24.11.1944      5.12.1944  XIII b/14             ?
  Taus Mandelholz         David            25719       Polen            Krenau        13.02.1901     25.11.1944      5.12.1944  XIII b/14             ?
  Grünwald                Emil             13280         ?              Kaschan       28.00.1927     30.11.1944      5.12.1944  XIII b/15             ?
  Goldkrauz               Aron             56832         ?                 ?           2.01.1895      1.12.1944      7.12.1944  XIII b/15             ?
  Nemeti                  Moritz           13866         ?             Nirmegysz      22.11.1894      2.12.1944      7.12.1944  XIII b/16             ?
  Steinberg               Abraham          14300         ?                 ?          23.02.1900      2.12.1944      7.12.1944  XIII b/16             ?
  Hornung                 Moses Isack      24691       Polen           Oświęcim       17.12.1896      4.12.1944      7.12.1944  XIII b/17             ?
  Zimhowdzki              Jakob            25942       Polen            Krenau        16.10.1911      4.12.1944      7.12.1944  XIII b/17             ?
  Klein                   Szlojan          56936         ?                 ?           8.05.1896      5.12.1944     14.12.1944  XIII b/20             ?
  Marokko                 David            56956         ?                 ?          14.03.1904      6.12.1944     14.12.1944  XIII b/18             ?
  Piarkarski              Ekinzier         25195       Polen           Bendsburg       8.11.1922      6.12.1944     14.12.1944  XIII b/19             ?
  Müller                  Hermann          42811       Ungarn              ?          13.08.1900      7.12.1944     14.12.1944  XIII b/19             ?
  Redlich                 Henoy            57193         ?                 ?          26.01.1911      7.12.1944     14.12.1944  XIII b/20             ?
  Freukiel                Pinkus           24378       Polen           Sosnowitz      25.07.1910      8.12.1944     14.12.1944  XIII b/18             ?
  Gersztynowietz          Synche           56918         ?                 ?          26.05.1910      8.12.1944     14.12.1944  XIII b/21             ?
  Zelig (Rabbi)           Mozes            42901       Ungarn              ?          10.04.1887     10.12.1944     14.12.1944  XIII b/21             ?
  Zipser                  Argard           42925       Ungarn              ?           6.09.1890     10.12.1944     14.12.1944  XIII b/22             ?
  Lewkowiecz              Lobe             24989       Polen               ?          29.06.1909     11.12.1944     14.12.1944  XIII b/22             ?
  Wochila                 Hersz            14049         ?                 ?          28.05.1899     11.12.1944     14.12.1944  XIII b/23             ?
  Neumann                 Emil             42815       Ungarn              ?          20.08.1901     14.12.1944     19.12.1944  XIII b/23             ?
  Gutter                  Jonas            24618       Polen               ?          19.07.1903     14.12.1944     19.12.1944  XIII b/24             ?
  Müller                  Samuel           13844         ?                 ?          15.04.1896     15.12.1944     19.12.1944  XIII b/24             ?
  Schwarz                 Hermann          14198         ?                 ?          12.02.1904     19.12.1944     22.12.1944  XIII b/25             ?
  Bren                    David            57026         ?                 ?          17.10.1921     19.12.1944     22.12.1944  XIII b/25             ?
  Weiser                  Chain            57247         ?                 ?           6.05.1900     19.12.1944     22.12.1944  XIII b/26             ?
  Berkowicz               Israel           57012         ?                 ?           7.06.1912     22.12.1944     24.12.1944  XIII b/26             ?
  Paluch                  Pinkus           25175       Polen               ?          18.01.1904     26.12.1944      4.01.1945  XIII b/27             ?
  Schöngut                Emanuel          25583       Polen               ?          17.05.1908     26.12.1944      4.01.1945  XIII b/27             ?
  Rzecszewski             Nusyn            25398       Polen               ?           2.06.1912     27.12.1944      4.01.1945  XIII b/28             ?
  Halpert                 Ignatz           42674       Ungarn              ?          14.05.1922     27.12.1944      4.01.1945  XIII b/28             ?
  Seidemann               Chaim            57208         ?                 ?          14.06.1908     27.12.1944      4.01.1945  XIII b/29             ?
  Napasteck               Szlama           56861         ?                 ?           8.02.1918     27.12.1944      4.01.1945  XIII b/29             ?
  Tennenbaum              Israel           25726       Polen               ?           5.11.1907     28.12.1944      4.01.1945  XIII b/30             ?
                                                                                                                                           
  Name                    Vorname         Nummer       Nation         Geburtsort      geboren am   gestorben am   Einäscherung  Urnenhain    Groß Rosen
                                                                                                                                           
  Rosenzweig              Rubin            25359       Polen               ?          22.09.1913     28.12.1944      4.01.1945  XIII b/30             ?
  Friedmann               Izak             56917         ?                 ?          14.07.1908     28.12.1944      4.01.1945  XIII b/31             ?
  Jurista                 Meiner           24573       Polen               ?          11.10.1909     30.12.1944      4.01.1945  XIII b/31             ?
  Goldminz                David            56923         ?                 ?          24.09.1914     30.12.1944      4.01.1945  XIII b/32             ?
  Wrondanski              Abram            57256         ?                 ?           5.09.1902      2.01.1945     18.01.1945  XIII b/35             ?
  Tyler                   Jakob            56888         ?            Lentschitz      28.12.1893      3.01.1945     18.01.1945  XIII b/32             ?
  Rosenfeld               Samuel           14021         ?                 ?          30.06.1920      4.01.1945     18.01.1945  XIII b/33             ?
  Zuchter                 Sincha           25953       Polen               ?                   ?      6.01.1945     18.01.1945  XIII b/33             ?
  Kleinmann               Jankel           24820       Polen               ?          26.05.1926      6.01.1945     18.01.1945  XIII b/34             ?
  Heliasz                 Zoltau           42684       Ungarn              ?           1.08.1896      8.01.1945     18.01.1945  XIII b/34             ?
  Bokik                   Israel           57181         ?                 ?          15.11.1900      8.01.1945     18.01.1945  XIII b/35             ?
  Schwalb                 Alfred           14185         ?                 ?          21.08.1901      9.01.1945     18.01.1945  XIII b/36             ?
  Najar                   Jankiel          25117       Polen               ?          26.11.1907      9.01.1945     18.01.1945  XIII b/37             ?
  Stark                   Schmul           25679       Polen               ?          10.01.1924      9.01.1945     18.01.1945  XIII b/38             ?
  Lekowicz                Israel           57133         ?                 ?           2.09.1905     10.01.1945     18.01.1945  XIII b/36             ?
  Salomon                 Manfred          57206         ?                 ?          21.08.1917     10.01.1945     18.01.1945  XIII b/37             ?
  Kruhl                   Rassel           57185         ?                 ?          27.06.1909     12.01.1945      6.02.1945  XIII b/39             ?
  Braun                   Abraham          24148       Polen               ?          13.06.1909     12.01.1945      6.02.1945  XIII b/39             ?
  Schlesinger             Josef            14165         ?                 ?          15.12.1879     13.01.1945      6.02.1945  XIII b/38             ?
  Rosensaft               Moszak           25350       Polen               ?           5.04.1919     13.01.1945      6.02.1945  XIII b/40             ?
  Laufer                  Salomon          24948       Polen               ?          18.03.1907     15.01.1945      6.02.1945  XIII b/40             ?
  Szanto                  Jakob            42976       Ungarn              ?           3.03.1902     17.01.1945      6.02.1945  XIII b/41             ?
  Safer                   ?                14080         ?                 ?          15.03.1923     17.01.1945      6.02.1945  XIII b/41             ?
  Rembiszewski            Chaim            25443       Polen               ?          14.04.1901     17.01.1945      6.02.1945  XIII b/42             ?
  Segal                   Josef            56978         ?                 ?          25.10.1908     19.01.1945      8.02.1945  XIII b/42             ?
  Königsberg              Schlama          24857       Polen               ?          11.07.1911     19.01.1945      8.02.1945  XIII b/43             ?
  Goldberg                Zajinvel         57273         ?                 ?          10.05.1901     19.01.1945      8.02.1945  XIII b/43             ?
  Goldstein               Oskar            42639       Ungarn              ?          24.06.1924     19.01.1945      8.02.1945  XIII b/44             ?
  Schlesinger             Moschek          25555       Polen               ?          10.10.1923     21.01.1945      8.02.1945  XIII b/44             ?
  Goldberg                Jakob            57075         ?                 ?          26.07.1902     22.01.1945      8.02.1945  XIII b/45             ?
  Kritzmann               Abraham          57282         ?                 ?          15.01.1906     22.01.1945      8.02.1945  XIII b/45             ?
  Kolf                    Meylesch         56939         ?                 ?           5.10.1899     22.01.1945      8.02.1945  XIII b/46             ?
  Krakowski               Szlama           24890       Polen               ?          15.02.1919     22.01.1945      8.02.1945  XIII b/46             ?
  Silberstein             Hermann          56982         ?                 ?           9.02.1900     22.01.1945      8.02.1945  XIII b/47             ?
  Heinmann                Benno            24644       Polen               ?           8.11.1910     22.01.1945      8.02.1945  XIII b/47             ?
  Herz                    Josef            42696       Ungarn              ?          16.09.1925     22.01.1945      8.02.1945  XIII b/48             ?
  Rosengarten             Saul             57201         ?                 ?          29.09.1912     25.01.1945      8.02.1945  XIII b/48             ?
  Kimmelmann              Meier            24794       Polen               ?          28.09.1900     25.01.1945     12.02.1945  XIII b/49             ?
  Korn                    Abram            56945         ?                 ?          20.12.1909     25.01.1945     12.02.1954      ?                 ?
  Klink                   Josef            24830       Polen               ?          30.08.1921     26.01.1945     12.02.1945  XIII b/50             ?
  Peses                   Chil             57171         ?                 ?           7.05.1905     26.01.1945     12.02.1945  XIII b/50             ?
  Schenkowitz             Simon            14143         ?                 ?           9.02.1902     27.01.1945     12.02.1945  XIII b/51             ?
  Treimann                Nuchim           25747       Polen               ?          20.01.1908     27.01.1945     12.02.1945  XIII b/51             ?
  Genat                   Eliasz           13208         ?                 ?          20.09.1897     30.01.1945     12.02.1945  XIII b/52             ?
  Neuwohner               Salomon          13892         ?                 ?           1.11.1927     30.01.1945     12.02.1945  XIII b/52             ?
  Mandelzwaig             Adam             57146         ?                 ?           3.09.1922     31.01.1945     12.02.1945  XIII b/53             ?
  Rottenberg              Niklas           42852       Ungarn              ?          17.09.1926     31.01.1945     12.02.1945  XIII b/53             ?
                                                                                                                                           
  Name                    Vorname         Nummer       Nation         Geburtsort      geboren am   gestorben am   Einäscherung  Urnenhain    Groß Rosen
                                                                                                                                           
  Fiscewciz               Wolf             57269         ?                 ?          25.03.1891     31.01.1945      2.05.2019  XIII b/53             ?
  Schloss                 Oskar            25556       Polen               ?          26.10.1922     31.01.1945     12.02.1945  XIII b/54             ?
  Ensel                   Szaja            24276       Polen               ?          10.12.1913      2.02.1945     12.02.1945  XIII b/56             ?
  Klug                    Juda             12738         ?                 ?           8.08.1906     31.01.1945     12.02.1945  XIII b/55             ?
  Zicker                  Pinkus           25955       Polen               ?           9.07.1913      2.02.1945     12.02.1945  XIII b/55             ?
  Brückner                Jacob            24170       Polen               ?          15.05.1926      2.02.1945     12.02.1945  XIII b/56             ?
  Hostig                  Abush                ?       Polen             Lodz                  ?              ?              ?      ?                 ?
  Hostig                  Joel                 ?       Polen             Lodz                  ?        02.1945              ?      ?                 ?
  ----------------------- ------------- -------- ------------------ --------------- ------------ -------------- -------------- ----------- ------------

  : (Fortsetzung)
:::

## Namen der ermittelten Überlebenden

::: tiny
  ---------------------------------- --------------------------- ------------ ----------------------- ------------------ ------------------
                                                                                                                         
  Name                               Vorname                       geboren am Geburtsort              Geb.-Nat.          Emmigration 
                                                                                                                         
    Adler                            Joseph                        04.05.1930 Dubová                  Tschechoslowakei   ?
  Adler                              Shraga                        15.09.1932 Kisvarda                Ungarn             ?
  Agnes                              Rona                                1929 Budapest                Ungarn             Ungarn
  Altmann                            Tuwia                         26.07.1930 Łódź                    Polen              Israel
  Axelrod                            Yolanda                       08.08.1920 Porumbesti              Rumänien           ?
  Baum                               Jehuda                        10.04.1900 Piotrków Trybunalski    Polen              Israel
  Beale                              Mendel                        24.12.1921 Sompolno                Polen              ?
  Ben                                Menachem (Pritz)              10.04.1922 Kielce                  Polen              Israel
  Ben-Shlomo                         Miriam                        07.08.1927 Kielce                  Polen              ?
  Benedykt                           Hela                          02.02.1923 Jaworzno                Polen              ?
  Benjamins                          Mozes                         21.06.1917 Rotterdam               Niederlande        ?
  Bennett                            Robert                        15.03.1933 Danzig                  Danzig             ?
  Berger                             Alice                                  ? Budapest                Ungarn             ?
  Bergman                            Schyja                        11.04.1906 Bobowa                  Polen              ?
  Berkowitz                          Hela                          16.03.1926 Trzebinia               Polen              ?
  Berkowits                          Hersi                         10.01.1924 Viseul-de-Mijloc        Rumänien           ?
  Birnbaum                           Mulek                         15.05.1912 ?                       ?                  Schweden
  Blum                               Ann                           15.03.1928 Chrzanów                Polen              ?
  Borenstein                         Charles                       05.07.1924 Łódź                    Polen              ?
  Borenstein                         Paul                          25.10.1927 Bedzin                  Polen              ?
  Bornstein                          Ignatz                              1900 ?                       ?                  BRD
  Brandt                             Isidor (früher Izek)          16.04.1908 Łódź                    Polen              USA
  Brandt                             Maximilian                    22.06.1915 Poznań                  Polen              Israel
  Braun                              Israel                        23.08.1924 Wartenau                Deutschland        USA
  Burger                             Alice                         06.03.1925 Budapest                Ungarn             ?
  Bürger                             Max                           18.08.1883 Görlitz                 Deutschland        BRD
  Drori                              Ya'akóv                       13.01.1920 Łódź                    Polen              ?
  Ehrnstein                          Eva                           24.10.1924 Penászlek               Ungarn             ?
  Eisenbaum                          Morris                        28.02.1928 Łódź                    Polen              ?
  Elefant                            Anna                          12.04.1921 Satu Mare               Rumänien           ?
  Erdos                              Magda                         10.10.1927 Satu Mare               Rumänien           ?
  Chaimovitz                         Esther                        28.10.1927                                            ?
  Cherston                           Mark                          18.06.1915 Łódź                    Polen              ?
  Czapnik Talesmann                  Isidor                        13.02.1917 Breslau                 Deutschland        Uruguay
  Czech                              Hermann                       27.10.1893 Oppeln                  Deutschland        Polen
  Dalezmann                          Abram                         25.08.1915 Sosnowice               Polen              USA
  Daskal                             Ester                         15.12.1918 Batarci                 Rumänien           ?
  Davidovits                         Eugene                        28.01.1930 Satu Mare               Rumänien           ?
                                                                                                                         
  Name                               Vorname                       geboren am Geburtsort              Geb.-Nat.          Emmigration 
                                                                                                                         
  Dial                               Max                           01.06.1922 Czestochowa             Polen              ?
  Eichner                            Adolf                         10.05.1922 Bukarest                Rumänien           Deutschland
  Elihai                             Yosef                               1928 Łódź                    Polen              ?
  Faiman                             Dora                          18.05.1919 Krakau                  Polen              ?
  Fajtlowicz                         Chalom                        07.05.1913 Łódź                    Polen              ?
  Faragó                             Klára                         25.04.1921 Kiskunfálegyháza        Ungarn             ?
  Federman                           Wolf                          15.05.1910                                            ?
  Feffermatz                         Jean                          24.12.1920 Bedzin                  Polen              ?
  Feigenblatt                        Anna                          25.02.1928 Strzemieszyce Wielkie   Polen              USA
  Feigenblat                         Isak                          03.05.1909 Zawiercie               Polen              USA
  Feigenblatt                        Henry                         10.11.1914 Szczekociny             Polen              ?
  Feiger                             Walter                        08.09.1927 Krakau                  Polen              ?
  Feld                               Yehudah                       12.06.1927 Bedzin                  Polen              ?
  Feldmann                           Dora                          20.11.1925 Olkusz                  Polen              ?
  Fenster                            Leon                          24.06.1912 Łódź                    Polen              Israel
  Ferlzmeier                         Sara                                   ? ?                       ?                  ?
  Ferson                             Alexander                     03.05.1918 Bedzin                  Polen              ?
  Finkel                             Cesia                         14.08.1928 Strzemieszyce           Polen              ?
  Finkelstein                        Haim                                1925 Chorzów                 Polen              ?
  Fiszlewicz                         Szymon                        01.12.1921 Radomsko                Polen              Israel
  Flajser (Fleischer)                Lili                          13.06.1924 Bajmok                  Jugoslawien        ?
  Fleiner                            Magda                               1800 Budapest                Ungarn             ?
  Frajman                            Jisrael David                 10.12.1897 Zduńska Wola            Polen              Isreal
  Frank                              Elizabeth                     23.04.1924 Madaras                 Rumänien           ?
  Frankel                            Samuel                        02.07.1923 Łódź                    Polen              ?
  Freund                             Nathan                        21.07.1928 Satu Mare               Rumänien           ?
  Frush                              Tova                          01.01.1910 Zloczew                 Polen              ?
  Gitler                             Zalman                        31.05.1919 Bedzin                  Polen              ?
  Glass ($\leadsto$ Posener)         Hirsch David                  17.05.1912 Chrzanow                Polen              USA
  Glattstein                         Channa                        24.12.1924 Chust                   Tschechoslowakei   ?
  Gleitmann                          Josef                         06.04.1913 Nutenberg               Polen              BRD
  Gráber                             Shlomo                        13.07.1926 Majdan                  Tschechoslowakei   Schweiz
  Gráber                             Mózes                         17.12.1903 Nyírgyulaj              Ungarn             Israel
  Grad ($\leadsto$ Citron)           Margarowicz Maria             13.09.1919 Brzezany                Polen              USA
  Granek                             Benek                         07.09.1917 Krzepice/Czestochowa    Polen              ?
  Grant                              Murray                        16.01.1925 Dabrowa Górnicza        Polen              ?
  Grünwald/Greenfield                Aron                          17.07.1926 Dukla                   Polen              ?
  Grünwald                           Israel                                 ? Dukla                   ?                  ?
  Grinfeld                           Tsiporah                      05.05.1920 Lipca                   Tschechoslowakei   ?
  Gross                              Joseph                        07.03.1927 Nyírbátor               Ungarn             ?
  Grünwald                           Leon                                   ? ?                       ?                  ?
  Guterman                           David                                  ? ?                       ?                  ?
  Guterman Slivka                    Brenda                        29.06.1916 Strzemieszyce Wielkie   Polen              ?
  Gutlev                             Haim Shlomo                         1926 Nagykároly              Rumänien           ?
  Gutlev                             Martin                                 ? ?                       ?                  ?
  Hartstein                          Edward                        17.07.1927 Zalau                   Rumänien           ?
  Harvey                             Alfred                        15.09.1925 Bedzin                  Polen              ?
  Harvey                             Joseph                        20.06.1919 Bedzin                  Polen              ?
  Haut                               Henry                         25.04.1925 Łódź                    Polen              ?
                                                                                                                         
  Name                               Vorname                       geboren am Geburtsort              Geb.-Nat.          Emmigration 
                                                                                                                         
  Helman                             John                          20.07.1909 Łódź                    Polen              ?
  Hirsch ($\leadsto$ Silbering)      Harry                               1800 Łódź                    Polen              USA
  Hoffman                            Alexander                     14.07.1924 Huszt                   Ungarn             ?
  Hostig (57102)                     Leon                          01.11.1919 Łódź                    Polen              USA
  Horowitz                           Fela                          20.08.1920 Strzemieszyce Wielkie   Polen              USA
  Horowitz                           Mayer                               1800 ?                       ?                  USA
  Hyndráková                         Anna                          25.03.1928 Prag                    Tschechoslowakei   Tschechien
  Jackson                            Abraham                       14.05.1927 Łódź                    Polen              ?
  Jacowitz                           Edward                        08.03.1916 Łódź                    Polen              ?
  Jakobson, Dr.                      Miczyslaw                     22.04.1894 Warschau                Polen              Israel
  Kabran                             Paulette                      07.04.1918 Przyrów                 Polen              ?
  Kala                               Haia                                   ? Nyírmada                Ungarn             ?
  Kalman                             Nathan                        15.10.1909 Łódź                    Polen              ?
  Kalman                             Rosner                              1924 Szchechova              ?                  ?
  Katz                               David                         08.03.1922 Chust                   Tschechoslowakei   USA
  Kessler                            Samuel                        21.02.1912 Köln                    Deutschland        BRD
  Kielstein                          Efrain                        07.04.1925 Hindenburg              Deutschland        Israel
  Kinrus, Dr.                        Jakob                         11.12.1910 Łódź                    Polen              Israel
  Klajman                            Natan                               1924 Berlin                  Deutschland        ?
  Klayn                              Magdah                        02.01.1929 Nyírmada                Ungarn             ?
  Klein                              Anna                          24.05.1920 Bölcske                 Ungarn             ?
  Klein                              Helen                                  ? ?                       ?                  ?
  Klein                              Lawrence                      04.01.1928 Nyírbátor               Ungarn             ?
  Kleinman                           Natan                         19.06.1924                                            ?
  Koenigstein                        Harry                         06.06.1929                                            ?
  Kopelman                           Simhah Bunim                  01.01.1911 Warschau                Polen              ?
  Kozusarz                           Mordko                        08.04.1925 Łódź                    Polen              Israel
  Krakauer                           Aron                          08.05.1911 Jaworzno                Polen              BRD
  Krongold                           Henoch                        21.11.1927 Łódź                    Polen              ?
  Kérn                               Avraham                       17.08.1912 Bircza                  Polen              ?
  Kuczynski                          Hersz                         28.11.1907 Babiak                  Polen              Kanada
  Langer                             Abraham                       19.06.1916 Chrzanów                Polen              ?
  Langer                             Emanuel                       21.03.1894 Gleiwitz                Deutschland        BRD
  Lebovic                            Mayer                         03.07.1925 Uhla                    Tschechoslowakei   ?
  Lebovits                           Lili                          05.11.1922 Lazuri                  Rumänien           ?
  Lee                                Barbara                       15.01.1925 Chrzanów                Polen              ?
  Lestovzki                          Rahel                                  ? ?                       ?                  ?
  Levi                               Dov                           20.08.1914 Przedbusz               Polen              Israel
  Levi                               Paul                          09.09.1905 Łódź                    Polen              BRD
  Lifshitz                           å«aharon                      24.08.1925 Strzemieszyce Wielkie   Polen              ?
  Linenberg                          Hersz                         10.11.1910 Gniwoszow               Polen              USA
  Lindenfeld                         Desiderio                     02.03.1919 Satu Mare               Rumänien           ?
  Lipschutz                          Abraham                       22.11.1919 Wielun                  Polen              ?
  Lipschutz                          Judith                        11.12.1926 Valea-lui-Mihai         Rumänien           ?
  Mącznik                            Ben                           25.12.1912 Łódź                    Polen              USA
  Mącznik                            Shlomo                                 ? Łódź                    Polen              USA
  Mandelbaum                         Roman                         06.02.1923 Chrzanów                Polen              BRD
  Mandelbaum                         Samuel                        03.02.1928 Chrzanów                Polen              BRD
                                                                                                                         
  Name                               Vorname                       geboren am Geburtsort              Geb.-Nat.          Emmigration 
                                                                                                                         
  Manelah                            Shlomoh                       19.04.1926 Zawiercie               Polen              ?
  Markowicz                          Toska                         22.11.1922 Strzekoczin             Polen              Israel
  Matyas                             Tibor                         25.05.1925 Reteag                  Rumänien           ?
  Maurer                             Irving                        12.06.1924 Przemysl                Polen              ?
  Menahem                            Arie Ben                            1922 Łódź                    Polen              ?
  Meiyer                             Helmann                                ? ?                       ?                  
  Miller                             Josef                         16.04.1920 Łódź                    Polen              Israel
  Milstein                           Sam                           15.03.1923 Sosnowiec               Polen              ?
  Minski                             Jacob                         25.11.1907 Zürich                  staatenlos         ?
  Miodownik                          Roman                         07.04.1921 Sosnowiec               Polen              Argentinien
  Mitchley                           Halina (Lusia)                23.11.1920 Warsaw                  Polen              ?
  Moskowiz                           Nandor                        21.01.1931 Kisvárda                Ungarn             ?
  Muller                             Irene                         13.07.1926 Tiszabercel             Ungarn             ?
  Nachman                            Avnon                               1928 Nyírlugos               Ungarn             ?
  Nechuschtan                        David                         10.04.1927 Łódź                    Polen              Israel
  Neubauer                           Mozes                                  ? Mátészalka              Ungarn             ?
  Neumark                            Samuel                        15.07.1907 Łódź                    Polen              USA
  Neuwohner                          David                         10.03.1930 Chust                   Tschechoslowakei   ?
  Niuvitz                            Zvi                                    ? Bixad                   Rumänien           ?
  Nudelman                           Sol                           10.11.1926 Wolbrom                 Polen              ?
  Oborowicz                          Janusch                       25.05.1923 Breslau                 Deutschland        DDR
  Okrent                             Nusen                         21.05.1906 Łódź                    Polen              ?
  Peper Metz                         Eugenia                             1915 Torenhajm               Polen              ?
  Perle                              Bendet                        22.02.1926 Pabianice               Polen              USA
  Peri                               Yitshák                       07.06.1927 Târgu Mureş             Rumänien           ?
  Pesses                             Max                           03.03.1912 Łódź                    Polen              ?
  Pietrkowski                        Morris                        10.09.1925 Łódź                    Polen              ?
  Pik                                Berek                         02.03.1910 Widawa                  Polen              BRD
  Pilc                               Georg                         08.01.1924 Dąbrowa Górnicza        Polen              USA
  Piotrowski                         Henoch                        05.01.1913 Łódź                    Polen              USA
  Plotek                             Isaak                         21.02.1907 Łódź                    Polen              BRD
  Potok                              Hedwig                        15.04.1922 Beuthen/Oberschlesien   Deutschland        BRD
  Prashker                           Rosa                          15.07.1920 Sosnowiec               Polen              USA
  Pressman                           Alina                         09.03.1921 Warsaw                  Polen              ?
  Pretselmayer                       Sarah                         05.05.1924 Lipice                  Tschechoslowakei   ?
  Przechadzki                        Meir                          02.08.1924 Krakau                  Polen              ?
  Rajchbart                          Abram                         10.03.1901 Laski                   Polen              ?
  Ramras                             Josef                         25.05.1924 Oświęcim                Polen              USA
  Rappaport                          Jakob                         06.10.1909 Piotrków Trybunalski    Polen              Israel
  Ravett                             Murray                                -- Pustelnik/Warsawa       Polen              ?
  Raykhman                           Tsvi                          22.07.1926 Łódź                    Polen              ?
  Reich                              Joseph                        26.12.1924 Bedzin                  Polen              ?
  Reifer                             Samuel                        15.12.1921 Chrzanów                Polen              ?
  Rosenberger                        Ignac                                  ? ?                       ?                  ?
  Rosenblatt                         Henry                         02.08.1919 Siewierz                Polen              ?
  Rozenbaum                          Miriam                        08.01.1924 Trzebinia               Polen              ?
  Rubin                              Mendel E.                     05.01.1933 Encs                    Ungarn             USA
  Rusinek                            Adam                          22.05.1919 Kromolów                Polen              ?
  Rusk                               Laura                         05.12.1922 Sosnowiec               Polen              ?
                                                                                                                         
  Name                               Vorname                       geboren am Geburtsort              Geb.-Nat.          Emmigration 
                                                                                                                         
  Sachs                              Israel                        25.03.1926 Przyrów                 Polen              ?
  Sander                             Julius                        22.10.1918 Bedzin                  Polen              ?
  Sandovski                          Menahém-Mendel                26.02.1923 Łódź                    Polen              ?
  Sayone                             Bernie                        06.09.1922 Chmielnik/Kielce        Polen              ?
  Schenk                             Kathy                         20.03.1924 Olkusz                  Polen              ?
  Schmelzer                          Freida                        07.12.1922 Turulung                Rumänien           ?
  Schneider                          Alex                          08.03.1932 Kosino/Berehovo         Tschechoslowakei   ?
  Schreiber                          Isabel                        23.01.1922 Budapest                Ungarn             ?
  Schreiber                          Jacob                         15.04.1917 Jaworow/Lwów            Polen              ?
  Sekhvi                             Shalom                        28.05.1928 Sosnowiec               Polen              ?
  Shefer                             David                         16.10.1924                                            ?
  Shore                              Bernard                       24.01.1929 Chust                   Tschechoslowakei   ?
  Shore                              William                       26.02.1921                         u                  ?
  Simkovich                          Freda                         14.07.1914 Benatina                Tschechoslowakei   ?
  Small                              Morris                        14.12.1913 Sobkow                  Polen              ?
  Snow                               Isabella                      18.05.1926 Targul-Lapusului        Rumänien           ?
  Sonenfeld                          Veronika                      30.06.1920 Bajmok                  Jugolawien         ?
  Spindler                           Oskar                         11.02.1909 Budapest                Ungarn             ?
  Storch                             Marty                         06.01.1924 Ozorków                 Polen              ?
  Strul                              Ruchama                       10.02.1927 Staszów/Kielce          Polen              ?
  Sugár                              Lászl                         05.08.1927 Sopron                  Ungarn             ?
  Szpigiel                           Harry                         29.01.1925 Łódź                    Polen              ?
  Sakrowitsch                        Schlomo                             1928 Łódź                    Polen              ?
  Samuel                             Frankel                                ? ?                       ?                  USA
  Samuel                             Irene                         10.06.1918 Petrowa                 Tschechoslowakei   USA
  Schiffer                           Emerich                       11.10.1898 Liptovský Mikuláš       Tschechoslowakei   Israel
  Schilit                            Janek                         05.08.1914 Jaloschin/Welonyen      Polen              ?
  Schwarcz                           Abraham Armin                       1926 Vámfalu                 Rumänien           ?
  Sliwka                             Bronia                                 ? ?                       Polen              USA
  Sobotka                            Gerszon                       19.12.1912 ?                       ?                  Schweden
  Steinmetz                          Salomon                       23.10.1928 Neresnice               Tschechoslowakei   USA
  Steinmetz                          Shlomo                                 ? Nereznice               Russland           ?
  Stellmach                          Ludwig Egon                   20.02.1905 Oppeln                  Deutschland        BRD
  Strauss                            Fritz                         22.01.1902 Buchen                  Deutschland        BRD
  Szpigel                            Mendel                        29.01.1920 Łódź                    Polen              Kanada
  Testyler                           Charles                       16.06.1927 Sosnowiec               Polen              ?
  Timberg                            Abraham                             1920 Oświęcim                Polen              ?
  Toroncyk                           Ber Leib                      22.05.1909 Łódź                    Polen              Israel
  Tsukér                             David                         13.07.1920 Przedbórz/Kielce        Polen              ?
  Tsur                               Tsvi                          26.06.1923 Warsaw                  Polen              ?
  Tyller                             Effraim Hermann               18.01.1901 Łódź                    Polen              Israel
  Tyller                             Jechiel                             1800 Łódź                    Polen              Israel
  Tyler                              Katalin                       27.08.1924 Berettyóújfalu          Ungarn             ?
  Urbinder                           Klara                         12.09.1928 Oradea                  Rumänien           ?
  Urman                              Solomon                       15.10.1924 Bedzin                  Polen              ?
  Vogler                             Henryk                        06.03.1911 Krakau                  Polen              Polen
  W.                                 Doris                         28.11.1925 Teplice                 Tschechoslowakei   Tschechoslowakei
  Wachsmann                          Max                           08.02.1918 Jaworzno                Polen              Brasilien
                                                                                                                         
  Name                               Vorname                       geboren am Geburtsort              Geb.-Nat.          Emmigration 
                                                                                                                         
  Walczak                            Wlodzimierz                   01.08.1923 Łódź                    Polen              ?
  Weinryb                            Ignatz/Irving                 20.09.1923 Będzin                  Polen              USA
  Weinryb                            Samak                         05.05.1914 Będzin                  Polen              USA
  Weinstein                          Blima                         15.06.1915 Sosnowiec               Polen              USA
  Weintraub                          Isaac                         14.07.1907 Łódź                    Polen              USA
  Weisberg                           Mila                          07.08.1927 Kielce                  Polen              Polen
  Weiss                              Atleka                                 ? ?                       ?                  ?
  Weiss                              Ernest                        31.01.1928 Mád                     Ungarn             ?
  Weitzmann                          Hermann                                ? ?                       Deutschland        USA
  Wertheimer ($\leadsto $ Rotmann)   Edith ($\leadsto$ Sandor)              ? Budapest                Ungarn             ?
  Widawski                           Jehuda                        26.08.1912 Łódź                    Polen              Israel
  Wiener                             Sara                          20.05.1920 Wolbrom                 Polen              ?
  Wilensky                           Magda                         13.12.1924 Kvasy                   Tschechoslowakei   ?
  Wilf                               Irving Israel                 06.02.1909 Łódź                    Polen              ?
  Winkler                            Klara                                  ? ?                       ?                  ?
  White                              David                         30.05.1912 Vilna                   Polen              ?
  Wodesmann                          Max                           08.02.1928 Jaworzno                Polen              BRD
  Wolff                              Fritz                         20.02.1896 Ostfelde                Deutschland        BRD
  Wolkowicz                          Abraham                       06.02.1911 Łódź                    Polen              Israel
  Wyszegrodzki                       Leib                          16.04.1908 Łódź                    Polen              Israel
  Yakov                              Vanger                                 ? ?                       ?                  ?
  Varga                              Edit                          22.04.1920 Tileagd                 Rumänien           ?
  Váys                               Yehudit                       01.01.1929 Tiszadada               Ungarn             ?
  Zaks                               Chaja                         11.10.1914 Sławków                 Polen              Israel
  Zelig                              Leon                                   ? ?                       ?                  USA
  Zelig                              Myrtin                        10.05.1921 Będzin                  Polen              ?
  Zeliger                            Josef                                  ? ?                       ?                  ?
  Zicherman                          Arthur                        12.04.1927 Berehovo                Tschechoslowakei   ?
  Zilbershtáyn                       Ya'akóv Tsvi                  24.10.1924 Tomaszów Mazowiecki     Polen              ?
  Znamirowski                        Teddy                         27.05.1929 Łódź                    Polen              ?
  Zuckermann                         Leo                           01.11.1928 Łódź                    Polen              ?
  Zwaaf                              Barend                        25.12.1921 Amsterdam               Niederlande        ?
  Zygielbaum                         Adele                         15.12.1924 Slawków                 Polen              ?
  ---------------------------------- --------------------------- ------------ ----------------------- ------------------ ------------------

  : (Fortsetzung)
:::
