## Verzeichnisse

### Literaturverzeichnis {#literaturverzeichnis .unnumbered}

:   Abteilung Kultur beim Rat der Stadt Görlitz (Hsg.): Mit Schweiß und
    Blut gedüngter Boden im Biesnitzer Grund, in: Görlitzer
    Kulturspiegel. Ausgabe September 1955. Görlitz 1955.

:   Kitia Altman: Die Hoffnung auf das Überleben -- Alfred Roßners Hilfe
    für die Juden in Będzin.In Wolfgang Benz (Hrsg): Dachauer Hefte
    Jahrgang 20, S. 194ff.

:   Wolfgang Benz: Selbstbehauptung und Gegenwehr von Verfolgten. In:
    Deutscher Widerstand 1933--1945. Bundeszentrale für politische
    Bildung (Hrsg.). Bonn 1994.

:   Wolfgang Benz: Die Allgegenwart des Konzentrationslagers. Außenlager
    im nationalsozialistischen KZ-System. In: Wolfgang Benz / Barbara
    Distel (Hrsg.): Das Ende der Konzentrationslager. Dachauer Hefte 20.
    Jahrgang. Heft 20. Dachau 2004.

:   David van Biema: Poisoned Lives -- Two men met in a Nazi slave labor
    camp 44 years ago. One was a victim, the other a torturer, and both
    were Jews. Since then, one has prayed for justice, the other to
    forget. Both have failed, miserably.Washington Post, 24. April 1988.

:   Heinz Boberach / Rolf Thomas / Hermann Weiss: Ämter, Abkürzungen,
    Aktionen des NS-Staates. K. G. Saur (Hrg.). Instituts für
    Zeitgeschichte. München 1997.

:   Eugenius Brzezicki / Adolf Gawalewicz / Tadeus Hołuj, Antoni
    Kępiński  Stanisław Kłodziński, Władysław Wolter: Die
    Funktionshäftlinge nationalsozialistischer Konzentrationslager.
    Hamburger Institut für Sozialforschung (Hrsg.): Die Auschwitz-Hefte.
    Rogner & Bernhard. Hamburg 1995.

:   Bundeszentrale für politische Bildung (Hrsg.): Gedenkstätten für die
    Opfer des Nationalsozialismus. Bonn 1999.

:   Danuta Czech: Kalendarium der Ereignisse im Konzentrationslager
    Auschwitz-Birkenau 1939--1945. Rowohlt. Reinbeck 1989.

:   Adolf Eichmann: Götzen. Unveröffentlichtes Manuskript seiner
    Aufzeichnung im Gefängnis in Haifa, was Eichmann mit diesem Namen
    versah. O.J.

:   Alexander Fischer (Hg.): Teheran -- Jalta -- Potsdam. Die
    sowjetischen Protokolle von den Kriegskonferenzen der Großen
    Drei, S. 184f. Köln 1985.

:   Franck'sche Verlagshandlung (Hsg.): Motortechnische Zeitschrift.
    Ausgabe 04/1952. Stuttgart 1952.

:   Franck'sche Verlagshandlung (Hsg.): Motortechnische Zeitschrift.
    Ausgabe 07/1953. Stuttgart 1953.

:   Robert Gellately: Hingeschaut und weggesehen -- Hitler und sein
    Volk. Deutsche Verlagsanstalt München. München 2002.

:   Georg K. Glaser: Geheimnis und Gewalt -- Der autobiographische
    Bericht eines Einzelkämpfers. Rowohlt Taschenbuch. Hamburg 1983.

:   Schlomo Graber: Schljame -- Von Ungarn durch Auschwitz-Birkenau,
    Fünfteichen und Görlitz nach Israel. Jüdische Familiengeschichte.
    1859--2001. Hartung-Gorre Verlag. Konstanz 2002.

:   Karl-Heinz Gräfe / Hans-Jürgen Töpfer: Ausgesondert und fast
    vergessen, KZ-Außenlager auf dem Territorium des heutigen Sachsen.
    DDP. Dresden 1996.

:   Robert Heinze: Ortschronik Rennersdorf. Unveröffentlicht. o.Z.

:   Rolf Helm: Anwalt des Volkes -- Erinnerungen. Dietz Verlag. Berlin
    1978.

:   Raul Hilberg: Sonderzüge nach Auschwitz. Die amerikanische
    Originalausgabe wurde 1976 unter dem Titel The Role of the German
    Railroads in the Destruction of the Jews veröffentlicht.
    Horst-Werner Dumjahn Verlag. Mainz 1981.

:   Raul Hilberg: Die Vernichtung der europäischen Juden. Band 2., 9.
    Auflage, Fischer-Taschenbuchverlag. Frankfurt a.M. 1999.

:   Siegfried Hittig: Jahre Altbernsdorf auf dem Eigen. 1234--1984. Nowa
    Doba. Bautzen 1984.

:   Anna Hyndráková: Letter to my children. In: World without human
    dimension. State Jewish Museum Praque. Praque 1991.

:   Heinz Israel: Im Wandel der Zeit -- 1285--1985, Beiträge zur
    700-Jahrfeier der Gemeinde Deutsch-Paulsdorf. Deutsch-Paulsdorf 1985

:   Hermann Kaienburg (Hrsg.): Wie konnte es soweit kommen?. In:
    Konzentrationslager und deutsche Wirtschaft. Leske + Budrich Verlag.
    Opladen 1996.

:   Alfred Konieczny: Frauen im Konzentrationslager Groß-Rosen in den
    Jahren 1944--1945. Państwowe Muzeum Gross-Rosen. Wałbzych 1998.

:   Alfred Konieczny: Das KZ Groß-Rosen in Niederschlesien, S. 316, in:
    Ulrich Herbert, Karin Orth, Christoph Dieckmann (Hsg.): Die
    nationalsozialistischen Konzentrationslager in Entwicklung und
    Struktur, Band. 1, Wallstein Verlag, Göttingen 1998.

:   Joël Kotek / Pierre Rigoulot: Das Jahrhundert der Lager -
    Gefangenschaft, Zwangsarbeit, Vernichtung. Propyläen Verlag. München
    2001.

:   Ernst Kretzschmer: Görlitz unter dem Hakenkreuz. Edition 3.
    Städtische Kunstsammlung Görlitz. Görlitz 1982.

:   Hermann Langbein: Widerstand in den nationalsozialistischen
    Konzentrationslagern. Fischer Taschenbuchverlag. Frankfurt a.M.
    1980.

:   Hannelore Lauerwald: Im fremden Land -- Kriegsgefangenenlager Stalag
    VIII A. Tatsachen - Briefe - Dokumente. Sächsische Landeszentrale
    für Politische Bildung (Hrsg.). Viadukt-Verlag. Görlitz 1997.

:   Henry Leide: NS-Verbrecher und Staatssicherheit. Vandenhoeck &
    Rubrecht. Göttingen 2005.

:   Herbert Obenaus: Die Außenkommandos des Konzentrationslagers
    Neuengame. In: Hermann Kaienburg (Hrg.): Konzentrationslager und
    deutsche Wirtschaft. Leske und Budrich. Opladen 1996.

:   Karin Orth: Experten des Terrors. Die Konzentrationslager, SS und
    die Shoah. In: Gerhard Paul (Hrg.): Die Täter der Shoah. Wallstein
    Verlag. Göttingen. 2002.

:   Roland Otto: Die Verfolgung der Juden in Görlitz unter der
    faschistischen Diktatur 1933--1945. Stadtverwaltung Görlitz (Hrsg.).
    Görlitz 1990.

:   Pavla Placha und Andrea Rudorff: Reichenau (Rychnov u Jablonce nad
    Nison). In: Wolf­gang Benz / Bar­bara Die­s­tel (Hrgs.): Der Ort des
    Terrors. Geschichte der nationalsozialistischen Konzentrationslager.
    Band 6: Natzweiler, Groß-Rosen, StutthofS. 421-426.  Ver­lag
    C.H.Beck, Mün­chen 2008.

:   Peter Reicherl: Vergangenheitsbewältigung. C.H.Beck. München 2001.

:   Jakob Rosenbaum: Von Görlitz nach Tirol. In: Zeitschrift für
    Geschichte Nr. 5: Fun Lecten Churbn (from the last extermination).
    München. Mai 1947.

:   Dieter Rostowski: Todesmärsche in der Oberlausitz. Selbstverlag.
    Kamenz 2003.

:   Dieter Rostowski / Marlies Röhle: Vom KZ-AL Niesky nach Brandhofen
    (Spohla). Warum ein Dorf bei Hoyerswerda 1945 geschichtsträchtig
    wurde.. Selbstverlag. Kamenz 2005.

:   Hans Rothfels / Theodor Eschenburg: Die wirtschaftlichen
    Unternehmungen der SS. Deutsche Verlags-Anstalt. Stuttgart 1963.

:   Andrea Rudorff: Das Lagersystem der Organisation Schmelt in
    Oberschlesien. In: Der Ort des Terrors. Geschichte der
    nationalsozialistischen Konzentrationslager. Band 9:
    Arbeitserziehungslager, Ghettos, Jungendschutzlager,
    Polizeihaftlager, Sonderlager, Zigeunerlager, Zwangsarbeitslager.
    Band. 9. C.H.Beck. München 2009.

:   Mike Schmeitzner: Der Fall Mutschmann -- Sachsens Gauleiter vor
    Stalins Tribunal. 2. Auflage 2011. Sax-Verlag. Beucha Markkleeberg
    2011.

:   Franz Scholz: Görlitzer Tagebuch. Chronik einer Vertreibung
    1945/1946. 2. Aufl. Ullstein Zeitgeschichte. Berlin 1988.

:   Jürgen Schröder (Hrg.): Jahre WUMAG. 1948--1998.. WUMAG.
    Krefeld 1998.

:   Simon Schweitzer (Hrg.) / Milly Charon: Simons langer Weg.
    Büchergilde Gutenberg. Frankfurt a.M. 2002.

:   Wolfgang Sofsky: Die Ordnung des Terrors. Das Konzentrationslager.
    Fischer Verlag. Frankfurt a.M. 1993.

:   Isabell Sprenger: Gross Rosen. Ein Konzentrationslager in Schlesien.
    Böhlau Verlag. Köln 1996.

:   Dorota Sula und Andrea Rudorff: Zittau, in: Wolfgang Benz / Barbara
    Diestel (Hrgs.): Der Ort des Terrors. Geschichte der
    nationalsozialistischen Konzentrationslager. Band 6: Natzweiler,
    Groß-Rosen, StutthofS. 470-473. C.H.Beck. München 2008.

:   Jeffrey Sweet: The Action against Sol Schumann, Dramatists Play
    Service Inc. (Hrsg.) New York 2003.

:   Wolfgang Theurich: Jahre Waggonbau in Görlitz -- 1849-2009.
    EK-Verlag. Freiburg 2009.

:   Karl-Heinz Thielke (Hrg.): Fall 5 -- Ausgewählte Dokumente des
    Flick-Prozesses. VEB Deutscher Verlag der Wissenschaften. Berlin
    1965.

:   Johannes Tuchel: Inspektion der Konzentrationslager 1938--1945.
    Edition Hentrich. 1994.

:   Martin Weinman: Das nationalsozialistische Lagersystem (CCP). 4.
    Auflage. Frankfurt a.M. 2001.

:   VEB Waggonbau Bautzen (Hrsg):Waggonbauer pflegen revolutionäre
    Traditionen. Aus der Geschichte des KZ-Außenlagers in der Maschinen-
    und Waggonfabrik vorm Busch Bautzen.. Bautzen, 1983

:   Henryk Vogler: Autoportret z Pamięci. Wydawnictwo Literackie. Kraków
    1981.

:   Thomas Warkus: Kriegsgefangene und Fremdarbeiter im
    nationalsozialistischen Deutschland 1939--1945. Das Beispiel
    Görlitz.Diplomarbeit. Technische Universität Dresden, Philosophische
    Fakultät, Institut für Geschichte. 1995.

:   Adam Włodek: Najcichszy Sztandar. Krakau, 1945.

:   Kurt Wolf: KZ-Außenlager Görlitz Biesnitzer Grund. Stadt Görlitz
    (Hrg.). Görlitz 2005.

:   Volker Zimmermann: NS-Täter vor Gericht. Justizministerium
    Nordrheinwestpfalen in Zusammenarbeit mit der Mahn- und Gedenkstätte
    der Landeshauptstadt Düsseldorf (Hrsg.). Düsseldorf 2001.

:   Roman Zgłobicki: Obozy i cmentarze Wojenne w Zgorzelcu. Zgorzelec
    1996.

:::: thebibliography
Archivalien

::: footnotesize
Testimonies ehemaliger Häftlinge des Außenlager Görlitz und des
Arbeitslagers der Organisation Schmelt. Zydoswskim Institycie
Historycznym Warszawa, Tlomackie 3/5, 00-090 Warsaw, Polen.

Unterlagen über die Besitzverhältnisse des Gut Oberrennersdorf.
Unitätsarchiv der Evangelischen Brüder-Unität, Zittauer Str. 24, 02747
Herrnhut.

Protokoll der Gemeinderatssitzungen des Jahres 1945 Ren-nersdorf.
Kreisarchiv Löbau-Zittau, Lisa Tetzner Str. 11, Zittau.

WUMAG. Staatsarchiv Dresden, Archivstr. 1, 01069 Dresden.

Muzeum Gross Rosen. Waĺbrzych, Polen.

Ratsarchiv Görlitz. Am Untermarkt 1, Görlitz.

Friedhofsverwaltung Görlitz.

Yad Vashem Holocaust Gedenkstätte Israel.

United States Holocaust Memorial Museum. Washington DC.

Jüdisches Museum Prag.

Visual Shoa Institute / University of Southern California.
:::
::::

### Kartenverzeichnis {#kartenverzeichnis .unnumbered}
