project:
  type: website
  output-dir: ../docs
  render:
  - index.qmd
  - 000-title.qmd
  - 010-intro.qmd
  - 020-goerlitz.qmd
  - 030-evakuierung.qmd
  - 040-ermittlungen.qmd
  - 050-gedenken.qmd
  - 060-zusammenfassung.qmd
  - a070-testiminies.qmd
  - a080-opferlisten.qmd
  - a090-verzeichnisse.qmd
  - a100-about.qmd

website:
  title: "KZ Außenlager Görlitz"

  navbar:
    background: primary
    search: true
    pinned: true
    # contents: auto
    left:
    - text: "Home"
      href: 000-title.qmd
    - text: "about"
      href: about.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
    - text: "Vorwort"
      href: 010-intro.qmd
    - text: "Das KZ-Außenlager Görlitz"
      href: 020-goerlitz.qmd
    - text: "Todesmarsch nach Rennersdorf und Befreiung in Görlitz"
      href: 030-evakuierung.qmd
    - text: "Ermittlungen gegen NS-Verbrechen"
      href: 040-ermittlungen.qmd
    - text: "Gedenken und Erinnerung der Opfer"
      href: 050-gedenken.qmd
    - text: "Zusammenfassung"
      href: 060-zusammenfassung.qmd
    - section: "Anhang"
      contents:
      - text: "Testimonien"
        href: a070-testitmonies.qmd
      - text: "Verzeichnisse von Toten und Überlebenden"
        href: a080-opferlisten.qmd
      - text: "Verzeichnisse"
        href: a090-verzeichnisse.qmd
    - text: "Über dieses Buch"
      href: a100-about.qmd

format:
  html:
    toc: true # hide inline toc
    toc-level: 6
    theme: cosmo
