project:
  type: website
  output-dir: ../docs
  render:
  - index.qmd
  - 000-title.qmd
  - 010-intro.qmd
  - 020-goerlitz.qmd
  - 030-evakuierung.qmd
  - 040-ermittlungen.qmd
  - 050-gedenken.qmd
  - 060-zusammenfassung.qmd
  - a070-testimonies.qmd
  - a080-opferlisten.qmd
  - a090-verzeichnisse.qmd
  - a100-about.qmd
  - about.qmd

website:
  title: "KZ Außenlager Görlitz und Rennersdorf"
  #favicon: logo.png
  site-url: https://nise.github.io/kz-al-goerlitz
  bread-crumbs: true
  open-graph:
    description: ""
    locale: de_DE
  back-to-top-navigation: true
  reader-mode: false
  page-footer:
    left: "Lizensiert unser Creative Commons, CC-BY <br> Niels Seidel: Die KZ-Außenlager Görlitz und Rennersdorf"
    right:
    - href: https://www.nise81.com

  navbar:
    background: primary
    search: true
    pinned: true
    # contents: auto
    right:
    - text: "about"
      href: about.qmd

  sidebar:
    style: "docked"
    # search: true
    contents:
    - text: "Vorwort"
      number-offset: -1
      href: 010-intro.qmd
    - text: "&nbsp;"
    - text: "Das KZ-Außenlager Görlitz"
      number-offset: 0
      href: 020-goerlitz.qmd
    - text: "&nbsp;"
    - text: "Todesmarsch nach Rennersdorf und Befreiung in Görlitz"
      number-offset: [ 2 ]
      href: 030-evakuierung.qmd
    - text: "&nbsp;"
    - text: "Ermittlungen gegen NS-Verbrechen"

      href: 040-ermittlungen.qmd
    - text: "&nbsp;"
    - text: "Gedenken und Erinnerung der Opfer"
      number-offset: 4
      href: 050-gedenken.qmd
    - text: "&nbsp;"
    - text: "Zusammenfassung"
      number-offset: 5
      href: 060-zusammenfassung.qmd
    - text: "&nbsp;"
    - text: "---"
    - section: "Anhang"
      contents:
      - text: "Testimonien"
        href: a070-testimonies.qmd
      - text: "Verzeichnisse von Toten und Überlebenden"
        href: a080-opferlisten.qmd
      #- text: "Verzeichnisse"
      #  href: a090-verzeichnisse.qmd

format:
  html:
    lang: de
    toc: true # show/hide inline toc
    toc-depth: 6
    # toc-location: left
    toc-titel: "Seiteninhalte"
    toc-expand: true
    number-sections: true
    number-depth: 3
    cap-location: bottom
    fig-align: center
    lightbox: true
    theme:
      light: [ flatly, custome.css ] # cosmo
      dark: [ darkly, custome.css ]
